### ISSUE TITLE
Supported indexers

### ISSUE THREAD

**Issue by ludviglundgren** [autobrr/autobrr#1]
We'll start with a subset of trackers/indexers and expand with requests for new ones.

## IRC

- [x] Acid-Lounge
- [x] AlphaRatio
- [x] AnimeBytes
- [x] BeyondHD
- [x] Bit-hdtv
- [x] BTN
- [x] Danishbytes
- [x] DigitalCore
- [x] EMP
- [x] FileList
- [x] GazelleGames
- [x] HDB
- [x] HD-Torrents
- [x] IPTorrents
- [x] MTV
- [x] MAM
- [x] Milkie
- [x] Nebulance
- [x] Norbits
- [x] Orpheus
- [x] PTP
- [x] RED
- [x] RevolutionTT
- [x] SuperBits
- [x] TorrentDay
- [x] TorrentDB
- [x] TorrentLeech
- [x] TorrentSeeds
- [x] TorrentSyndikat
- [x] TranceTraffic
- [x] UHDBits

**Comment by KyleSanderson** [comment]
PTM DC AL TS please.

**Comment by rouggy** [comment]
TB, TS, MTV

**Comment by rouggy** [comment]
Have tried to create one definition for a private tracker (Milkie), where can I send it to you ?

**Comment by ludviglundgren** [comment]
Thanks to @GregTroar there's now support for TorrentDay, TorrentSeeds, Milkie and MTV https://github.com/autobrr/autobrr/pull/45

**Comment by ludviglundgren** [comment]
Thanks to KaiserBh there's now support for AnimeBytes #87

**Comment by moreirait** [comment]
is there way to support LearnFlakes? thanks

**Comment by ludviglundgren** [comment]
> is there way to support LearnFlakes? thanks

Could you join the Discord https://discord.com/invite/WQ2eUycxyT so we can discuss it further? Need more details about it :+1:

**Comment by supersonik1337** [comment]
is there a possibility to add torrent-syndikat and anime-world
both german trackers

**Comment by arubachen** [comment]
Pornbay plz.

**Comment by ludviglundgren** [comment]
Thanks @F4n4t for adding support for TorrentSyndikat https://github.com/autobrr/autobrr/pull/178

**Comment by RaneyDazed** [comment]
Can you guys maybe add in Anthelion?

**Comment by ludviglundgren** [comment]
There is still quite a few indexers to support, but I consider this issue done.

For further requests etc [open a github discussion](https://github.com/autobrr/autobrr/discussions/categories/ideas) instead.

**Comment by henningfredriksen** [comment]
https://subsplease.org please. Anime is a bit more difficult to automate than other content, and this would fully automate my setup in combination with Deluge, Plex and Shoko.

**Comment by shmt86** [comment]
Can you support **ABN**? Thanks.

**Comment by GregTroar** [comment]
Go on ABN forum and you will have the file.

**Comment by bnghtsh** [comment]
Please add desitorrents.tv to indexers. Thank you!

**Comment by fruini** [comment]
Add SugoiMusic please.

**Comment by nowjon** [comment]
Can we add gaytor.rent ? :)

**Comment by paulrnz** [comment]
Aither have justed added IRC/Announce, so please add aither.

**Comment by s0up4200** [comment]
> Aither have justed added IRC/Announce, so please add aither.

working on it!

**Comment by sv3nio** [comment]
Any chance to add support for FunFile.org?

**Comment by s0up4200** [comment]
> Any chance to add support for FunFile.org?

Can you provide some info about how you authenticate to join the #FunFile.org channel?
Would be nice if you get provide some recent announces as well that we can use to check the regex pattern.

**Comment by s0up4200** [comment]
@sv3nio It'd be nice if you could use our **Indexer request template** to provide us all necessary info.
You can create in indexer request here: https://github.com/autobrr/autobrr/issues/new/choose

You can also provide us this info on DIscord if you want.

**Comment by RikT** [comment]
feat (indexer): Add TheDarkCommunity (TDC)
https://thedarkcommunity.cc/

**Comment by martylukyy** [comment]
@RikT
Can you provide us more information about TDC with filling out our Indexer request template?
You can find the template at https://github.com/autobrr/autobrr/issues/new/choose

In case you don't want to share some information here you can also provide this information on Discord.

**Comment by martylukyy** [comment]
> Any chance to add MusicVids? They have RSS only.

autobrr has the `Generic RSS` indexer.
With the `Generic RSS` indexer you can add **any** RSS feed (torrent or magnet) to autobrr.

**Comment by Sonic3R** [comment]
Please add TorrentNetwork, let me know what you need to achieve goal

**Comment by zze0s** [comment]
> Please add TorrentNetwork, let me know what you need to achieve goal

TN, the German one? It's already supported.

**Comment by Sonic3R** [comment]
I'm sorry for misunderstanding from my side...I meant to add categories for TNT like you put for AR,TL,TS, etc

**Comment by mgpsp** [comment]
Any chance Blutopia can be added?

**Comment by s0up4200** [comment]
> Any chance Blutopia can be added?

Blutopia would have to set up an IRC announce channel for that.
You can use Torznab/RSS for Blutopia now though.

**Comment by mgpsp** [comment]
Yeah, was just realizing that. Thanks for the info.

**Comment by fercats99** [comment]
Any chance for getting JPS support? Looks like they don't IRC announce

**Comment by s0up4200** [comment]
> Any chance for getting JPS support? Looks like they don't IRC announce

Hi there. If they don't have IRC, you can still use them via a Torznab feed (Prowlarr). See https://autobrr.com/configuration/feeds#torznab--newznab

**Comment by NostalgicGnome** [comment]
Could you please add support for FearNoPeer (FNP)?

**Comment by zze0s** [comment]
> Could you please add support for FearNoPeer (FNP)?

They do not have IRC announce yet. Open a forum thread or send a staff pm and try convince them to add it. In the mean time, use Generic RSS or Generic Torznab via Prowlarr.

**Comment by faekiva** [comment]
> > Could you please add support for FearNoPeer (FNP)?
> 
> They do not have IRC announce yet. Open a forum thread or send a staff pm and try convince them to add it. In the mean time, use Generic RSS or Generic Torznab via Prowlarr.

Looks like they've added it since this was posted!
