### ISSUE TITLE
Lossless also matches 24bit Lossless in 1.27.1

### ISSUE THREAD

**Issue by Jaonea** [autobrr/autobrr#1001]
Version
1.27.1
![image](https://github.com/autobrr/autobrr/assets/24249324/ebe4b430-d88d-4da0-b1dc-413b2cbec897)

Describe the bug
Quality type Lossless also matches 24bit Lossless

To Reproduce

    Create a filter matching Lossless
    Filter matches announces containing 24bit Lossless

Expected behavior
It should only match 24bit Lossless when that is selected as a quality.

Log Output:
release.store: &{ID:241 FilterStatus:FILTER_APPROVED Rejections:[] Indexer:redacted FilterName:FilterName Protocol:torrent Implementation:IRC Timestamp:2023-06-29 08:09:10.644827446 +0200 CEST m=+478658.964535468 InfoURL:https://redacted.ch TorrentURL:https://redacted.ch/ MagnetURI: GroupID: TorrentID:1111111 TorrentTmpFile: TorrentDataRawBytes:[] TorrentHash: TorrentName:Artist - AlbumName [2014] [Album] - FLAC / 24bit Lossless / Vinyl / Scene Size:0 Title:AlbumName Description: Category:Album Categories:[] Season:0 Episode:0 Year:2014 Resolution: Source:ViNYL Codec:[] Container: HDR:[] Audio:[FLAC LOSSLESS 24BIT Lossless] AudioChannels: Group:Scene Region: Language:[] Proper:false Repack:false Website: Artists:Artist Type: LogScore:0 Origin:Scene Tags:[tags] ReleaseTags:FLAC / 24bit Lossless / Vinyl / Scene Freeleech:false FreeleechPercent:0 Bonus:[] Uploader: PreTime: Other:[] RawCookie: AdditionalSizeCheckRequired:false FilterID:1 Filter:0xc0009ca000 ActionStatus:[]}

Filter settings:
![image](https://github.com/autobrr/autobrr/assets/24249324/912af70e-498f-430c-81a6-680ce98909c1)

It seems that issue #703 is still occurring and #743 does not work
happy to provide any other logs or examples

**Comment by zze0s** [comment]
Hi!

It's indeed still a bug, and known one. The reason is the same for this one https://github.com/autobrr/autobrr/issues/851 .

We made some changes to what is included in `torrentName` when we parse the announce for RED and OPS to improve filtering. This lead to unexpected issues because it now parses it twice in different places, two different ways.

I can't recall the exact reason for the change but it was to improve parsing.

We have gone back and forth with band-aid fixes for this for a while because the proper solution is a bigger commitment, but looking back we should have done that from the start.

Me and the other maintainers are sadly way too busy at the moment to do anything proper. Hopefully I'll be able to prioritize this in a month or two.

**Comment by Jaonea** [comment]
I see, that is unfortunate. I recall when #743 was initially released on develop it worked but then it might be that some torrents weren't picked up, which I didn't catch. 

I'll try to play around with regex to see if I can figure out a good filter at least for redacted and will report back if anything sticks.

Thank you for looking into it and volunteering your time to the project!

**Comment by Jaonea** [comment]
After a couple days this worked so far for me:
\b24b(?:it)?(?:[-\s]\d+(?:\.\d+)?(?:kHz)?)?\b

This should exclude all the following:
24b
24bit
24-48
24b-44
24b-44kHz
24b-44.1kHz
24bit Losless

To test it longterm I would suggest duplicating your current filters and having the duplicate unchanged but only adding the torrents paused. Whereas the original one will run with the regex statement. This way you can easily compare what slipped through and what did not.

**Comment by xerosys** [comment]
> After a couple days this worked so far for me: \b24b(?:it)?(?:[-\s]\d+(?:.\d+)?(?:kHz)?)?\b
> 
> This should exclude all the following: 24b 24bit 24-48 24b-44 24b-44kHz 24b-44.1kHz 24bit Losless
> 
> To test it longterm I would suggest duplicating your current filters and having the duplicate unchanged but only adding the torrents paused. Whereas the original one will run with the regex statement. This way you can easily compare what slipped through and what did not.

Where did you enter in the regex? Was it in Advanced - Match Releases ?

**Comment by zze0s** [comment]
I'm finally working on a fix for this and other music related issues all in one go. See #1373

Plan is to get it out in the next release. Will need some testers, preferably running docker since it's easy to just change the tag.
