### ISSUE TITLE
qBittorrent download speed threshold is ignored

### ISSUE THREAD

**Issue by crahzee** [autobrr/autobrr#1003]
**Version**
v1.27.1

**Describe the bug**
When enabling "Ignore slow torrents" and setting a threshold, autobrr ignores it and adds anyways.

**To Reproduce**
1. Enable "Ignore slow torrents"
2. Set a threshold. (I used 1kbps for testing)
3. Autobrr ignores the threshold when max torrents are reached and adds anyways.
4. See logs.

```
12:30:37.000DEBUG checking client ignore slow torrent rules: &{ConnectionStatus:connected DHTNodes:0 DlInfoData:160451897907 DlInfoSpeed:15127681 DlRateLimit:0 UpInfoData:84515571851 UpInfoSpeed:2141216 UpRateLimit:0}
12:30:37.000DEBUG max active downloads reached and total download speed (14773) above threshold: (1), skipping
12:30:37.000DEBUG active downloads are slower than set limit, lets add it
```

**Expected behavior**
When max torrents are reached and download speed is above the threshold, torrents should not be added.

**Screenshots**
<img width="631" alt="Screenshot 2023-06-29 at 12 29 39 PM" src="https://github.com/autobrr/autobrr/assets/130537138/9833ffc7-b97c-4e1f-aeea-8eb00fa94add">

**Comment by zze0s** [comment]
Hi! I'm pretty sure you need to set the **Ignore condition** for this to work.

And it works with below the threshold, not above, so try increase them to like 10000 (10MB/s). 

That would then be: if max active is hit and the client speed is below 10000 kb/s, add the torrent anyway.

Hope that helps!

**Comment by crahzee** [comment]
Thanks @zze0s I have tried setting both ignore conditions and its the same behaviour. I guess that brings up another bug. After saving the condition and returning to the client settings, the field is empty.

**Comment by zze0s** [comment]
Then that does sound like a proper bug or two :smile:

**Comment by vtruong68** [comment]
I'm experiencing the same behavior where the ignore condition doesn't appear to be saved and the download speed threshold doesn't appear to be respected. I'm using qbittorrent v4.5.5.
