### ISSUE TITLE
[FEATURE REQ] 1337x chat support?

### ISSUE THREAD

**Issue by sam272** [autobrr/autobrr#1005]
Is it possible to use autobrr with 1337x chat?: https://chat.1337x.to/

I know you're focused on private indexers and IRC, but seems closely related since all their uploads are announced there (and they don't have an RSS as far as I can tell)

**Comment by zze0s** [comment]
Hi!

Took a look and pretty sure it's a web client for some IRC service they're running, but there is no info about the actual server part. It might be worth asking them about it.

The web chat client uses polling with GET requests at an interval to get new messages, so no websockets or SSE.

It's possible to build a relay service which does the same poll and then outputs to an IRC channel. I've built a couple of those before. Someone would have to host it tho.

**Comment by sam272** [comment]
I didn't get a response to my support email, but according to the mods in the chat, there isn't a way to access it via IRC. So if you're able to add it to autobrr that would be awesome.

**Comment by zze0s** [comment]
> I didn't get a response to my support email, but according to the mods in the chat, there isn't a way to access it via IRC. So if you're able to add it to autobrr that would be awesome.

A bit of late reply: That's a shame. The web chat really looked to be based on IRC. 

As mentioned earlier it is possible to write a scraper for the web page but I don't really have the time nor want to host that so I'll close this.

You'll have to do with RSS or Torznab via Prowlarr/Jackett.
