### ISSUE TITLE
[FEATURE REQ] Add to top of queue in qbit

### ISSUE THREAD

**Issue by thezak48** [autobrr/autobrr#1012]
**Is your feature request related to a problem? Please describe.**
Need Brrrr faster

**Describe the solution you'd like**
A option to add torrents to the top of the queue in qbit 

**Describe alternatives you've considered**
Means less brrrr

**Additional context**
Soup said it sounds good

**Comment by thezak48** [comment]
May help 
https://github.com/superturkey650/go-qbittorrent/blob/master/qbt/api.go#L440

**Comment by zze0s** [comment]
@thezak48 qBittorrent just released version 4.6.0, and it finally got this option on torrent add :wink:

**Comment by thezak48** [comment]
> @thezak48 qBittorrent just released version 4.6.0, and it finally got this option on torrent add 😉

It has had this option since at least 4.3.9, 4.6.0 just opens it to the WebUI
