### ISSUE TITLE
[FEATURE REQ] Ability to remove some filters/actions from "Recent activity" page

### ISSUE THREAD

**Issue by ext4xfs** [autobrr/autobrr#1018]
**Is your feature request related to a problem? Please describe.**
For some filters, like a freeleech filter, I don't want to see the releases on the "Recent activity" page. It would be nice to have a toggle to keep some filters off of it.

**Describe the solution you'd like**
A toggle for each filter to enable/disable listing on the Recent activity page

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by zze0s** [comment]
I don't see how we can easily implement that without messing up things with releases in general.
