### ISSUE TITLE
docker-compose autobrr will not stay running. Error out of memory

### ISSUE THREAD

**Issue by Reedler01** [autobrr/autobrr#1023]
**Version**
autobrr:latest
**Describe the bug**
Using Docker version 24.0.5, build ced0996 and Docker Compose version v2.15.1 on new install of centos. I have two different identical hosts I've tried to deploy on with the same error below. 

**To Reproduce**
1. I run "docker-compose -f autobrr-compose.yml up -d"
3. Container is rebooting
4. Below is compose.yml
5. Using a basic config.toml with my own generated session secret using the instructions in the config.toml example. 

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    user: 1000:1000
    environment:
      - TZ=America/New_York
    volumes:
      - /home/myuser/autobrr/config:/config
      - /home/myuser/autobrr/log:/log
    ports:
      - 7474:7474
6. See error
fatal could not open sqlite db connection | module=database stack=[{"func":"(*DB).openSQLite","line":"37","source":"sqlite.go"},{"func":"(*DB).Open","line":"71","source":"database.go"},{"func":"main","line":"69","source":"main.go"},{"func":"main","line":"250","source":"proc.go"},{"func":"goexit","line":"1598","source":"asm_amd64.s"}] error=enable wal: unable to open database file: out of memory (14) 

**Expected behavior**
The container to stay running and be able to connect to it. 

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-25 at 11 26 03 PM" src="https://github.com/autobrr/autobrr/assets/26558689/ddb3bdb8-a88d-492b-bd6a-6d35a2c69a32">

<img width="1440" alt="Screenshot 2023-07-25 at 11 44 04 PM" src="https://github.com/autobrr/autobrr/assets/26558689/cb288ba3-018b-49c1-8913-c230720d4e66">

**Desktop (please complete the following information):**
 - OS: centos 9 stream new install with latest updates 
 - Docker version 24.0.5, build ced0996 and Docker Compose version v2.15.1
 
**Smartphone (please complete the following information):**
 - N/A

**Additional context**
Docker and compose running on VM with 4 procs, 12GB memory 100GB HDD
No other container is using port 7474

**Comment by KyleSanderson** [comment]
Are you using NFS or something? it looks like mmap is failing for your filesystem.

**Comment by Reedler01** [comment]
No just standard LVM partitioning on the VM.

**Comment by KyleSanderson** [comment]
> No just standard LVM partitioning on the VM.

Ok, but how is the volume actually exposed - is it using p9 or virtiofs or something? you're 100% certain mmap works on your filesystem? The error indicates a much deeper problem.

**Comment by Reedler01** [comment]
When I run a mount Im showing nsfs on my docker overlays

**Comment by Reedler01** [comment]
It was literally a base centos install and I followed the instructions at https://docs.docker.com/engine/install/centos/

**Comment by Reedler01** [comment]
When I run an lsof |grep mem I show a bunch

**Comment by Reedler01** [comment]
I'm using a gitlab pipeline to deploy. I've also tried manually deploying using the command in the ticket. I don't use portainer to deploy.

**Comment by Reedler01** [comment]
Just spun up an 22.04 ubuntu minimal server and getting the exact same error. Same VM specs the ubuntu has a slightly new version of compose at 2.17.3

**Comment by zze0s** [comment]
Have you checked the permissions of the mounted dir? I've seen issues before when the config dir is not writable, and thus gets the out of memory error.

> Just spun up a 22.04 ubuntu minimal server and getting the exact same error. Same VM specs.

**Comment by Reedler01** [comment]
These are the 3 dirs that the compose created. 
drwxr-xr-x.  2 root             root    25 Jul 26 06:53 config
drwxr-xr-x.  2 root             root     6 Jul 25 22:38 log
drwx------. 19 systemd-coredump root  4096 Jul 30 10:24 postgres

**Comment by Reedler01** [comment]
@zze0s I think that was it. I completely opened up perms on those 3 dirs and the app started. Not ideal but I'll slowly lock them back down until something breaks again.
