### ISSUE TITLE
[FEATURE REQ] Allow smart episode filter to only match one torrent with the latest episode

### ISSUE THREAD

**Issue by pianistrevor** [autobrr/autobrr#1025]
**Is your feature request related to a problem? Please describe.**
I have been using the "Smart Episode" option in my filters, but because of the sites I scrape, there are often multiple downloads of the same episode (different web dls, etc).

**Describe the solution you'd like**
Either change or allow the smart episode filter to only match the first torrent for the given episode

**Describe alternatives you've considered**
I can't think of any other than severely constricting my filters to one indexer, one release group, one web source, etc.

**Additional context**
qBittorrent has this feature in their RSS auto-downloading and it worked great for me before...

**Comment by pianistrevor** [comment]
This could be a case where two matches came in the same wave, since this is an RSS feed. But I don't think so, as I had another instance where two different sites uploaded the same TV episode (two different torrent titles but same release) and autobrr got both.

**Comment by zze0s** [comment]
Hi. You are describing **skip duplicates/unique downloads**.

We have the [this current issue open](https://github.com/autobrr/autobrr/issues/375) for that and this PR https://github.com/autobrr/autobrr/pull/679

Closing this as a dupe.

**Comment by KyleSanderson** [comment]
> **Is your feature request related to a problem? Please describe.** I have been using the "Smart Episode" option in my filters, but because of the sites I scrape, there are often multiple downloads of the same episode (different web dls, etc).
> 
> **Describe the solution you'd like** Either change or allow the smart episode filter to only match the first torrent for the given episode
> 
> **Describe alternatives you've considered** I can't think of any other than severely constricting my filters to one indexer, one release group, one web source, etc.
> 
> **Additional context** qBittorrent has this feature in their RSS auto-downloading and it worked great for me before...

You're just looking for whatever comes out first? doesn't matter if it's an xvid cam, if the 4k DolbyVision HDR10+ with Atmos sound comes out a second later it's too late?

There's upgraderr documented on the site which is quite opinionated, but it may be closer to your actual desire?

**Comment by pianistrevor** [comment]
> > **Is your feature request related to a problem? Please describe.** I have been using the "Smart Episode" option in my filters, but because of the sites I scrape, there are often multiple downloads of the same episode (different web dls, etc).
> > **Describe the solution you'd like** Either change or allow the smart episode filter to only match the first torrent for the given episode
> > **Describe alternatives you've considered** I can't think of any other than severely constricting my filters to one indexer, one release group, one web source, etc.
> > **Additional context** qBittorrent has this feature in their RSS auto-downloading and it worked great for me before...
> 
> You're just looking for whatever comes out first? doesn't matter if it's an xvid cam, if the 4k DolbyVision HDR10+ with Atmos sound comes out a second later it's too late?
> 
> There's upgraderr documented on the site which is quite opinionated, but it may be closer to your actual desire?

No I'm not looking for whatever comes out first. I specifically want a 1080p WEB-DL, but I don't care if it's Disney Plus, Hulu, etc. Sometimes torrent sites will upload more than one episode that's 1080p WEB-DL. Further, I scrape multiple torrent sites with the filter, so it would grab multiple versions of the episode if both sites upload the same thing.

Looks like the linked PR should fix the problem though.
