### ISSUE TITLE
[FEATURE REQ] Indexer DigitalCore now supports seperate unrar tag

### ISSUE THREAD

**Issue by SnippetSpace** [autobrr/autobrr#1031]
**Is your feature request related to a problem? Please describe.**
Digitalcore serves a lot of RARed content and there is currently no way to distinguish this from non compressed content within the Autobrr. The current custom filter option only allows to filter out content tagged p2p/unrar, however is content is considered p2p but RARed this tag still applies.

**Describe the solution you'd like**
Digitalcore just implemented a new separate tag for UNRAR content, splitting UNRAR from P2P.
See here for reference: https://digitalcore.club/rss
Please add this as a filter in autobrr indexer filter options

**Describe alternatives you've considered**
Running unpackerr on my NAS but it is not a solution for my weak machine.

**Additional context**
Discussion thread with administrators: https://digitalcore.club/forum/4/topic/1481/add-logic-to-detect-badly-tagged-unrar-content

**Comment by KyleSanderson** [comment]
Have you considered rar2fs?

**Comment by zze0s** [comment]
I'll take a closer look this weekend. Feel free to ping me next week if I haven't yet responded.

**Comment by zze0s** [comment]
From what I've seen there hasn't been any updates to that thread yet. Nothing new in the announce either. 

We'll have to wait and see if they do any changes and add additional tags to the announce or not. It likely can be done without breaking changes.

**Comment by ERR1R** [comment]
announce is adjusted: 

NEW TORRENT in Movies/1080p :: release :: url :: [p2p,unrar]
