### ISSUE TITLE
[BUG] Empty TorrentID on retried actions

### ISSUE THREAD

**Issue by F4n4t** [autobrr/autobrr#1048]
**Version**
1.28.0

**Describe the bug**
When using the Retry button on a failed action, TorrentID is not passed along for the action.

**To Reproduce**

1. Goto Filters > Actions
2. Set Filter type Exec
3. Call simple bash script with Parameters `"{{ .TorrentName }}" "{{ .TorrentID }}"`

```bash
#!/bin/bash
LOG_FILE="$HOME/autobrr_test_action.log"

echo "$1" "$2">>"$LOG_FILE"
```

**Expected behavior**
TorrentID should be passed on retried action, but is empty. Works only for the initial action.

**Comment by zze0s** [comment]
Thanks for the report! Will look into it!
