### ISSUE TITLE
can't connect to UI remotely

### ISSUE THREAD

**Issue by sam272** [autobrr/autobrr#1060]
Trying to connect to the autobrr UI from a different computer on my home network. Autobrr is running on a windows 10 machine. for the *arrs/transmission/jackett, if I open the right port in windows firewall, I can access their UI from another computer by going to SERVERIP:port, but it isn't working for autobrr. What am I doing wrong?

**Comment by martylukyy** [comment]
Hi!

By default autobrr listens on `127.0.0.1` which is the recommended way when running a reverse proxy, but if you want to expose it to your local network then you must change the host entry in the config.toml from `127.0.0.1` to `0.0.0.0`.
You should be able to find you config.toml in the same directory as you autobrr.exe

**Comment by sam272** [comment]
ah, nice! I was thinking that might do it, but I couldn't figure out how to find the config.toml file. In my setup it ended up being in the Windows/System32 folder which was very tricky to figure out. I guess that's the default working directory for scheduled tasks? Working properly now, thanks!
