### ISSUE TITLE
[FEATURE REQ] ability to pick docker branch

### ISSUE THREAD

**Issue by Silent-Remux** [autobrr/autobrr#1109]
**Describe the solution you'd like**

`ghcr.io/autobrr/autobrr:latest` pulls prerelease RC candidates. a separate stable / develop branch would allow users who don't want to run prerelease to stick to stable.

**Comment by zze0s** [comment]
Thanks for reporting. Was a miss on our end. We have not done pre-releases in the project before but did it this time. `latest` should only be tagged from a proper release.

We have `develop` and `master` already, as well as PR tags.

**Comment by Silent-Remux** [comment]
@zze0s using `:latest` is still pulling the rc release.

**Comment by Silent-Remux** [comment]
> Yes, reverting it to v1.28.0 was not an option because it's not backwards compatible. v1.29.0 and new latest coming soon.

Then in that case, do you want a new ticket showing "update available" fo rc2 when using `:latest` cause surely it should no should update...

**Comment by zze0s** [comment]
Not sure yet, will look into it later this week.

**Comment by Silent-Remux** [comment]
> Not sure yet, will look into it later this week.

Here is what I see.

<img width="727" alt="Screenshot 2023-09-11 at 22 02 36" src="https://github.com/autobrr/autobrr/assets/16107603/9939d15e-5b63-4798-a909-8208bfc12071">

**Comment by zze0s** [comment]
I think that's technically correct that you want to know about pre-release updates if you are on a pre-release. In this case it was a mistake but it's been fixed already.
