### ISSUE TITLE
Macro `TorrentHash` not being parsed for all indexers

### ISSUE THREAD

**Issue by danwilldev** [autobrr/autobrr#1122]
**Version**
1.29.0

**Describe the bug**
When using the {{.TorrentHash}} macro in a filter action. No value is being passed to the Exec action.

**To Reproduce**
1. Run feed from AlphaRatio
2. Add exec action for filter
3. Pass TorrentHash as argument
4. Observe arguments passed to exec command.

**Expected behavior**
Hash to be passed to the exec command as an argument. 

**Screenshots**
![Screenshot_20230915-211054.png](https://github.com/autobrr/autobrr/assets/15017955/3019548a-469d-4d8b-bbe3-2c8b059a5f90)

**Log**
{"level":"info","module":"action","time":"2023-09-12T18:01:32Z","message":"executed command: '/home/custom/pythonScripts/pauseActiveTorrents.py', args: '[]' Octopath Traveler 2 {[FitGirl} Repack\\],alpharatio, total time 13m21.114213473s"}

**Desktop**
 - Debian latest LTS

**Comment by danwilldev** [comment]
Problem identified. See comment: https://discord.com/channels/881212911849209957/1153099455365664858/1153791084070187058

**Comment by zze0s** [comment]
Update: This is still a bug. 

We need to add a check for `TorrentHash` before we parse Marcos so we can download the .torrent if needed.
