### ISSUE TITLE
[INDEXER REQ] ReelFliX

### ISSUE THREAD

**Issue by ColinHebert** [autobrr/autobrr#1126]
**We currently only support indexers with IRC announces.**

# Indexer request

-  Do they have irc announce? Yes `#announce`

### If no existing `autodl-irssi .tracker` file

- Indexer name: `ReelFliX`
- Short name: `RFX`
- URL: `https://reelflix.xyz/`
- Download link examples with key such as `passkey, rss key, auth key, torrent pass` etc.: `https://reelflix.xyz/torrents/download/169`  (UNIT3D tracker)

## Announce examples

Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.

- `Category [Movie] Type [Remux] Name [HomeMade Movie 1998 Director's Cut 1080p BluRay REMUX AVC DD 2.0-FrameShoP] Resolution [1080p] Freeleech [0%] Internal [No] Double Upload [No] Size [16.8 GiB] Uploader [uploaderName] Url [https://reelflix.xyz/torrents/download/169]`

## IRC Network

- Network name: `ReelFliX`
- Network address: `irc.reelflix.xyz`
- Port: `6697`
- SSL/TLS: `Yes`
- NickServ registration required? Check wiki, guides etc: `Yes`
- Is there a required format for the nick? `No`

IRC password in `My Profile > Settings > Security > IRC`, used as SASL PLAIN

## Bonus

Check their categories in the announce an on site

Announce category - `Movie` (this tracker does only movies)

**Comment by martylukyy** [comment]
Hi,

do you happen to know the name of the announce bot?

**Comment by Slikkster** [comment]
The announce bot's name is **WALL-E**
