### ISSUE TITLE
filter with min size of 1TB or 1000GB matches smaller size releases

### ISSUE THREAD

**Issue by z4j3biz** [autobrr/autobrr#1131]
**Version**
Version: 1.29.0

**Describe the bug**
Min size of 1TB or 1000GB matches releases in smaller size.
In my case releases with 935.53 GB when I had set min size of 1TB and 974.19 GB when I had set min size of 1000GB were matched and added to queue.

**To Reproduce**
Set min size to 1TB or 1000GB and wait for release that matches set rule.

**Expected behavior**
If min size is set 1TB or 1000GB do not match releases in smaller size.

**Comment by zze0s** [comment]
This is a matter of different ways to count file size. TB is not the same as TiB. Put in 1TiB and it will work the way you want.
