### ISSUE TITLE
[INDEXER REQ] Bemaniso

### ISSUE THREAD

**Issue by starkayc** [autobrr/autobrr#1135]
**We currently only support indexers with IRC announces.**

# Indexer request

-  Do they have irc announce? Yes
-  Link to existing `autodl-irssi .tracker` file: https://github.com/doggo404/sows-autodl/blob/main/bemaniso.tracker
[bemaniso.tracker.txt](https://github.com/autobrr/autobrr/files/12666936/bemaniso.tracker.txt)

**Comment by Flupster** [comment]
Hey, I've made a first pass attempt at making a definition however I don't have an account and it requires some testing

Could you add this [bemaniso.yaml](https://raw.githubusercontent.com/Flupster/autobrr/bemanisows/internal/indexer/definitions/bemaniso.yaml) to your custom definitions and test it out and report back?

You can find a [guide on installing custom definitions here](https://autobrr.com/configuration/indexers/#custom-indexer-definitions)

**Comment by starkayc** [comment]
Hey, I tried the file but had to add an authkey section for it to work. However, it seems to add the same torrentID on the torrent/download part which cause it to download a different torrent. The correct url would be `https://bemaniso.ws/torrents.php?id=11111` and DL would be `https://bemaniso.ws/torrents.php?action=download&id=23456&authkey=authkey&torrent_pass=pass` opposed to having "11111" for both ends. I saw that there's a definition for orpheus and both sites looks identical with how they download besides needed a authkey so not sure if that'd help. Thanks a lot I appreciate it!

**Comment by Flupster** [comment]
> Hey, I tried the file but had to add an authkey section for it to work. However, it seems to add the same torrentID on the torrent/download part which cause it to download a different torrent. The correct url would be `https://bemaniso.ws/torrents.php?id=11111` and DL would be `https://bemaniso.ws/torrents.php?action=download&id=23456&authkey=authkey&torrent_pass=pass` opposed to having "11111" for both ends. I saw that there's a definition for orpheus and both sites looks identical with how they download besides needed a authkey so not sure if that'd help. Thanks a lot I appreciate it!

Sorry about that! I must have glossed over the id's being different

I've made changes to the yaml file again, I added the authkey setting and changed the regex to understand the ids

Could you test it for me again, I think with your help this should now work :)

**Comment by starkayc** [comment]
> > Hey, I tried the file but had to add an authkey section for it to work. However, it seems to add the same torrentID on the torrent/download part which cause it to download a different torrent. The correct url would be `https://bemaniso.ws/torrents.php?id=11111` and DL would be `https://bemaniso.ws/torrents.php?action=download&id=23456&authkey=authkey&torrent_pass=pass` opposed to having "11111" for both ends. I saw that there's a definition for orpheus and both sites looks identical with how they download besides needed a authkey so not sure if that'd help. Thanks a lot I appreciate it!
> 
> Sorry about that! I must have glossed over the id's being different
> 
> I've made changes to the yaml file again, I added the authkey setting and changed the regex to understand the ids
> 
> Could you test it for me again? I think with your help this should now work :)

I tried the script today and after changing torrenturl from `/torrents.php?action=download&id={{ .torrentId }}&torrent_pass={{ .torrent_pass }}&authkey={{ .authkey }}` to `/torrents.php?action=download&id={{ .torrentId }}&authkey={{ .authkey }}&torrent_pass={{ .torrent_pass }}` it all ended up working out as intended. Thanks again :D

**Comment by Flupster** [comment]
> > > Hey, I tried the file but had to add an authkey section for it to work. However, it seems to add the same torrentID on the torrent/download part which cause it to download a different torrent. The correct url would be `https://bemaniso.ws/torrents.php?id=11111` and DL would be `https://bemaniso.ws/torrents.php?action=download&id=23456&authkey=authkey&torrent_pass=pass` opposed to having "11111" for both ends. I saw that there's a definition for orpheus and both sites looks identical with how they download besides needed a authkey so not sure if that'd help. Thanks a lot I appreciate it!
> > 
> > 
> > Sorry about that! I must have glossed over the id's being different
> > I've made changes to the yaml file again, I added the authkey setting and changed the regex to understand the ids
> > Could you test it for me again? I think with your help this should now work :)
> 
> I tried the script today and after changing torrenturl from `/torrents.php?action=download&id={{ .torrentId }}&torrent_pass={{ .torrent_pass }}&authkey={{ .authkey }}` to `/torrents.php?action=download&id={{ .torrentId }}&authkey={{ .authkey }}&torrent_pass={{ .torrent_pass }}` it all ended up working out as intended. Thanks again :D

The addition of Bemaniso definition should be available by default in version 1.30 :) in the meantime could you test out the new version that adds support for release tags

If you find any problems let us know 😄

**Comment by starkayc** [comment]
> > > > Hey, I tried the file but had to add an authkey section for it to work. However, it seems to add the same torrentID on the torrent/download part which cause it to download a different torrent. The correct url would be `https://bemaniso.ws/torrents.php?id=11111` and DL would be `https://bemaniso.ws/torrents.php?action=download&id=23456&authkey=authkey&torrent_pass=pass` opposed to having "11111" for both ends. I saw that there's a definition for orpheus and both sites looks identical with how they download besides needed a authkey so not sure if that'd help. Thanks a lot I appreciate it!
> > > 
> > > 
> > > Sorry about that! I must have glossed over the id's being different
> > > I've made changes to the yaml file again, I added the authkey setting and changed the regex to understand the ids
> > > Could you test it for me again? I think with your help this should now work :)
> > 
> > 
> > I tried the script today and after changing torrenturl from `/torrents.php?action=download&id={{ .torrentId }}&torrent_pass={{ .torrent_pass }}&authkey={{ .authkey }}` to `/torrents.php?action=download&id={{ .torrentId }}&authkey={{ .authkey }}&torrent_pass={{ .torrent_pass }}` it all ended up working out as intended. Thanks again :D
> 
> The addition of Bemaniso definition should be available by default in version 1.30 :) in the meantime could you test out the new version that adds support for release tags
> 
> If you find any problems let us know 😄

After letting it test with a few torrents it seems to work as intended. Was just double checking that there was no error since I saw the last definition have an error consisting of `line not matching expected regex pattern: Manuel - GAS GAS GAS [2019] [Single] - FLAC / Lossless / WEB - https://bemaniso.ws/torrents.php?id=00000 / https://bemaniso.ws/torrents.php?action=download&id=00000 - eurobeat, initial.d` Though I haven't seen encounter any error after using the updated one. Thanks once again! :D
