### ISSUE TITLE
Release ages are offset by 3 hours in the web UI - Timezone postgres

### ISSUE THREAD

**Issue by euler-leon** [autobrr/autobrr#1138]
**Version**
1.29.0

**Describe the bug**
In the releases page, the age of all releases is 3 hours ahead. My local timezone is GMT+3. This results in the latest releases showing up as being in the future, e.g. age is 3 hours but the release date is actually 3 hours in the future. Basically the releases page is showing me the time in GMT+6.

**Additional context**
I am running autobrr in a Debian 11 LXC container. The timezone of the container is GMT+3. I have a postgres 14 database as the autobrr database in another LXC container.

**Comment by zze0s** [comment]
Hi! You're not the first to discover this issue that only happens with Postgres. We've looked at it multiple times and tried different setups, versions and tried different timezones on containers and web and so on.

Does your database have the same timezone setup?

**Comment by euler-leon** [comment]
I took a look at the database. The timestamp column in the release table is of type timestamp without time zone. But the data in that column looks correct, the times are in my local time (just without the time zone info).

The postgres LXC container and the postgres cluster/server itself have the same time zone as the autobrr container (GMT+3).

**Comment by zze0s** [comment]
@euler-leon Hey, are you able to test the image tag `pr-1343`? It hopefully fixes the issue.
