### ISSUE TITLE
[INDEXER REQ] TorrentHR

### ISSUE THREAD

**Issue by dAtBigFish** [autobrr/autobrr#1141]
# Indexer request

-  Do they have irc announce? Yes 
-  Link to existing `autodl-irssi .tracker` file: https://pastebin.com/XJU9ucfp

If onsite acc is needed for testing purposes let me know and Ill hook it up

**Comment by Flupster** [comment]
Hey could you provide some information about how to be invited to the announce channel?

- NickServ registration required? Check wiki, guides etc: Yes / No
- Is there a required format for the nick? Like `username|bot`? Check wiki, guides etc
- Invite command: Eg. `invitebot announce USERNAME IRCKEY`

**Comment by dAtBigFish** [comment]
No NickServ registration required as auth is handled by unique user key given in userprofile which user enters upon joining server and it gets auto invited to corresponding channels.
No required format for the nick can be any as in username|bot, username|autodl, username|autobrr, etc...
Invite command not needed for #announce channel

**Comment by martylukyy** [comment]
Okay, but where does the user enter that key?
As SASL Plain auth or do you msg/query that key someone?

**Comment by dAtBigFish** [comment]
msg that key to a bot on server

**Comment by Flupster** [comment]
Hey, I've made a first pass attempt at making a definition however I don't have an account and it requires some testing

Could you add this [torrenthr.yaml](https://raw.githubusercontent.com/Flupster/autobrr/indexer/torrentHR/internal/indexer/definitions/torrenthr.yaml) to your custom definitions and test it out and report back?

You can find a [guide on installing custom definitions here](https://autobrr.com/configuration/indexers/#custom-indexer-definitions)

**Comment by dAtBigFish** [comment]
Gave it a quick spin, seems to be working, might need to leave it testing for some time but for now it was successfully added to client.

**Comment by martylukyy** [comment]
We would appreciate if you can leave it on for some testing and report back! 😊

**Comment by zze0s** [comment]
> Gave it a quick spin, seems to be working, might need to leave it testing for some time but for now it was successfully added to client.

Any updates? :smiley:

**Comment by dAtBigFish** [comment]
Everything seems okay. It can be pushed to live.
