### ISSUE TITLE
Autobrr auto exit after running certain amount of time 

### ISSUE THREAD

**Issue by xiNeRoar** [autobrr/autobrr#1159]
**Version**
Latest

**Describe the bug**
i run my autobrr in docker using portainer, and it will shutdown sometime after running a certain amount of time for no reason, i attached the log here hoping someone can help me identify the issue 😦

here is the log;
https://pastebin.com/jXpPpKBX

**Comment by zze0s** [comment]
Hey. That looks like it originated from the daily cron job of Feed cache clearing :thinking:

Are you running any Feeds (RSS,Torznab)?

**Comment by xiNeRoar** [comment]
Yes, I do.
Here is the Feeds that I am using;
![image](https://github.com/autobrr/autobrr/assets/66216186/7b719326-a70e-4d1b-889a-976ded542b64)
shouldn't I use them?

**Comment by zze0s** [comment]
Okay good. No that should be fine. This is the first reports of something seemingly wrong with the cleanup job.

The only thing I can think of is that it's while the cleanup runs the feed update also runs and that causes some issue. I'll have to dig a bit and try some things.

**Comment by xiNeRoar** [comment]
thank you for helping, i can provide more log if it is needed. Just let me know and i am do what you instruct to facilitate your work

**Comment by xiNeRoar** [comment]
how can i clear the feedcache?

**Comment by zze0s** [comment]
Click the dots on the Feeds list item: 
![image](https://github.com/autobrr/autobrr/assets/43699394/870194f6-d597-4112-9e3e-156565de8501)

**Comment by xiNeRoar** [comment]
thank you. i will monitor it closely and let you know if the bug happens again

**Comment by zze0s** [comment]
Any updates on this? Try the latest release and see if that helps.

Will close this for now and you can open it again if needed.
