### ISSUE TITLE
Not all paths are rewritten to the baseUrl

### ISSUE THREAD

**Issue by jkaberg** [autobrr/autobrr#1166]
**Version**
1.31.0

**Describe the bug**
Not all paths are rewritten to the baseUrl (from config) which is set to `baseUrl = "/autobrr/"`. In my case it 404's `Inter-Variable.woff2` (noticed from Chrome->Console) which leads to blank page when accessing `https://subdomain.domain.tld/autobrr`

**To Reproduce**
docker-compose autobrr traefik labels
```
    labels:
      - "traefik.http.routers.autobrr.rule=PathPrefix(`/autobrr`)"
      - "traefik.http.routers.autobrr.entrypoints=web"
      - "traefik.http.services.autobrr.loadbalancer.server.port=7474"
      - "traefik.http.routers.autobrr.middlewares=autobrr-stripprefix"
      - "traefik.http.middlewares.autobrr-stripprefix.stripprefix.prefixes=/autobrr"
```

Set baseUrl in config to "/autobrr/"

**Expected behavior**
Display autobrr interface

**Desktop (please complete the following information):**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by martylukyy** [comment]
Hi,

i couldn't reproduce your issue but found a speculative fix during debugging.
Can you test docker tag `pr-1167` and report back if that fixed your issue?

**Comment by jkaberg** [comment]
@martylukyy So further testing before you're fix I found out that if append `/` to `/autobrr` (eg `/autobrr/`) it works with the info from OP. I notice that baseUrl in for instance Radarr and Sonarr is setup to `/radarr` and `/sonarr` respectively works just fine and doesn't need to append `/` to `/baseurl`

Might seem like an trivial thing now, but fixing this would bring it inline with other apps

I'll test you're fix and get back to you

**Comment by jkaberg** [comment]
Just tested `pr-1167` and still the same issue

**Comment by zze0s** [comment]
Hey. When we implemented baseUrl support we did a mistake to not do it properly and mount the api paths with the baseurl in front. This is why rewrite on proxy level is required when using baseurl.

Your Traefik setup does look correct, but I'll try it out and see.

**Comment by theQ23** [comment]
i'm on version 1.42.0 and not all the url's are getting rewritten with base url
The URL for Inter-Variable.woff2 doesn't get rewritten
This results in a blank page.
![image](https://github.com/autobrr/autobrr/assets/16393735/9c854a18-02b1-4147-9c91-00c82290b704)

**Comment by theQ23** [comment]
In the CSS for the font-face declaration

url("Inter-Variable.woff2") format("woff2");

needs to be change to 

url("./Inter-Variable.woff2") format("woff2");

![image](https://github.com/autobrr/autobrr/assets/16393735/cdc5fa45-02f8-43cd-be41-26b8a28e715b)

**Comment by adrianipopescu** [comment]
Is this still happening? So I know to not go down this route today :)

**Comment by zze0s** [comment]
> Is this still happening? So I know to not go down this route today :)

Just tested and have this working.

```yaml
labels:
  - "traefik.enable=true"
  - "traefik.docker.network=proxy"

  - "traefik.http.middlewares.autobrr-strip.stripprefix.prefixes=/autobrr"
  - "traefik.http.middlewares.autobrr-strip.stripprefix.forceSlash=true"

  - "traefik.http.routers.autobrr-baseurl.rule=Host(`full.domain.com`) && PathPrefix(`/autobrr`)"
  - "traefik.http.routers.autobrr-baseurl.middlewares=autobrr-strip"
  - "traefik.http.routers.autobrr-baseurl.entrypoints=https"
  - "traefik.http.routers.autobrr-baseurl.tls=true"
  - "traefik.http.routers.autobrr-baseurl.tls.certresolver=letsencrypt"
  - "traefik.http.routers.autobrr-baseurl.service=autobrr-baseurl"
  - "traefik.http.services.autobrr-baseurl.loadbalancer.server.port=7474"
```
