### ISSUE TITLE
RMT (Romanian Metal Torrents) iPLAY IRC problem

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#1168]
When the IRC (SASL or NickServ) indexer is turned on, the network issues an error. After restarting the machine, it also does not work. After deleting the indexer and deleting the network, it is not immediately deleted, but you have to reboot again. After that, the network starts working, but the channel is not.

![2023-10-04_16-24-47](https://github.com/autobrr/autobrr/assets/1818579/66569534-5a67-4e08-b0b3-3921173c6f83)

The TLC does not support this tracker yet.

**Comment by zze0s** [comment]
None of the maintainers have access to debug this.

Can you enable TRACE logs and do a restart of the IRC network and send the logs to me on Discord?

**Comment by bulletproof2k** [comment]
[Dashboard.txt](https://github.com/autobrr/autobrr/files/13186017/Dashboard.txt)
p.s. banned on Discord

**Comment by martylukyy** [comment]
@bulletproof2k 
I removed your comment since you leaked your passkeys in the logs..
If you post log please make sure you use the logs download feature in the UI which will redact all your secrets
or redact them by hand before posting..

**Comment by bulletproof2k** [comment]
> @bulletproof2k I removed your comment since you leaked your passkeys in the logs.. If you post logs please make sure you use the logs download feature in the UI which will redact all your secrets or redact them by hand before posting..

Where can I find the brr logs?

**Comment by martylukyy** [comment]
First we need to make sure that log files are being generated:
To generate log files which can be cleaned by autobrr please uncomment the `logpath` directive in the `config.toml`.
After restart autobrr you should see a `log` folder in the folder where your `config.toml` is located.

Now autobrr is creating log files which can be later downloaded on the lower part of the logs page in autobrr.
Clicking the download button on the right will now clean your log files of any secrets and download them.

**Comment by bulletproof2k** [comment]
> First we need to make sure that log files are being generated: To generate log files which can be cleaned by autobrr please uncomment the `logpath` directive in the `config.toml`. After restart autobrr you should see a `log` folder in the folder where your `config.toml` is located. For more information see: https://autobrr.com/configuration/autobrr
> 
> Now autobrr is creating log files which can be later downloaded on the lower part of the logs page in autobrr. Clicking the download button on the right will now clean your log files of any secrets and download them.

[autobrr.log](https://github.com/autobrr/autobrr/files/13188362/autobrr.log)
I hope I did everything right.
