### ISSUE TITLE
Superbits IRC doesn't join announce channel after NickServ identification

### ISSUE THREAD

**Issue by Mouton99** [autobrr/autobrr#1207]
**Version**
`latest` `v1.31.0`

**Describe the bug**
Superbits indexer doesn't join announce channel after NickServ authetication.

**To Reproduce**
1. Configure Superbits indexer
2. Check logs when enabling the IRC for Superbits

**Expected behavior**
IRC bot should join the announce channel (`#autodl`) after `/msg NickServ IDENTIFY` succeeds.

**Logs**
See https://gist.github.com/Mouton99/0aae55136f799db43e15e8f2d1582fd2

**Additional context**
```
19:55:55 {"level":"debug","module":"irc","network":"irc.superbits.org","time":"2023-10-21T15:55:55-04:00","message":"NOTICE nickserv logged in: [Mouton99|autodl Password accepted - you are now recognized.]"}
```
This should tell autobrr that identification succeeded, and it can now join the configured channel. Somehow, it doesn't.

**Workaround**
- Remove the Identification configuration (set to `None`, and remove the username & password);
- Specify the NickServ identification command in the `Invite command` field: `/msg NickServ IDENTIFY [Nick] [Password]`.

**Comment by zze0s** [comment]
Not a bug with autobrr, it's on their end.

They don't require registered nicks to join the announce, so using Auth Mechanism None and no info in nickserv account is the way to go.
