### ISSUE TITLE
qBittorrent issues with self-signed cert and TLS skip verify

### ISSUE THREAD

**Issue by funkey7dan** [autobrr/autobrr#1213]
**Version**
Version: v1.31.0,

**Describe the bug**
When trying to add qbittorrent 4.5.5 as client, when pressing "test" i see an error, as can be seen in the screenshot. In the logs i see "tls: failed to verify certificate: x509: certificate signed by unknown authority","time":"2023-10-25T17:58:16+03:00","message":"client connection test error"
I'm using a self signed certificate for the webui of qbittorrent to be able to add magnets from the browser. I checked "skip TLS check", but it still appears to run checks on the certificate that fail.

**Screenshots**
![image](https://github.com/autobrr/autobrr/assets/72495653/acf3bb52-550b-40bb-a50a-dfaafe290430)

**Desktop (please complete the following information):**
Docker compose - ghcr.io/autobrr/autobrr:latest

Thank you in advance!

**Comment by zze0s** [comment]
Hi. Try change from `https` to `http` and disable TLS and Skip TLS verification.

Is autobrr also in docker? 127.0.0.1 is probably not right then, use the container name instead like `http://qbittorrent:8080` or however you have it setup.

**Comment by funkey7dan** [comment]
> Hi. Try change from `https` to `http` and disable TLS and Skip TLS verification.
> 
> Is autobrr also in docker? 127.0.0.1 is probably not right then, use the container name instead like `http://qbittorrent:8080` or however you have it setup.

**Comment by funkey7dan** [comment]
Sorry, closed by mistake..
I'm using network_mode: host, so 127.0.0.1 points to the host in the container as well, and when i change to http there is still a connection error, all the requests fail. But it is expected, because the qbittorrent  webui is configured to work with https

**Comment by zze0s** [comment]
I see! This looks to be an actual bug then, sorry about that. 

Will make a fix and update here so you can try the image when ready.

**Comment by zze0s** [comment]
@funkey7dan Hi, have updated the library now which should fix things. Are you able to test the tag? 

Image tag: `ghcr.io/autobrr/autobrr:pr-1217`

Ref https://github.com/autobrr/autobrr/pull/1217

**Comment by funkey7dan** [comment]
> @funkey7dan Hi, have updated the library now which should fix things. Are you able to test the tag?
> 
> Image tag: `ghcr.io/autobrr/autobrr:pr-1217`
> 
> Ref #1217

That fixed it, thank you!
