### ISSUE TITLE
TorrentDay announcer issue on IRC

### ISSUE THREAD

**Issue by jjgadget** [autobrr/autobrr#1215]
**Version**
Latest version

**Describe the bug**
TD IRC channel the last few days has been switching between TD_Announce and TD_Announce0 as their bot. When TD_Announce0 is being used Autobrr ignores those new torrents.

**Expected behavior**
Can TD_Announce0 also be added as a monitored bot?

**Screenshots**
[2023-10-25 17:08:03] TD_Announce0: [Movie/4K] (Info)
[2023-10-25 17:09:09] TD_Announce0: [Movies/XviD] (Info)
[2023-10-25 17:13:39] TD_Announce0: [Movies/Bluray] (Info)

**Comment by s0up4200** [comment]
I don't think we should update our definitions everytime they fail their NickServ auth. They can easily solve this by properly authenticating with NickServ.

A possible solution on our end is to implement the possibility for the user to manually set the name of the announcer in IRC settings, but that needs to be discussed.
