### ISSUE TITLE
HTTP Method "POST" set to Default

### ISSUE THREAD

**Issue by mouzzampk2014** [autobrr/autobrr#1224]
**Version**
Updated :develop branch

**Describe the bug**
Setting up webhook to POST as default

**Screenshots**
![image](https://github.com/autobrr/autobrr/assets/96798778/fc2164a1-4b4c-4b1a-b479-44e73c3f73e8)

Actually not an issue just a possibility to set to default.

Thank you

**Comment by s0up4200** [comment]
It already defaults to POST. See tooltip:

![CleanShot 2023-10-29 at 21 12 25@2x](https://github.com/autobrr/autobrr/assets/18177310/8a815c1f-5a6c-46c5-83db-e260b3ac7713)

It's trivial to update the default text to say POST here, but I'm not sure it's really needed.

Will leave this open for now, in case someone disagrees.

**Comment by mouzzampk2014** [comment]
Thanks my friend, completely make sense. Only if rollover the mouse. 

Thanks again

**Comment by s0up4200** [comment]
It does not default to POST after all apparently. We might do something about that😄
