### ISSUE TITLE
Unable to connect to remote Deluge. Autobrr adds the optional Port at the end.

### ISSUE THREAD

**Issue by persuaded6414** [autobrr/autobrr#1228]
**Version**
v1.31.0

**Describe the bug**
Adding a new Deluge 2 Client, AutoBrr tries to add the Port at the end of the URL.

**To Reproduce**
1. Settings > Clients > add
2. Deluge 2. Host "https://REDACTED.seedhost.eu/REDACTED/qbittorrent/" (port left as 0 since it's optional), enable TLS, add my user and password.
3. Hit "Test" and get "ERROR" (to be honest, it would be great if the error log was listed here directly)

**Expected behavior**
For it to connect

**Screenshots**
It seems like it tries to add the default port "443" at the end of the URL: `https://REDACTED.seedhost.eu/REDACTED/qbittorrent/:443`

If I change the port (from 0 to 1234) then the failed attempt will be to `https://REDACTED.seedhost.eu/REDACTED/qbittorrent/:1234`

Log for Port:0 (default):

```
ERRclient connection test error error="error logging into client: https://REDACTED.seedhost.eu/REDACTED/qbittorrent/: dial tcp: address https://REDACTED.seedhost.eu/REDACTED/qbittorrent/:443: too many colons in address"= module=download_client stack=[{"func":"(*service).testDelugeConnection","line":"135","source":"connection.go"},{"func":"(*service).testConnection","line":"34","source":"connection.go"},{"func":"(*service).Test","line":"131","source":"service.go"},{"func":"downloadClientHandler.test","line":"83","source":"download_client.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"444","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"316","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Server.IsAuthenticated.func1","line":"42","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*ChainHandler).ServeHTTP","line":"31","source":"chain.go"},{"func":"(*Mux).routeHTTP","line":"444","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"316","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"444","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Cors).Handler.func1","line":"281","source":"cors.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"LoggerMiddleware.func1.1","line":"88","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Recoverer.func1","line":"45","source":"recoverer.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RealIP.func1","line":"36","source":"realip.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RequestID.func1","line":"76","source":"request_id.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"90","source":"mux.go"}]
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome and Firefox
 - Version 22.04

**Additional context**

**Comment by zze0s** [comment]
You are trying to add Deluge with an url for qbit? Is that a copy/paste error on your end or what you are actually trying to do?

Did you check our docs for [SeedHost Deluge setup](https://autobrr.com/configuration/download-clients/shared#deluge)? That is the shared services, not sure from your url if you have a dedi or shared.

**Comment by persuaded6414** [comment]
Thanks for that link. I did find reference to that in a search engine however I was getting 404. I checked the other day in the internet archive but the info seemed it was deleted for a purpose.

Didn't see this one in the main site which is a major facepalm for me. Apologies for wasting your time.
