### ISSUE TITLE
Regex filter including commas not working as expected

### ISSUE THREAD

**Issue by jjxxs** [autobrr/autobrr#1241]
**Version**
1.33.0

**Describe the bug**
Advanced filters allow the usage of Regex. Regexes allow commas, e.g. `\.[Ss]\d{1,2}[Ee]\d{1,3}\.` is a valid regex. But the backend will split the user-given regex at the comma, hence resulting in a faulty regex.

**To Reproduce**
Create a advanced filter, e.g. "match release" with a regex like `\.[Ss]\d{1,2}[Ee]\d{1,3}\.`. It will not work as expected.

**Expected behavior**
The regex should work as intended. It is not necessary to allow users to add multiple regexes, separated by comma. This can naturally be achieved by separating them with `|`.

**Additional context**
A workaround would be to use e.g. `\.[Ss]\d\d?E\d\d?\d?\.`. But it is not straight-forward to the user why a regex that uses commas doesn't work as expected. I only understood it after I had a look at the backend-code.

**Comment by jjxxs** [comment]
@zze0s the linked PR won't fix this issue. for the given example, the function introduced in https://github.com/autobrr/autobrr/pull/1212/commits/41811dcabf10f79e6f311d03a5d44fb7824eee70 will produce the following output:

```
\.[Ss]\d{1
3}E\d{1
3}\. 
```

also the linked commit will introduce new issues when escaped brackets are used, e.g. `\(,txt` will not split the regex at the comma.

**Comment by zze0s** [comment]
> @zze0s the linked PR won't fix this issue. for the given example, the function introduced in [41811dc](https://github.com/autobrr/autobrr/commit/41811dcabf10f79e6f311d03a5d44fb7824eee70) will produce the following output:
> 
> ```
> \.[Ss]\d{1
> 3}E\d{1
> 3}\. 
> ```
> 
> also the linked commit will introduce new issues when escaped brackets are used, e.g. `\(,txt` will not split the regex at the comma.
> 
> i would suggest to either let the user use '|' to separate their expressions or extend the UI so that the user can hit a '+' button and a new input-box will appear to enter another regex.

Yeah, aware that that PR needs some more work, but it's a start. The current filters are broken with as is if using regex and comma in there, so there's nothing to break in that sense.

Pipes are also valid inside regex patterns so that is not an option to use as a splitter either.

Having multiple inputs would be ideal and I do consider the filters a design flaw in hindsight.
We have talked about building more of a "rules engine" where you can build the expressions with a nice ui or some expression meta language. Doing that is no small task tho so a quick fix for now would be preferred.

**Comment by jjxxs** [comment]
I think the main issue is that the filters currently accept two different kinds of input:
- a simplified format where '*' and '?' can be used as wildcards [1]
- a regex when the 'use regex'-option is set

Ideally the backend would use two different filter-functions, depending of the state of the 'use regex'-option. Luckily that's what the backend already does:
https://github.com/autobrr/autobrr/blob/17e97201fdfbe892f9299dcb1333514d1643a06b/internal/domain/filter.go#L302-L319

The `matchRegex` function could be changed to stop splitting on `,` which breaks the regex. The 'use regex'-option is opt-in and users can and will use `|` instead the comma to achieve the same effect. Existing filters could easily be migrated on a version-update by replacing the `,` with a `|` for filters where the regex-option is set.

This would make the feature work as intended without breaking anything. No workarounds would be needed.

[1] https://autobrr.com/filters#advanced
