### ISSUE TITLE
[FEATURE REQ] Expand the three dot menu either with an option or if there's enough width available.

### ISSUE THREAD

**Issue by persuaded6414** [autobrr/autobrr#1242]
**Is your feature request related to a problem? Please describe.**
I have plenty of width real estate and having to click the three dot menu doesn't make much sense.

<img width="668" alt="autobrr" src="https://github.com/autobrr/autobrr/assets/117122541/ef8a4d72-a91b-428b-854a-6c969157104a">

**Describe the solution you'd like**
Adding an option that would remove the three dot menu and show the icons with tooltip on hover or make it dynamic based on the available width (on mobile, we would revert to the three dot menu for example).

**Describe alternatives you've considered**
Lose my mind with an extra click every time :)

**Additional context**
Same in the Settings > IRC. My nick is not long enough and the three icons could easily fit in there.

**Comment by zze0s** [comment]
While I get your point, most of those options are rarely tocuhed. You can get to Edit by clicking the filter name (if you didn't know) and the toggle has the button already. Delete you probably don't do all day every day. Duplicate same. Export to JSON every now and then.

Too many buttons would make it cluttered, especially for buttons that are not used frequently.

**Comment by persuaded6414** [comment]
@zze0s thanks. I actually didn't know I could click the filter name. That makes sense.
