### ISSUE TITLE
link for shared seedboxes host infobox results in page not found

### ISSUE THREAD

**Issue by z4j3biz** [autobrr/autobrr#1252]
**Version**
1.33.0

**Describe the bug**
When adding new Client and trying to find info on how to add one i.e. checking Host infobox then it is linking to https://autobrr.com/configuration/download-clients/shared-seedboxes which results in "Page Not Found".

**To Reproduce**
1. Go to 'Settings > Clients'
2. Click on 'Add new'
3. Scroll down to 'Host'

**Expected behavior**
Fix infobox link for shared seedboxes to https://autobrr.com/configuration/download-clients/shared/

**Screenshots**
https://imgur.com/a/A5ool6L

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by s0up4200** [comment]
Hi there. Sorry about that. I'll make sure the docs are corrected asap.
