### ISSUE TITLE
[FEATURE REQ] Generic RSS default "Max Age" is too low; Log that a release is dropped due to old age

### ISSUE THREAD

**Issue by sethidden** [autobrr/autobrr#1280]
**Is your feature request related to a problem? Please describe.**
Hi, I set up Autobrr a few months ago but I couldn't get it to actually fetch things from two of my RSS feeds. I saw that the RSS feeds are downloaded correctly, and my only filter was just the one with all empty fields.

The culprit turned out to be the "Max Age" setting being too strict by default.
You can find it in "Settings > Feeds > (press 3 dots near one of the RSS feeds) > Edit".

The default value of 3600 (1 hour) is too low, because consider this case:
1. A torrent is automatically published at 18:00
2. The tracker is scraped at 21:00 and a RSS feed is generated.

The result is an RSS feed that has an entry that was published at 18:00, but .rss feed with that very entry could've been fetched at the earliest by 21:00, so the "Max age" will drop it.

Here's even a real life case: https://archlinux.org/feeds/releases/
At the top you can see that the RSS feed was added at:
Last updated: Wednesday, November 1, 2023 8:06:32 AM

but the newest entry is from Wednesday, November 1, 2023 1:00:00 AM, so 7 hours earlier.

----

But perhaps that's an one off case, Still, it'd be nice if the logs let the user know, as it's unexpected that feeds are being filtered outside the "Filters". 

Currently the logs look like this, given the case above:
```
023-11-24 17:50:08.868396+01:00{"level":"debug","module":"feed","feed":"Generic RSS","time":"2023-11-24T17:50:08+01:00","message":"found (0) new items to process"}
2023-11-24 18:20:07.325983+01:00{"level":"debug","module":"feed","feed":"archlinux","time":"2023-11-24T18:20:07+01:00","message":"refreshing rss feed: archlinux, found (3) items"}
```

I was wondering if it'd be possible to make Autobrr work like this:
1. Download every 30m like it always does
2. Compare the new RSS against its current RSS feed cache (does something like this exist?)
3. If there are new elements, see if they are older than maxAge. If they are, **LOG** "Found new release but it's older than maxAge, so dropping". If they're not, just accept them as normal.

**Describe the solution you'd like**
1. Consider increasing default RSS maxAge to account for differences between "Publish date of entry as seen in RSS text" and "Date at which the RSS's .xml file actually becomes available on the Internet"
2. Consider logging when a new RSS entry gets dropped due to max age

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by zze0s** [comment]
Time handling with feeds is a bit hit 'n miss. While it does default to `3600` seconds we usually recommend users to set it to `0` which means disable the check and it will then process all releases in the feed.

> It could also be perhaps more intuitive to include "maxAge" as something that gets filtered out in the Filters section, rather than at the "feeds" entity level. That way, too old entries could appear in the "Releases" tab and be shown that they were rejected with a red x.
> 
> Though I understand that the RSS maxAge is currently in the Feeds section because not all sources understand maxAge.

In hindsight maybe it should have been part of the filters instead of the feed settings :thinking:

**Comment by zze0s** [comment]
Not needed, will take care of it in the coming days @sethidden
