### ISSUE TITLE
FLAC/24bit FLAC filter bug

### ISSUE THREAD

**Issue by nostringyoyo** [autobrr/autobrr#129]
Set a music filter to match a handful of genres and only selected 'FLAC' to download but it will download 24bit FLAC as well even though 24bit FLAC is unchecked.

**Comment by ludviglundgren** [comment]
Hi! 

This is captured with RegEx and since FLAC is part of 24bit FLAC it will match that as well. 

But there can potentially be some changes to make it work better when comparing.

Will get back to this and update the ticket with more info when I have it.

**Comment by nostringyoyo** [comment]
Thank you!

**Comment by ludviglundgren** [comment]
Should be fixed with #257
