### ISSUE TITLE
Sanitize Log Output

### ISSUE THREAD

**Issue by brettpetch** [autobrr/autobrr#134]
Remove all auth/api/announce keys from logging.

Examples of regex to remove this kind of data from log output can be found here: https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

/b

**Comment by ludviglundgren** [comment]
That would be nice indeed.. Not an easy task to do properly tho. Will see what I can do. Putting it in the backlog of stuff.
