### ISSUE TITLE
Cannot use case-insensitive regexp

### ISSUE THREAD

**Issue by vkhobor** [autobrr/autobrr#1349]
**Version**
v1.34.1

**Describe the bug**
I cannot use this regexp on New Filter->Advanced tab: (?i)DO NOT|DON'T|CORUPT|CORRUPT|STOP

**To Reproduce**
1. Go to Create New Filter
2. Navigate to Advanced tab
3. Switch on regexp mode
4. Input `(?i)DO NOT|DON'T|CORUPT|CORRUPT|STOP` in Except releases
5. See validation error

**Expected behavior**
I expected that there would be no error.
As the info popup says it supports full golang flavour regex, so I tested my regex on golang playground and it worked there.
https://play.golang.com/p/BZp5k8ILEvA

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 
 **Additional**
 It looks to me that it fails from the javascript regex parsing here: https://github.com/autobrr/autobrr/blob/a86258aaa723ed22b54169756009251c68ca2de3/web/src/components/inputs/input.tsx#L298
 
![Screenshot from 2024-01-15 03-59-29](https://github.com/autobrr/autobrr/assets/47790799/8545790f-a007-4cef-a38e-e200fe6308b4)

**Comment by zze0s** [comment]
Hi! We make all regex case-insensitive by default `(?i)`. You are however missing the capture group here `(?i)DO NOT|DON'T|CORUPT|CORRUPT|STOP` while you have it correct in the playground `(?i)(DO NOT|DON'T|CORUPT|CORRUPT|STOP)`.

This should work: `(DO NOT|DON'T|CORUPT|CORRUPT|STOP)`.

**Comment by vkhobor** [comment]
Thanks. I am going to close this then.
