### ISSUE TITLE
IRC connection error="tls: first record does not look like a TLS handshake"

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#1372]
**v1.35.1** Latest

![2024-01-24_21-16-42](https://github.com/autobrr/autobrr/assets/1818579/d08d2659-41d2-4ebf-a2c7-7eccb4c2fca0)
[autobrr.log](https://github.com/autobrr/autobrr/files/14042488/autobrr.log)

Stopped working:

**FunFile** (maybe they work, but they show that they don't work)
**HD-Space**
**HD-Torrents**
**Milkie**
**PTFiles**
**ReelFliX** (maybe they work, but they show that they don't work)
**RetroFlix**
**SpeedApp**
**iAnon** (maybe they work, but they show that they don't work)

I log into the desktop IRС client without any problems.
About 30 IRS trackers have been added, it may not be able to cope with such a large number.

**Comment by zze0s** [comment]
Hey. Knowing your history of other issues I'm pretty confident this is something only related to your environment. Looks like it's been in a crash-loop.

**Comment by bulletproof2k** [comment]
> Hey. Knowing your history of other issues I'm pretty confident this is something only related to your environment. Looks like it's been in a crash-loop.

Hi. Knowing how you respond to requests, I haven't really received a single answer that would solve at least one of my problems related to brr. Moreover, I am sure that there can be no problems on my part. In your case, this is not the answer I expected from the developer. Nevertheless, I expect a reasonable answer from you, at least in which direction to "drip"? It's best to write "this is a problem on your part."

**Comment by zze0s** [comment]
My apologies.

In the past you have posted several issues in here and other places which has been user configuration related or external factors like IRC networks being down or similar.

Usually that many indexers/networks does not have issues at the same time and if it was something with autobrr we would have more reports of issues with it from the past few updates. We've had other WEB UI related issues but IRC has been stable.

Your logs show that it seem to restart frequently, and I suspect because of a panic somewhere but it does not write that into the logs. If you run with Docker you should be able to see more logs and similar with systemd services you could look with journalctl and look at the service logs and see if it shows anything.

TLS handshake issues could maybe be indicated by IP ban or maybe a MiTM or similar.

**Comment by bulletproof2k** [comment]
I'm using the Windows version.
Is there a FlareSolverr running in the system, could it be related in some way? And then why do I log into these networks through the desktop client without any problems, and they worked properly some time ago?

**Comment by bulletproof2k** [comment]
After a while I get this error:
### client encountered connection error error="read tcp 192.168.*.**:53263->188.240.145.30:6697: wsarecv: An existing connection was forcibly closed by the remote host."= module=irc network=irc.rizon.net

**Comment by zze0s** [comment]
Can you look at the windows console autobrr is running via and see if it crashes and restarts?

Can you also try disconnect from your desktop client and connect to a single network? Some networks have limits on users per IP. Are you using two different nicks, one for desktop client and a bot nick for autobrr? That is usually required.

**Comment by bulletproof2k** [comment]
> Can you look at the windows console autobrr is running via and see if it crashes and restarts?
> 
> Can you also try disconnect from your desktop client and connect to a single network? Some networks have limits on users per IP. Are you using two different nicks, one for desktop client and a bot nick for autobrr? That is usually required.

I do the restart myself in order to restart idle networks, I also use different nicknames for networks and channels.

**Comment by zze0s** [comment]
Restarting autobrr itself is not needed, you can restart individual irc networks. I think you are running into some issue with flooding and the IRC networks disconnect you.

Do you have any other pc/server/seedbox you can try run autobrr on?

**Comment by bulletproof2k** [comment]
> Do you have any other pc/server/seedbox you can try run autobrr on?

Nop

**Comment by zze0s** [comment]
I suspect it's something windows related then. I'm not sure what to test next, unfortunately.  Hopefully someone else with more Windows knowledge will chime in.

**Comment by bulletproof2k** [comment]
The problem is solved by using nssm 😊
