### ISSUE TITLE
Transmission HTTPS/TLS/SSL never passes the "Test" button

### ISSUE THREAD

**Issue by rpatterson** [autobrr/autobrr#1374]
**Version**
The autobrr version you're running. If you run something other than latest, please update before reporting issues.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KyleSanderson** [comment]
> **Version** The autobrr version you're running. If you run something other than latest, please update before reporting issues.
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Are you running Transmission 1.2? That's not supported (and Additional information is where you would have put that information).

**Comment by rpatterson** [comment]
I'm so sorry, I was drafting this issue in a tab and hadn't intended to submit it yet. I'll reopen when I finish.

**Comment by KyleSanderson** [comment]
> I'm so sorry, I was drafting this issue in a tab and hadn't intended to submit it yet. I'll reopen when I finish.

All good man - the RPCs are quite different per version, so it could be as something as at a general level it isn't implemented, or it's an issue in our expectations on the library, or it's a bug in the library.

**Comment by rpatterson** [comment]
Ugh, it was indeed user error. I was misremembering *how* I deployed transmission behind Traefik. I thought I used a subdomain but I actually used a sub-path. Of course, I would have figured that out while drafting this issue, as I just did, but *no* I had to go and submit it early somehow! At any rate, please disregard and my apologies for the wasted cycles.

**Comment by KyleSanderson** [comment]
> Ugh, it was indeed user error. I was misremembering _how_ I deployed transmission behind Traefik. I thought I used a subdomain but I actually used a sub-path. Of course, I would have figured that out while drafting this issue, as I just did, but _no_ I had to go and submit it early somehow! At any rate, please disregard and my apologies for the wasted cycles.

Is there anything we can add to the docs to help the next person? If we don't have Traefik in there already maybe this would be a nice opportunity to add something. The entire project exists to help the next person 😺

**Comment by rpatterson** [comment]
> Ugh, it was indeed user error.

To elaborate on helping others, now that I understand my error I also understand what the logs were trying to tell me. I can't think of a way to make the logs more clear without probably also making them less clear for *different* user errors. It would be a better UX to display the error message I went to the logs for in some sort of validation failure message on the form. Better UX for sure, but wouldn't have saved me from myself here.
