### ISSUE TITLE
TypeError when visiting pages

### ISSUE THREAD

**Issue by G4Zz0L1** [autobrr/autobrr#1375]
**Version**
latest, portainer says it's the 2.24.3

**Describe the bug**
I'm getting TypeError's when visiting pages (like releases or filters) and in the home page there's nothing, even if the release table has thousands of rows.
I don't have an adblocker or similar, that could block something in javascript and I don't know where to look for errors.
In the `docker compose logs` it's working fine, fetching releases from rss like always, it even sends them to radarr/sonarr, so everything else is fine.
The UI is somewhat broken though, and I don't know why.

**To Reproduce**
1. Go to releases tab, or filters tab (even the logs in the settings tab)
2. See error

**Expected behavior**
It should work

**Screenshots**
- home
![image](https://github.com/autobrr/autobrr/assets/13220636/74c66116-8d99-4eb6-a2ad-74cd185e1c24)
- releases
![image](https://github.com/autobrr/autobrr/assets/13220636/319d12e5-45ce-4656-903c-98d427a4a5e1)
- filters
![image](https://github.com/autobrr/autobrr/assets/13220636/1bb3a53b-cb51-418b-adf3-6b9acf530d50)
- logs
![image](https://github.com/autobrr/autobrr/assets/13220636/a876bc76-dc75-46a2-8a3b-82282155fd24)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome
 - Version 121.0.6167.85

**Additional context**
The only logs I can see are the following:
- releases
  - TypeError: n.map is not a function at XQ  screens/releases/Filters.tsx:86  {isSuccess && data?.map((indexer, idx) => (
- filters
  - TypeError: e.filter is not a function at UQ  screens/filters/List.tsx:168  const enabledItems = data?.filter(f => f.enabled);
- logs
  - TypeError: Cannot read properties of undefined (reading 'length') at lC  screens/Logs.tsx:197  {data && data.files.length > 0 ? (

**Comment by zze0s** [comment]
We've had some issues recently mostly affecting Chromium based browsers. Clear your cookies and it will work again. 

Sorry about the inconvenience!

**Comment by G4Zz0L1** [comment]
Yep, you're right, now it's working again.
Thanks a lot!
