### ISSUE TITLE
TypeError: e.filter is not a function

### ISSUE THREAD

**Issue by FunThomas76** [autobrr/autobrr#1377]
after updating to the latest version i get the following error:

We caught an unrecoverable error!
Please consider reporting this error to our [GitHub page](https://github.com/autobrr/autobrr) or to [our official Discord channel](https://discord.gg/WQ2eUycxyT).
TypeError: e.filter is not a function
at UQ  bigfoot/src/screens/filters/List.tsx:168  const enabledItems = data?.filter(f => f.enabled);
You can try resetting the page state using the button provided below or restarting your autobrr application. However, this is not guaranteed to fix the error.

it is running on a seedbox at seedhost.eu
all config seems to be missing and when moving to pages for filters, releases or logs i get the error and nothing more is possible

**Comment by s0up4200** [comment]
We've had some issues recently mostly affecting Chromium based browsers. Clear your cookies and it will work again.

**Comment by FunThomas76** [comment]
is firefox chromium based ?

**Comment by zze0s** [comment]
> is firefox chromium based ?

It's not, but it was mostly Chromium based browsers. Some reports of issues with Firefox as well but way way less.

**Comment by FunThomas76** [comment]
so since the support worked and all is lost a fresh install with new config works fine

**Comment by FunThomas76** [comment]
after the support team worked and all config and database is lost a fresh install with new config works now fine

**Comment by zze0s** [comment]
Reinstalling is not needed, this is purely a frontend issue. What provider was this? Tell them it's only a frontend issue and clearing cookies or using a other browser to test is the way.

**Comment by FunThomas76** [comment]
read the first post and you know the provider, i told them about the issue if other users had the same problems

**Comment by zze0s** [comment]
I somehow missed that. Hopefully they don't just reinstall and break users installs with something that is a cookies/browser issue :slightly_smiling_face:
