### ISSUE TITLE
Add support for Docker AArch64 / ARM64

### ISSUE THREAD

**Issue by xoaaC** [autobrr/autobrr#138]
Hi,

adding a feature request to make the autobrr docker container compatible with AArch64 / ARM64 systems.
Would love to see this option in the future! :)
Keep up the amazing work - been waiting for a autodl-irssi replacement for a long time!

Kind regards

**Comment by ludviglundgren** [comment]
Hello!

Thanks! :smile:  

Can probably make that happen! :slightly_smiling_face: Will check out more docker buildx stuff and see whats needed.
