### ISSUE TITLE
[INDEXER REQ] ToonsForMe

### ISSUE THREAD

**Issue by edge20200** [autobrr/autobrr#1386]
**We currently only support indexers with IRC announces.**

# Indexer request

-  Do they have irc announce? Yes 

### If no existing `autodl-irssi .tracker` file

- Indexer name: ToonsForMe
- Short name: TFM
- URL: https://toonsfor.me
- Download link examples with key such as `passkey, rss key, auth key, torrent pass` etc:
 https://toonsfor.me/torrents/download/1 (UNIT3D tracker)

## Announce examples

Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.

- Category [Movies] Type [WEBRip] Name [ReleaseNameRedactedHere] Freeleech [0%] Internal [No] Double Upload [No] Size [1.33 GB] Uploader [Anonymous] Url [https://toonsfor.me/torrents/download/1]

## IRC Network

- Network name: OnlyEncodes
- Network address: irc.onlyencodes.cc
- Port: 6697
- SSL/TLS: Yes
- NickServ registration required? Check wiki, guides etc: Yes (Wiki Guide on site)
- Is there a required format for the nick? Like `username|bot`? No
- Invite command: None

## Bonus

Check their categories in the announce an on site

Announce category - Site category name
Announce category - Movie = Moive
Announce category - TV Show = TV

Announce bot = RobinHood

Other notes, grouping is allowed on network now.

**Comment by s0up4200** [comment]
What is the channel name?
