### ISSUE TITLE
[WEBUI] Unable to click tooltips on certain setups

### ISSUE THREAD

**Issue by s0up4200** [autobrr/autobrr#1389]
**Version**
v1.36.0

**Describe the bug**
Tooltips are not working as expected with a mouse and sometimes a touchpad if the app registers the device as a touch device.
E.g., a laptop with a touch screen or an iPad with a Magic Keyboard attached.

On the iPad, it only triggers the tooltip when touch is used. If using the touchpad on the Magic Keyboard, nothing happens.

**To Reproduce**
1. Go to the dashboard with a touch screen device
2. Click the action tooltip using a mouse (or an attached touchpad on the iPad)

Console error: `Unable to preventDefault inside passive event listener invocation.`

**Expected behavior**
It should work.

**Device tested:**
 - OS: iPadOS
 - Browser: Safari
 - Version: 17.3

**Additional context**
The bug was probably introduced by #1314

**Comment by ekatiyar** [comment]
This also affects laptops with touchscreens, at least in my experience. Clicking with my mouse/touchpad does not work, but "clicking" on tooltips using the touchscreen does work.
