### ISSUE TITLE
ANT Announces not being picked up from IRC

### ISSUE THREAD

**Issue by jfl88** [autobrr/autobrr#1409]
**Version**
v1.37.0

**Describe the bug**
Connected to ANT IRC channel on the Settings > IRC page.  Can see the announces by "Sauron" bot as below:

> [2024-02-13 20:15:56] Sauron: [Feature Film] Like Cats & Dogs (2017) [H264 / MKV / WEB / 1080p / AC3 / Subs / EDGE2020 / Filename: Like.Cats.&.Dogs.2017.1080p.AMZN.WEB-DL.DDP.2.0.H.264-EDGE2020.mkv] [5.05 GiB - Uploader: Anonymous] https://anthelion.me/torrents.php?action=download&id=77062 - comedy,romance,subtitles

> [2024-02-13 21:05:42] Sauron: [Feature Film] The Bermuda Depths (1978) [H264 / MKV / Blu-ray / 1080p / FLAC / Subs / Remux / MIXMUX / Filename: The.Bermuda.Depths.1978.Warner.Archive.Collection.USA.Theatrical.Cut.1080p.BluRay.Remux.AVC.FLAC.1.0-MIXMUX.mkv] [15.36 GiB - Uploader: kjokkn] https://anthelion.me/torrents.php?action=download&id=77063 - adventure,fantasy,sci.fi,thriller,subtitles

However "Last Announce" remains "n/a".  Also no sign of ANT announces in the overall app logs.

**To Reproduce**
1. Create indexer for ANT and complete IRC information
2. Enable IRC
3. Observe announces occur in the viewable IRC chat box, but do not update the "Last Announce" metric for the IRC channel

**Expected behavior**
Announces should be detected and fed back to the rest of the indexer workflow.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Server running autobrr in Docker (Unraid)
 - Browser: Safari 
 - Version: 17.2.1

**Additional context**

I took the message from the IRC window and dropped it into [Regex](https://regex101.com) to test against the pattern in the ant.yaml definitions file, it appears all the correct groups are being matched - it pulls out 10 groups and the all align to the test, that is about as deep as I got - I am not super familiar with Go so not sure how to dig further.

**Comment by jfl88** [comment]
I know that ANT changed their IRC server address from .cc to .io - I made that change manually in the IRC settings.  I don't think that's related to this though, otherwise I wouldn't see messages at all?

**Comment by jfl88** [comment]
Relevant section of IRC settings page:
<img width="892" alt="image" src="https://github.com/autobrr/autobrr/assets/204281/5b9eeba9-fe27-4e86-808f-9b999c8f7c1a">

Relevant section of logs:
20:15:56 -
<img width="1228" alt="image" src="https://github.com/autobrr/autobrr/assets/204281/b96c69ab-c29c-41c4-aeca-c852635e6685">
21:05:42 -
<img width="1243" alt="image" src="https://github.com/autobrr/autobrr/assets/204281/12503365-8611-4cea-8826-24755ebb4d1a">

**Comment by zze0s** [comment]
Hi! The definition needs to have the correct info for the filtering etc to work properly, only editing the network addr is not enough. We have already merged the changes and was supposed to make a release yesterday but we had to do some testing of other things so we did not make it.

Will make a release today :)

**Comment by zze0s** [comment]
v1.38.0 is out with the updated urls. https://github.com/autobrr/autobrr/releases/tag/v1.38.0

**Comment by jfl88** [comment]
That fixed it, thanks for the quick update!
