### ISSUE TITLE
[FEATURE REQ] Incognito mode on Release page should change second line

### ISSUE THREAD

**Issue by eanzie** [autobrr/autobrr#1413]
**Version**
1.38.1

**Describe the bug**
When on the Release page and click the eye icon on bottom right of the page it shows the "Incognito mode".  The release names change to linux isos but the second line Category, Size, and Misc do not change.

**To Reproduce**
When on the Release page and click the eye icon on bottom right of the page 

**Expected behavior**
Either hide the line or change to linux iso type information.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11, FF 122.0.1 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by zze0s** [comment]
Hey! Not strictly a bug, it wasn't really considered when it was added. Will add it to the todo.
