### ISSUE TITLE
Refuses to monitor the channel #metal (RMT)

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#1414]
Latest

Windows 11 Pro
Yandex Browser
1.38.1

1. DigitalCore - when I try to download a torrent file from any pushes tab in the browser, I get a message: The user doesn't exist.
2. Romanian Metal Torrents - there is a connection to the iPLAY network (I see this in the logs), but there is no monitoring of the #metal channel.

I will be grateful for any help.

**Comment by zze0s** [comment]
> 1. DigitalCore - when I try to download a torrent file from any pushes tab in the browser, I get a message: The user doesn't exist.

Is this only for the download link and not the info link? Are download with autobrr working so you have the correct passkey setup?
 
> 2. Romanian Metal Torrents - there is a connection to the iPLAY network (I see this in the logs), but there is no monitoring of the #metal channel.
> 
Do they have any invite commands etc? According to the indexer definition we have you only have to have a NickServ registered nick to join the channel.

**Comment by bulletproof2k** [comment]
> > 1. DigitalCore - when I try to download a torrent file from any pushes tab in the browser, I get a message: The user doesn't exist.
> 
> Is this only for the download link and not the info link? Are download with autobrr working so you have the correct passkey setup?
> 
> > 2. Romanian Metal Torrents - there is a connection to the iPLAY network (I see this in the logs), but there is no monitoring of the #metal channel.
> 
> Do they have any invite commands etc? According to the indexer definition we have you only have to have a NickServ registered nick to join the channel.

All the rules regarding nicknames are followed. At the expense of the DigitalCore, the connection is OK, but I can't download torrent file from one of the tabs with releases, a page with the address opens: https://digitalcore.club/api/v1/torrents/download/***/*****

As for RMT, all commands are standard /msg Nickserv identify YourPASSWORD 🤷

**Comment by bulletproof2k** [comment]
> I can't replicate the DigitalCore issue, copying a download link and visiting in an Incognito window does work as intended. Is it happening for all torrents or only some? If only some then those have likely been deleted.
> 
> As for iPlay I just tested connecting with a regular client and it works with the default settings and I saw you join and part. Will wait and see if there's any announces. If you are connected with the nick already maybe try group the nick.

As for the DigitalCore, this happens with all torrents when I try to download in the browser, I get a message: "The user doesn't exist." But if I go to the page of this release on the tracker, then the torrent is available and it can be downloaded.

As for RMT, I connect through a regular client without any problems, but if I try to connect through brr, the network turns red.
Their network does not support TLS.

**Comment by bulletproof2k** [comment]
> By default in autobrr iPlay have TLS disabled and using port 6668. Make sure you have the same and try again.
> 
> Have you had any successful downloads from DC to a download client? Make sure you are using your `passkey` in indexers settings and not your irc key etc. Easy to mix them up.
> 
> Also if you change passkey, old release links will not be updated, only new release links.

You were right about DC, I got the keys mixed up. 😊
But as for the RMT, I tried restarting and changing the mechanism, but it doesn't change anything. ☹️

![2024-02-20_19-10-28](https://github.com/autobrr/autobrr/assets/1818579/b50c6637-fd07-46e9-9663-f8dd6ba27805)
![2024-02-20_19-09-04](https://github.com/autobrr/autobrr/assets/1818579/56b9749c-af95-44d7-80cb-a1f2bef819b7)

**Comment by zze0s** [comment]
Great! 

Can you try set IRC Auth Mechanism to NickServ instead of SASL, and set account to your main nick `BLPF2k`, or try the same as in nick `BLPF2k|AUTODL`.

**Comment by bulletproof2k** [comment]
@zze0s I didn't quite understand, should I use the main nickname `BLPF2k` instead of the nickname of the bot `BLPF2k|AUTODL`?

**Comment by zze0s** [comment]
Try set nickname and account to `BLPF2k|AUTODL` with Mechanism to `NickServ`. 

If that still fails then the set nick to `BLPF2k|AUTODL` and account to `BLPF2k`, but that only works if the bot nick `BLPF2k|AUTODL` is **grouped with the main** `BLPF2k`.

**Comment by bulletproof2k** [comment]
In the first case, it does not work.
![2024-02-20_19-43-41](https://github.com/autobrr/autobrr/assets/1818579/56d8b032-ca08-4e53-b64a-f554cafb1c6e)
In the second case, there is a connection to the network but no connection to the #metal channel.

**Comment by zze0s** [comment]
Disable the network in autobrr, then try this in Hexchat or some other client. Try login with your bot user and do nickserv identify and verify it works before putting the info in autobrr.

**Comment by zze0s** [comment]
That is exactly what happens behind the scenes if you have Mechanism NickServ, and account + password set, like this:

![image](https://github.com/autobrr/autobrr/assets/43699394/a58bb5b7-8a89-4009-988f-e56aa00b12a8)

**Comment by bulletproof2k** [comment]
> That is exactly what happens behind the scenes if you have Mechanism NickServ, and account + password set, like this:
> 
Yep, this is the first case.

**Comment by bulletproof2k** [comment]
@zze0s please check if the channel is working correctly `#metal` before the next update is released. If you have any problems with your account on this tracker, you can write to me at the email address listed in my profile, and we will resolve this issue. 🤷🏻‍♂️

p.s. this update solved the previous problem, thanks. 😊
