### ISSUE TITLE
[INDEXER REQ] omgwtfnzbs

### ISSUE THREAD

**Issue by Xenodini** [autobrr/autobrr#1417]
# Indexer request

-  Do they have irc announce? Yes

### If no existing `autodl-irssi .tracker` file

- Indexer name: omgwtfnzbs
- Short name: omgwtfnzbs
- URL: https://omgwtfnzbs.org
- Download link example: `https://api.omgwtfnzbs.org/nzb/?user=USERNAME&api=APIKEY&id=NZBID`
- Protocol: nzb
- Privacy: private
- Language: en-us

## Announce examples

Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.

- `[category] [ filename ] [ size ] [ NZBID ]`
- `[TV: HD] [ Asphalt-Cowboys.S13E08.GERMAN.DOKU.720p.WEB.H264-MGE ] [ 597.95 MB ] [ NGV8KW ]`
- `[TV: HD] [ Asphalt-Cowboys.S13E08.GERMAN.DOKU.1080p.WEB.H264-MGE ] [ 2.55 GB ] [ zaDwCu ]`
- `[MUSIC: MP3] [ iNCODE_-_Correlation-(MDL255)-SINGLE-WEB-2024-ZzZz ] [ 10.04 MB ] [ Dance ] [ btwk5I ]`
- `[TV: HD] [ Evil.-.Stimmen.des.Boesen.S01E06.GERMAN.DL.DOKU.1080p.WEB.H264-MGE ] [ 1.63 GB ] [ EDfXxg ]`
- `[MOVIES: FULL BR] [ Migration.2023.COMPLETE.BLURAY-RiSEHD ] [ 39.35 GB ] [ qXOLq4 ]`
- `[MUSIC: MP3] [ Chris_Mundie_-_Be_Ok-(REG2006)-SINGLE-WEB-2024-ZzZz ] [ 14.66 MB ] [ Dance ] [ Sr79iS ]`
- `[MOVIES: HD] [ Next.Goal.Wins.2023.BluRay.720p.DTS.x264-MTeam.heb ] [ 5.82 GB ] [ 5Apxaq ]`
- `[MUSIC: MP3] [ Giorgiamariasara_-_Corro-SINGLE-WEB-IT-2024-UOVA ] [ 11.85 MB ] [ Pop ] [ hUYlTE ]`
- `[XXX: SD-CLIPS] [ OnlyFans.2024.Sybil.and.Lumi.Ray.Pimp.Of.The.Year.XXX.MP4-P0RNL0V3RSD ] [ 210.41 MB ] [ JoHZLc ]`

## IRC Network

- Network name: synIRC
- Network address: irc.synirc.net
- Port: 6697
- SSL/TLS: Yes
- Channel: #omgwtfnzbs
- Announcer: omgwtfnzb
- NickServ registration required?: Yes
- Is there a required format for the nick?: No
- Invite command: `/msg omgwtfnzb !invite NICKNAME IRCKEY #omgwtfnzbs`

**Comment by zze0s** [comment]
You broke their rules of naming them in public. IRC and usenet is not ideal. Use the generic newznab indexer.
