### ISSUE TITLE
[INDEXER REQ] omgwtfnzbs

### ISSUE THREAD

**Issue by Xenodini** [autobrr/autobrr#1418]
# Indexer request

-  Do they have irc announce?: Yes

### If no existing `autodl-irssi .tracker` file

- Indexer name: omgwtfnzbs
- Short name: omgwtfnzbs
- URL: https://omgwtfnzbs.org/
- Download link example: `https://api.omgwtfnzbs.org/nzb/?user=USERNAME&api=APIKEY&id=NZBID`
- privacy: private
- protocol: nzb

## Announce examples

Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.

- `[TV: HD] [ ReleaseNameCensored ] [ 10.26 GB ] [ NZBID ]`
- `[MOVIES: HD] [ ReleaseNameCensored ] [ 6.05 GB ] [ NZBID ]`

## IRC Network

- Network name: synIRC
- Network address: irc.synirc.net
- Port: 6697
- SSL/TLS: Yes
- Channel: #omgwtfnzbs
- Announcer: omgwtfnzb
- NickServ registration required?: Yes
- Is there a required format for the nick?: No
- Invite command: `/msg omgwtfnzb !invite NICKNAME IRCKEY #omgwtfnzbs`

**Comment by zze0s** [comment]
This is against their rules. Please don't open more prs about this here in autobrr. Come talk to us on Discord instead.

**Comment by bulletproof2k** [comment]
[Xenodini](https://github.com/Xenodini) Hi, are there any applications on this tracker in order to receive an invitation?
Sorry for the question.

**Comment by zze0s** [comment]
@bulletproof2k not the place to ask.

**Comment by zze0s** [comment]
@Xenodini I'll close this in the next 10 minutes so you get a chance to read this. We won't add it because it's against their rules. Use Generic Newznab for their feed instead. IRC and usenet is not ideal.
