### ISSUE TITLE
Telegram Notifications

### ISSUE THREAD

**Issue by thomasza92** [autobrr/autobrr#1431]
**Version**
autobrr 1.38.1

**Describe the bug**
Can't get Telegram notifications to work. 
Logs report: `telegram client request error: {"ok":false,"error_code":404,"description":"Not Found"}`
Docs are unhelpful.

**To Reproduce**
1. Go to Settings
2. Go to Notifcations
3. Add a name, select Telegram as type, select all events.
4. Under settings, input the settings that are required. (but docs do not make clear how these should be formatted or what the settings correspond to)
5. Press 'Test' button and check logs.

**Expected behavior**
Telegram notifications to work properly.

**Desktop (please complete the following information):**
Ubuntu 20.04
Firefox

**Additional context**
The docs on how to add [Telegram notifications](https://autobrr.com/configuration/notifications) are not helpful.

For example, when you request an API key for a bot on telegram, BotFather gives you a result that is formatted like this: 
`<BOT_ID>:<API_KEY>`

..but it seems like autobrr expects to receive _*only*_ the `API_KEY` portion, not the `BOT_ID`, as before when I included both of these I was given an 'unauthorized' error in logs.

There are many other questions that are left unanswered in the docs as well. Do I need to have topics in my group? What about the fact that 'General' topic does not count as topic when sending API requests? Does it actually utilize a group, or a private chat, or channel? All of these API requests are sent slightly differently and how they are sent in autobrr remains unclear.

[Here](https://gist.github.com/nafiesl/4ad622f344cd1dc3bb1ecbe468ff9f8a) is a gist explaining how to get a Telegram Bot's Chat ID for various setups. It also shows the differences between API requests depending on private chat, channel, group chat, and group chat topics.

If someone can explain what autobrr expects to receive in each of these form fields please let me know. I have tried many different variations and remain unsuccessful.

**Comment by bulletproof2k** [comment]
Most likely you have mixed up the places bot_token and your chat_id

**Comment by addy** [comment]
The latest version of the client is successfully sending my Telegram notifications for reference.

**Comment by zze0s** [comment]
Closing this as there's been no response from the OP and other users confirming it does still work so likely a configuration issue.
