### ISSUE TITLE
Caddy - baseUrl config issues

### ISSUE THREAD

**Issue by GabrielOsvair** [autobrr/autobrr#1432]
**Version**
1.38.1

**Describe the bug**
When baseUrl is activated in the configuration file (baseUrl = "/autobrr"), the page opens as if it were the first time, and asks to create an account, but I have already done this process and I see the filters and feeds updating normally in CMD... If I use baseUrl baseUrl = "/autobrr/" the page is completely blank.

**Expected behavior**
I would like to use it like Radarr, for example, to configure Caddy and use everything on the same domain.

**Screenshots**
I believe the text description is self-explanatory.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

**Smartphone (please complete the following information):**
 - OS: Android 13
 - Browser: Chrome
 - Version: latest

**Comment by zze0s** [comment]
Hi! You must have the ending slash like `/autobrr/` as baseurl and then a `uri strip_prefix /autobrr` as in the caddy config as documented here https://autobrr.com/installation/reverse-proxy/caddy

**Comment by GabrielOsvair** [comment]
Hello, the problem is not with Caddy, I already use it throughout the arr's ecosystem. As I said, the page is completely blank, accessed on the local network or via the domain when the baseUrl is configured. When I disable baseUrl, it normalizes the process. The same does not occur when using subdomains... which leads me to believe that the problem is with the BaseUrl config

With the baseUrl configured:
![image](https://github.com/autobrr/autobrr/assets/67530921/025f5498-0f58-4ec5-8b85-6520e6b60e2b)

What appears in CMD and the web interface:
![image](https://github.com/autobrr/autobrr/assets/67530921/790496c7-6f9f-45fa-a822-840718d2dc9e)

The impression is that the problem is with the baseUrl, since it appears to be running, but the interface is not accessible.

If I configure the baseUrl as "/autobrr", the data is reset, as if I hadn't configured anything.
![image](https://github.com/autobrr/autobrr/assets/67530921/91eed71f-b287-44e5-967b-8c4e259dbeda)

If I deactivate the baseUrl, everything works as it should... This is all on the local network, the problem is not in configuring the Caddy.
![image](https://github.com/autobrr/autobrr/assets/67530921/1a401f3d-ba6a-403d-be18-ac0f841837f0)

**Comment by GabrielOsvair** [comment]
Someone who also came across the blank interface: #1166

**Comment by zze0s** [comment]
Can you share your caddy conf? You must have the uri strip prefix when using baseurl. Same with nginx and traefik when using baseurl. Subdomains are not affected since they load from the root.
