### ISSUE TITLE
A mismatched version of the database schema during upgrade process

### ISSUE THREAD

**Issue by vBm** [autobrr/autobrr#1440]
**Version**
Version `1.39.0`
Database `sqlite`

**Describe the bug**
A mismatched version of the database schema upgrade process.

**To Reproduce**
Have an older database and upgrade to the latest version.

**Expected behavior**
Correct version number.

**Screenshots**
Not a screenshot per see but a log:
```
{"level":"info","module":"database","type":"sqlite","time":"2024-02-27T20:52:34-07:00","message":"Beginning database schema upgrade from version 54 to version: 55"}
{"level":"info","module":"database","type":"sqlite","time":"2024-02-27T20:52:34-07:00","message":"Upgrading Database schema to version: 54"}
{"level":"info","module":"database","type":"sqlite","time":"2024-02-27T20:52:34-07:00","message":"Database schema upgraded to version: 55"}
```

**Additional context**
The middle line should be:
```
{"level":"info","module":"database","type":"sqlite","time":"2024-02-27T20:52:34-07:00","message":"Upgrading Database schema to version: 55"}
```

The code in question (to my untrained eye) appears to be on the [line 127 of sqlite.go](https://github.com/autobrr/autobrr/blob/develop/internal/database/sqlite.go#L127)

**Comment by martylukyy** [comment]
Thanks for reporting!

This bug will be fixed in future versions of autobrr upon #1441 being merged. 🙂
