### ISSUE TITLE
Working IRC indexer fails with `tls: handshake failure` after v1.39.0 upgrade

### ISSUE THREAD

**Issue by rpatterson** [autobrr/autobrr#1443]
**Version**

- Version: v1.39.0
- Build date: 2024-02-27T12:05:59.806Z
- Application: /usr/local/bin/autobrr
- Config path: /config
- Database: sqlite

**Describe the bug**

After upgrading, an IRC indexer that was working previously now fails to connect with `ERR: client encountered connection error error="remote error: tls: handshake failure"= module=irc network=irc.p2p-network.net`.

**To Reproduce**
1. Start an autobrr container using the `ghcr.io/autobrr/autobrr:v1.38.1` tag
2. Add an Indexer for `Milkie` with working settings
3. Note that the IRC connection is working/green
4. Restart the autobrr container using the `ghcr.io/autobrr/autobrr:latest` tag
5. Note that the IRC connection is broken/yellow and that the logs report `tls: handshake failure`

**Expected behavior**

Working IRC connections for supported indexers should continue working after an upgrade.

**Additional context**

Here's `$ irssi` completing the TLS handshake and reporting that the TLS certificate is fine:

```
06:15 -!- Irssi: Looking up irc.p2p-network.net
06:15 -!- Irssi: Connecting to irc.p2p-network.net [139.162.154.78] port 6697
06:15 -!- Irssi: Certificate Chain:
06:15 -!- Irssi:   Subject: CN: *.p2p-network.net
06:15 -!- Irssi:   Issuer:  C: US, O: Let's Encrypt, CN: R3
06:15 -!- Irssi:   Subject: C: US, O: Let's Encrypt, CN: R3
06:15 -!- Irssi:   Issuer:  C: US, O: Internet Security Research Group, CN: ISRG Root X1
06:15 -!- Irssi: Protocol: TLSv1.2 (256 bit, AES256-GCM-SHA384)
06:15 -!- Irssi: EDH Key: N/A
06:15 -!- Irssi: Public Key: 4096 bit RSA, valid from Feb 13 05:27:30 2024 GMT to May 13 05:27:29 2024 GMT
06:15 -!- Irssi: Public Key Fingerprint:  D0:04:FD:2A:D2:4F:39:6B:48:EB:2A:79:A0:94:A3:14:5D:9D:52:40:1A:9E:E3:62:A5:A3:B8:82:A8:03:06:01 (SHA256)
06:15 -!- Irssi: Certificate Fingerprint: 90:B5:35:DB:11:35:BA:B4:86:6F:A6:7B:DB:DD:B5:BE:6E:FB:2B:BE:B7:1A:AE:EA:7F:3F:E6:3F:56:36:08:55 (SHA256)
06:15 -!- Irssi: Connection to irc.p2p-network.net established
```

**Comment by rpatterson** [comment]
Doh! Encountering this issue is how I discovered that my backup process wasn't including my autobrr DB. My most recent backup is from a while ago and I've added a bunch of indexers and other configuration since then. I can't rollback to `v1.38.1` using the current DB because because there were some DB migrations with `v1.39.0`. Ouch! Totally my fault but if anyone has any tips for how to rollback the DB, you'd be an angel who saved me a buch of data re-entry.

**Comment by bulletproof2k** [comment]
I have the same problem, but I haven't done any manipulations with my database. Everything worked after the update, but after the restart, the `p2p-network` stopped working.

![2024-02-28_13-11-03](https://github.com/autobrr/autobrr/assets/1818579/d57364d6-d420-4dd7-a61a-35d0b407f81b)

**Comment by zze0s** [comment]
This was reported on Discord earlier today as well. I have it working with the latest tag v1.39.0 running in docker, but others are reporting the same issue.

We upgraded Go from 1.20 up to 1.22 and they made internal changes that deprecated old TLS ciphers, like the one above `TLSv1.2 (256 bit, AES256-GCM-SHA384)`.

With P2P-network they have multiple servers so maybe some have it updated and others not, and I'm connected to one that works. I'm not entirely sure yet.

* Downgrading without backups is not an option because we made database schema changes
* Reverting or downgrading Go version is not ideal either because the newer version brings a lot of benefits

**Comment by rpatterson** [comment]
> I have the same problem, but I haven't done any manipulations with my database.

Sorry, the DB stuff I mentioned is just my personal woe and not related to this issue.

> Everything worked after the update, but after the restart, the `p2p-network` stopped working.

Yeah, to confirm the issue is related to the `v1.39.0` release, I downgraded to `v1.38.1` re-added the `Milkie` indexer and confirmed the IRC connection still works for that previous version.

**Comment by rpatterson** [comment]
> With P2P-network they have multiple servers so maybe some have it updated and others not, and I'm connected to one that works. I'm not entirely sure yet.

For context, this issue has persisted for me across several restarts of the VPN my autobrr container is using, so I've had the issue when connecting from several different IPs. What general geographical region are you connecting successfully to P2P-network from, @zze0s? I'd be happy to change to the closest VPN server to you and test to see if that makes a difference.

> * Downgrading without backups is not an option because we made database schema changes

Sigh, I figured. Thanks for confirming though.

> * Reverting or downgrading Go version is not ideal either because the newer version brings a lot of benefits

Definitely not!

**Comment by zze0s** [comment]
The server I tested with is at Hetzner in Germany.

**Comment by zze0s** [comment]
@rpatterson can you try tag `pr-1444` in a couple of minutes once it's built and see if that works?

It's a speculative fix.

**Comment by rpatterson** [comment]
> The server I tested with is at Hetzner in Germany.

I can reproduce the issue connected to VPN servers in both Frankfurt and Berlin.

**Comment by rpatterson** [comment]
> @rpatterson can you try tag `pr-1444` in a couple of minutes once it's built and see if that works?

That tag works, including back on my previous VPN server.
