### ISSUE TITLE
[INDEXER REQ] SATClubbing

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#1455]
Indexer request

-  Do they have irc announce? Yes
- Indexer name: SATClubbing
- Short name: SCMT
- URL: https://satclubbing.club/

IRC Network

- Network name: P2P-NET
- Network address: [irc.p2p-network.org](http://irc.p2p-network.org/)
- Port: 6697 is common for TLS
- SSL/TLS: Yes

https://satclubbing.club/irc.php

**Comment by zze0s** [comment]
Hey @bulletproof2k, could you please gather the announce examples and categories for us? Will make it much easier 🙂

**Comment by luckylittle** [comment]
There are no announces @bulletproof2k
