### ISSUE TITLE
[[error: NotEmptyValidator] DownloadUrl: 'Download Url' must not be empty. - got value: ]

### ISSUE THREAD

**Issue by davidbaguetta1** [autobrr/autobrr#1457]
**Version**
v1.39.1

**Describe the bug**
I setup a Torznab RSS feed from Prowlarr for Nyaa on my autobrr, which i am using to monitor new releases and send them to Sonarr and Radarr. I setup this feed to use Magnet links.

Whenever autobrr tries to push a nyaa release, the push gets rejected with a message saying `[[error: NotEmptyValidator] DownloadUrl: 'Download Url' must not be empty. - got value: ]`. I checked Sonarr and it is indeed returning a 400 status code for these releases. 
This issue only happens when using Magnet links. If I set up the RSS feed with Torrent links, it works well.

**To Reproduce**
1. Add Nyaa indexer to Prowlarr
2. Add Generic Torznab indexer to autobrr, pointing to the Nyaa indexer in Prowlarr (**make sure the Download Type is set to Magnet**)
3. Create filter for Nyaa indexer with an Action to send to a Sonarr and/or a Radarr instance
4. Wait for a new release to be added to Nyaa
5. Confirm that the release always gets rejected by Sonarr and/or Radarr with the above error message

**Expected behavior**
The release should be submitted to Sonarr and Radarr, and possibly rejected, but not with the above error.

**Screenshots**
![Screenshot 2024-03-12 at 10 54 41 AM](https://github.com/autobrr/autobrr/assets/153558354/a857e36b-11d2-4df4-a880-ae0d5e9c31d7)
![Screenshot 2024-03-12 at 10 55 13 AM](https://github.com/autobrr/autobrr/assets/153558354/106e7685-7e5d-493f-8940-ffa59cb10018)

**Additional context**
Sonarr Trace Logs: https://pastebin.com/cnVYgLDB
Prowlarr Trace Logs: https://pastebin.com/LKVdTntE

I went through autobrr's source code and noticed that when i am using torrents, it sends the link under the field `downloadUrl` and when i use magnets it sends the link under `magnetUrl` ([torznab.go](https://github.com/autobrr/autobrr/blob/develop/internal/feed/torznab.go#L129-L132) and [sonarr.go]( https://github.com/autobrr/autobrr/blob/develop/internal/action/sonarr.go#L58-L59)). I feel like Sonarr/Radarr always expect a `downloadUrl` and that's why the error is thrown.

**Comment by davidbaguetta1** [comment]
Issue has been fixed in both [Sonarr](https://github.com/Sonarr/Sonarr/pull/6626) and [Radarr](https://github.com/Radarr/Radarr/pull/9840)

**Comment by zze0s** [comment]
Awesome! Did not know that was an issue until you reported it. Thanks to markus for quickly fixing it on their end!
