### ISSUE TITLE
Locked out of authentication after changing Password to blank

### ISSUE THREAD

**Issue by FortuneTTS** [autobrr/autobrr#1466]
**Version**
 v1.39.1
 docker compose

**Describe the bug**
I changed my password to blank with the GUI thinking it would disable authentication but when i try to log in it tells me a password is required. 
I have used autobrrctl --config /home/username/.config/autobrr change-password <USERNAME> 
which gives:
{"level":"info","module":"database","type":"sqlite","time":"2024-03-20T09:48:47Z","message":"Beginning database schema upgrade from version 0 to version: 55"}
{"level":"info","module":"database","type":"sqlite","time":"2024-03-20T09:48:47Z","message":"Database schema upgraded to version: 55"}
and prompts me for a password, however the new password does not work and i get "Wrong password or username!"

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser Firefox

**Comment by zze0s** [comment]
That is rather impressive. You can't disable auth, but the tool should not let you put in an empty password either. Think this is the first time in autobrr's lifetime we get such a report :)

You can reset it if you use a SQLite browser to open the db and remove the user from the users table then you can create a new one.

**Comment by FortuneTTS** [comment]
> That is rather impressive. You can't disable auth, but the tool should not let you put in an empty password either. Think this is the first time in autobrr's lifetime we get such a report :)
> 
> You can reset it if you use a SQLite browser to open the db and remove the user from the users table then you can create a new one.

SQLite browser worked, i copied the user entry from an old backup I had, by the way the reason i want to disable authentication is that i have setup a Authentik for SSO so i wanted to avoid having to re authenticate

**Comment by zze0s** [comment]
Great!

There's two open issues about Auth Proxies with some good info in them already: https://github.com/autobrr/autobrr/issues?q=is%3Aopen+is%3Aissue+label%3Aauth
