### ISSUE TITLE
missing variables

### ISSUE THREAD

**Issue by KyleSanderson** [autobrr/autobrr#147]
$(year)-$(month)-$(day)
$(TorrentName)
$(TrackerShort) 

etc

Specifically I was using this on labels, commands, and rt-dir historically.

**Comment by ludviglundgren** [comment]
Merged PR #157 which introduces the following new variables:

New variables:
* Indexer `{{.Indexer}}`
* TorrentHash `{{.TorrentHash}}`
* Resolution `{{.Resolution}}`
* Source `{{.Source}}`
* HDR `{{.HDR}}`
* Season `{{.Season}}`
* Episode `{{.Episode}}`
* Year `{{.Year}}`
* Month `{{.Month}}`
* Day `{{.Day}}`
* Hour `{{.Hour}}`
* Minute `{{.Minute}}`
* Second `{{.Second}}`

And usable in the action fields for:
* Watch folder
* Label
* Tags
* Category
* Save Path

--

For TrackerShort you can use `Indexer` now, but it will be a mix of full and short names. Will improve in the future.
