### ISSUE TITLE
PTP Freeleech filter does not work

### ISSUE THREAD

**Issue by plmi** [autobrr/autobrr#1477]
**Version**
1.39.1

**Describe the bug**
No freeleech torrents get downloaded.

**To Reproduce**
1. Goto "Filters" and create a new filter
2. Set a filter name, indexer "PassThePopcorn" and Advanced > Freeleech > Activate Freeleech toggle
3. Define a download action
4. Save and activate the filter
5. No freeleech torrents get filtered or downloaded

**Expected behavior**
I would expect that freeleech torrents get filtered and downloaded.

**Screenshots**
See the screenshots. Torrent is freeleech but was not filtered.
![2024 03 25-00:26:26](https://github.com/autobrr/autobrr/assets/65455617/c290b889-692b-407e-8031-49d675de31b8)
![2024 03 25-00:27:22](https://github.com/autobrr/autobrr/assets/65455617/1986a91d-8381-487e-a4e9-51db46583024)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12
 - Browser: Chromium
 - Version: 122

**Comment by zze0s** [comment]
Hey! On PTP they add freeleech manually after the announce except for certain events like the Halloween upload contest. So unfortunately you'll not get many snatches from having the freeleech toggle enabled.

**Comment by plmi** [comment]
You you say that there not announced as freelech and I can't filter them in any way?

**Comment by zze0s** [comment]
Correct. You can use a Rss/torznab feed to filter for them, or manually go over them once a day and add to your client. You'll not be in the initial swarm but at least you'll get in for bonus points.

**Comment by plmi** [comment]
Ok thank you very much for this tipps! This issue can be closed then.
