### ISSUE TITLE
Bifurcation of the FNP indexer.

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#1480]
No matter which one of the two you choose, the network stops working after a few minutes.
![2024-03-25_13-38-47](https://github.com/autobrr/autobrr/assets/1818579/0a6a6bd9-2ce1-44ed-a5d5-9096825e3a2c)

**Comment by zze0s** [comment]
Hey! Can you give some more context here?

* Is that the indexers list in a filter or something else?
* Are you using a custom definition and the built in?
* **the network stops working after a few minutes**, is that the IRC network? What does the logs say? Set log level to TRACE to see everything

**Comment by bulletproof2k** [comment]
> Hey! Can you give some more context here?
> 
> * Is that the indexers list in a filter or something else?
> * Are you using a custom definition and the built in?
> * **the network stops working after a few minutes**, is that the IRC network? What does the logs say? Set log level to TRACE to see everything

For what period should the TRACE be set?
It shows in every filter.

**Comment by zze0s** [comment]
If it shows every filter then a minute or less should be fine. I just need more context and explanation to know what this is about.

**Comment by bulletproof2k** [comment]
@zze0s, @fabricionaweb Sorry guys, this is my inattention. Before that, it was added as Generic RSS after that, he was added a second as an IRС and naturally gave an error.
