### ISSUE TITLE
[BUG] Export JSON does not work in Safari

### ISSUE THREAD

**Issue by flavorgold1** [autobrr/autobrr#1487]
**Version**
1.40.1

**Describe the bug**
The `Export JSON` function is not working in Safari.
It says:
```
Error
Failed to copy JSON to clipboard.
```

**To Reproduce**
1. Go to `...` next to a filter.
2. Click on `...`.
3. Scroll down and click on `Export JSON`.

**Expected behavior**
The JSON info gets copied to the clipboard.

**Desktop (please complete the following information):**
macOS Sonoma Safari

**Additional context**
Also, is there no way to export actions and other things to JSON?

**Comment by zze0s** [comment]
Hi! This is a browser limitation which makes write to clipboard only available on `https` domains. Is this the case for you where you have autobrr on `http` something?

I verified and tested on Safari and have it working on `https` domains for autobrr.

[MDN reference](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard)

**Comment by flavorgold1** [comment]
I'm using caddy/https to access autobrr.

Even in Safari's Private Mode, I can't get it to copy. Same error.

**Comment by zze0s** [comment]
That's interesting :thinking:

Could you try another browser and see if that works? If it does then it's 100% Safari, but if it doesn't work then it's something else.

**Comment by flavorgold1** [comment]
It works just fine in Chrome and Firefox, on macOS Sonoma.

**Comment by zze0s** [comment]
> It works just fine in Chrome and Firefox, on macOS Sonoma.

Perfect, thanks for testing! That rules out issues with your caddy setup to start with.

I do not have a system with macOS Sonoma, but maybe you can share your exact Safari version which I might be able to test with?

Can you check if you have any Plugins/Extensions, Security/Privacy Profiles, Permissions or similar in Safari that could prohibit the use of the clipboard? Does it work with other websites?

**Comment by frantathefranta** [comment]
Happens to me too, using autobrr in kubernetes, accessed through Traefik. 
macOS Sonoma 14.4.1
Safari 17.4.1 (19618.1.15.11.14)
Add-ons: 
- AdGuardHome - disabled
- Vimium
- Tampermonkey (no scripts set for domain)
- Kagi search

**Comment by zze0s** [comment]
@flavorgold1 @frantathefranta can you both go into autobrr settings -> API Keys and make a new one and try copy that? Does that work for you on safari?

**Comment by flavorgold1** [comment]
> @flavorgold1 @frantathefranta can you both go into autobrr settings -> API Keys and make a new one and try copy that? Does that work for you on safari?

Yes! That works! In regular mode and private mode.
In regular mode, I have AdGuard running.
