### ISSUE TITLE
Missing options for variables

### ISSUE THREAD

**Issue by x134h34kr** [autobrr/autobrr#149]
I see that some tracker definitions have some variables that are impossible to define in the index filter.

Take hdb as an example:

```
      - torrentName
        - category
        - releaseTags
        - internal
        - uploader
        - torrentSize
        - baseUrl
        - torrentId
```

Internal is a variable, but there's no option to select it in the filter.

Is it possible to add that option please? Or a custom field that would allow us to specify a custom variable and the expected result?

Cheers

**Comment by ludviglundgren** [comment]
Hello! You are correct, this is not possible to set currently.

But it's something that should be there so will make it a prio over coming weeks. This should probably be behind a field like `origin` that can take `internal`, `scene`, `p2p` etc.
