### ISSUE TITLE
Add Perfect FLAC definition as used by RED

### ISSUE THREAD

**Issue by frantathefranta** [autobrr/autobrr#1494]
**Is your feature request related to a problem? Please describe.**
When using a Music oriented filter, the helpful "Perfect FLAC" override is different in definition than what the Redacted tracker uses. Redacted states that "(100% log for CD, or any Vinyl/DVD/Soundboard/WEB/Cassette/Blu-ray/SACD/DAT)" counts for a Perfect FLAC. I realize that autobrr uses the Orpheus definition, which I respect. 

**Describe the solution you'd like**
I'd like to have an option to select the Redacted definition.

**Describe alternatives you've considered**
If it's not possible to do this, I'd like to know how to set up a filter that covers the Redacted definition of Perfect FLAC, as when I try to select it manually in the simple toggles, I can't get it to snatch both WEB FLACs and CD FLACs with 100% log.

**Comment by zze0s** [comment]
Hi! I think we use the varroa definition of Perfect FLAC which is CD, FLAC, Lossless/24bit lossless, Cue file, Log file, Log Score 100%.

You should be able to setup a filter for that:

```JSON
{
    "name": "Music",
    "version": "1.0",
    "data": {
        "formats": [
            "FLAC"
        ],
        "quality": [
            "Lossless",
            "24bit Lossless"
        ],
        "media": [
            "CD",
            "WEB",
            "Vinyl",
            "Soundboard",
            "DAT",
            "Cassette",
            "Blu-Ray",
            "SACD"
        ],
        "cue": true,
        "log": true,
        "log_score": 100
    }
}
```

We can look into if the predefined Perfect FLAC setting should be changed, but I am a bit hesitant as there are a lot of users relying on it that might start to get unwanted releases after a change like that.

**Comment by frantathefranta** [comment]
Yeah I definitely don't want to break it for anyone. I feel like I've tried this and it didn't grab Lossless WEB files, but I'll try again.

**Comment by zze0s** [comment]
Please do and set your log level in settings to either Debug or Trace for like a day and see what it does.
