### ISSUE TITLE
[FEATURE REQ] Radarr action to have a toggle to add a new movie into Radarr

### ISSUE THREAD

**Issue by gmcouto** [autobrr/autobrr#1497]
**Is your feature request related to a problem? Please describe.**
I have a private torrent tracker that I download movies on the early swarm to improve my ratio and reputation. However many movies are uploaded there that I don't have on my Radarr, so the Radarr action ends up rejecting them.

I can force autobrr to add them to the download client directly, but it is a waste of disk space not to have them on my radarr-plex flow.

**Describe the solution you'd like**
I wanted Radarr action to have the option to add the unmonitored movie into Radarr so that Radarr can approve the new release immediately.

**Comment by zze0s** [comment]
Hi!

This question comes up every now and then (mainly on our Discord) and it's in the maintainers opinion this feature has no place in autobrr, and here's why.

Say you monitor two big general indexers like TL and IPT, they get 100s of unique movie releases uploaded every day. 

If there was a feature to add the new titles as monitored in your Radarr you could get 100s of new movies each day, that you most likely do not want in your library. It would clutter your arr and be a pain to remove all the newly added media each day that you do not want.

We (the maintainers) think the better approach is to keep the wanted media (Radarr) separate from the "increase my ratio media". And that is already supported in autobrr.

1. Set your Radarr filter to a high priority like 1000 and check [these filter examples](https://autobrr.com/filters/examples#movies---radarr)
2. Create a new filter with a lower priority, say 100, for the "improve ratio filter". Use categories and resolutions if you only want movies and maybe set Max Downloads per Day to a reasonable number. Combine that with an external filter for a [freespace check script](https://autobrr.com/filters/external#script) so you do not fill your disk. Set that filter to send directly to your download client. If you have qbit you can improve it further by setting Max Active Downloads in the autobrr qbit client settings, [see this](https://autobrr.com/filters/examples#build-buffer)
3. If you want to go one step further then look into [omegabrr](https://autobrr.com/filters/omegabrr) which you can use to setup lists with popular upcoming movies and tv which will maybe grab titles you could be interested in and if it grabs something you want then add it manually in the arr and change the category and have it import the already downloaded release.

I hope this covers the reason why a feature like this does not already exist.

**Comment by gmcouto** [comment]
I sort of already have done those, except for `omegabrr`.

I don't see the point on having such complex lists on `autobrr`, because if the lists are already in sync with my Radarr/Sonarr clients, any upload that is new or is an upgrade will start downloading anyways as long as they are in my lists.

The real conundrum is what to do with some movies `I didn't plan on downloading, but now I have downloaded them anyways`?

The issue is that I think it is a waste of hard disk space having so many movies that are not properly organized, or not even available to watch on my Jellyfin/Plex instances.

I let my autobrr download any 1080p movies from a certain tracker because I think they are small enough to not fill up my disk space, and this tracker has almost no duplicates at all, and is very organized. Those are good for automatically adding them into radarr.

And is not like I care about my low-resolution library that much, but they are there.

I managed to workaround this with Webhooks, and it was surprisingly easy. If anyone come up after me, and is interested:

`https://RADARR-INSTANCE/api/v3/movie?apikey=YOUR-KEY-HERE`
```json
{
    "title": "",
    "monitored": true,
    "minimumAvailability": "released",
    "isAvailable": true,
    "qualityProfileId": 7,
    "tmdbId": {{ .Tags }},
    "addOptions": {
        "monitor": "none",
        "searchForMovie": false
    },
    "rootFolderPath": "/media/movies-hd" // ROOT FOLDER HERE
}
```

The only requirement is that your tracker parser must read the TmdbId on some variable. On Locadora, it is on `tags` variable. (Reference: https://github.com/autobrr/autobrr/pull/1433)

**Comment by gmcouto** [comment]
If anyone is looking for a solution for this, I have worked on an easy to configure tool that helps you setup just that:
> Force adding new-unknown movies to Radarr when you download them through autobrr

https://github.com/gmcouto/mediaddrr
