### ISSUE TITLE
[FEATURE REQ] Add torrent to Qbittorrent as "Download first and last pieces first"

### ISSUE THREAD

**Issue by KyokoMiki** [autobrr/autobrr#1510]
**Is your feature request related to a problem? Please describe.**
I want to add this feature in web/src/screens/filters/sections/action_components/ActionQBittorrent.tsx, but after taking a look, the existing parameters do not support this setting. To add it, it would likely require adding keys to the database and could potentially cause incompatibility between the modified database and the original one. Therefore, I would like to ask if there are any good solutions to handle this.

**Comment by zze0s** [comment]
Hey @KyokoMiki

Soup was quick to implement this but if there's other things then his PR is a great example to look at to implement similar features!
