### ISSUE TITLE
[INDEXER REQ] HD-Only

### ISSUE THREAD

**Issue by kaypoush** [autobrr/autobrr#1524]
# Indexer request

-  Do they have irc announce? Yes
- `autodl-irssi .tracker` file: No

- Indexer name: HD-Only
- Short name: HD-O
- URL: https://hd-only.org
- Download link example: https://hd-only.org/torrents.php?action=download&id=TORRENTID&authkey=AUTHKEY&torrent_pass=PASSKEY

## Announce example

- Harry Potter à l'école des sorciers [2001] [Film] - Blu-ray 4K / HEVC / 2160p / Muet / Multilingue / VOF / VO / stFR / VFF / VFI / VFQ / VF? / Scene / Bonus / Custom / HDR / HDR10+ / DV / RM / DC / VL / UC / UR / FL / NIMA4K - https://hd-only.org/torrents.php?id=GROUPID / https://hd-only.org/torrents.php?action=download&id=TORRENTID - Aventure, Fantastique

## IRC Network

- Network name: HD-Only
- Network address: irc.hd-only.org
- Port: 6697
- SSL/TLS: Yes
- NickServ registration required? No
- Is there a required format for the nick? No
- Invite command: /msg HD-Bot enter CHANNEL USERNAME IRCKEY

**Comment by s0up4200** [comment]
Hello @kaypoush! Unless the announcer is also called HD-Bot, could you also provide the name of the IRC-bot, and the name of the channel the IRC-bot is sending announces to?

**Comment by kaypoush** [comment]
> Hello @kaypoush! Unless the announcer is also called HD-Bot, could you also provide the name of the IRC-bot, and the name of the channel the IRC-bot is sending announces to?

Hi. It's also called HD-Bot. They have one bot for everything. It's sending announces to #announce channel which is invite only.

**Comment by kaypoush** [comment]
@s0up4200 Sorry I forgot to indicate but there are more than one category:

Film, Dessin animé, Série, Série Animée, Film d'animation, Concert, Documentaire, Spectacle, Court-métrage, Clip, Démonstration, Autre

**Comment by kaypoush** [comment]
Also last release tag is release group name. When there is no release group name specified, that can be an issue. I can ask this to be to changed if you want.

**Comment by kaypoush** [comment]
> If FL and GROUP can be separated with `-` instead of `/` that would be great.

Done ! If you need any other change or explanation just ask. Thank you for https://github.com/autobrr/autobrr/pull/1525
