### ISSUE TITLE
Indexer update Base URL for release links

### ISSUE THREAD

**Issue by KyokoMiki** [autobrr/autobrr#1531]
**Version**
The autobrr version you're running. If you run something other than latest, please update before reporting issues.
develop / commit:ccff369f30acf8cf060868128115d3a2a8231a23

**Describe the bug**
The base URL field in the indexers specifies the domain name as https://www.torrentleech.cc, but when actually downloading torrents, it still calls https://www.torrentleech.org, causing the download to fail.

**Screenshots**

![image](https://github.com/autobrr/autobrr/assets/161209740/06fec1f7-7953-4010-ad32-cb1be53ff05a)
![image](https://github.com/autobrr/autobrr/assets/161209740/d1b31aa4-cb7a-453d-9f45-646a0461a3d7)

**Comment by s0up4200** [comment]
Changing the `base_url` will only work for future announces, not previous ones.
There has been talks about how to fix this, but there is no concrete solution yet.

**Comment by KyokoMiki** [comment]
Thank you very much!
