### ISSUE TITLE
qbittorrent: client.timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by KyleSanderson** [autobrr/autobrr#154]
I've destroyed my client by adding a couple thousand torrents to it which it's working through. autobrr seems to only try a single attempt to push, and if it timesout gives up forever and skips the action. I suppose the request is to add configurable retries (and perhaps default to something reasonable, like 3 if the client is angry with what it's been assigned).

**Comment by ludviglundgren** [comment]
It's a hard thing to test, but I've added this in the pr #155
