### ISSUE TITLE
Can no longer reach login screen when using Synology reverse proxy [v1.41.0]

### ISSUE THREAD

**Issue by SawkeeReemo** [autobrr/autobrr#1542]
**Version**
v1.40.1

**Describe the bug**
Can no longer reach Autobrr via reverse proxy when managed by Synology's reverse proxy system. It starts to load, but then you just get an all black page with no login box. If I revert back to the older v1.40.1 version, then I can log in again. 

SIDE NOTE:  After I've logged in with the v1.40.1, if I leave my browser open, then upgrade the autobrr docker container to v1.41.0, I stay logged in and can work as normal. This seems to be some sort of issue with just getting to the log in screen now that didn't exist before.

EDIT: I can, however reach the log in screen if I connect to autobrr locally, just not through reverse proxy on this version. 

**Expected behavior**
This worked fine until v1.41.0.

**Desktop (please complete the following information):**
 - OS: Synology DSM 7.1.1 & Docker version 20.10.23, build 876964a 
 - Browser: Chrome [macOS Catalina]
 - Version: 124.0.6367.119

**Comment by zze0s** [comment]
Hi! Can you test with a separate browser or incognito window? Is there anything in the logs of autobrr, preferably on Trace level. Do you run a baseurl like `/autobrr`?

What does the config look like for the reverse proxy?

**Comment by SawkeeReemo** [comment]
I tried both Firefox and Chrome, same results. But it did work in incognito mode in Chrome. Guess I just need to clear the browser cache or something. 

But also thanks for giving me the idea to look up where Syno even keeps the reverse proxy config. Never thought to look for it before. ...haven't found it yet, but if I do, and have any more issues, I'll make sure to post it here.

**Comment by zze0s** [comment]
Hopefully this [PR #1527](https://github.com/autobrr/autobrr/pull/1527) fixes the issue. We'll do a RC release in a bit that we'd be happy if you test out! :slightly_smiling_face:

**Comment by SawkeeReemo** [comment]
Oh yeah! That will probably do it. Always happy to test. Thanks for all the great work on this. Love Autobrr and wish I set it up much sooner.

**Comment by zze0s** [comment]
> Oh yeah! That will probably do it. Always happy to test. Thanks for all the great work on this. Love Autobrr and wish I set it up much sooner.

There's now a new image tag you can try `v1.42.0-rc1`. You can't revert back to a lower version once you use this one unless you take a backup of your database before upgrading.

We have tested it quite a bit already and everything looks good so far but more testers and feedback are always great.

**Comment by SawkeeReemo** [comment]
Ok, I'll give it a shot! Easy for me to zip up my config folder and revert if needs be. Thanks for the heads up! (also, pardon the newbish question, but if I run into an issue with that version, where would you prefer I interact with you about it?)

**Comment by zze0s** [comment]
Sounds good! The [autobrr Discord server](https://discord.gg/WQ2eUycxyT) is where we hang out and have an active community :)

**Comment by SawkeeReemo** [comment]
Perfect. I’m already in there!

**Comment by SawkeeReemo** [comment]
Yup. I’m on 1.42.0 right now and haven’t had any login issues!
