### ISSUE TITLE
autobrr don't set Tags for qBittorrent

### ISSUE THREAD

**Issue by vip5912** [autobrr/autobrr#1551]
**Version**
1.42.0

**Describe the bug**
I configured the Filter with Action qBittorrent with Category (tv) & Tags (TL).
New torrent contains only Category, Tags are empty.
I can set Tag (TL) manually by WebGUI.

**Expected behavior**
New torrent with Category & Tags.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Browser [Firefox]
 - Version [126.0]
 
**Server:**
 - OS: [Debian 11]
 - Download client [qBittorrent]
 - Version [4.2.5]

**Comment by s0up4200** [comment]
v4.2.5 was released over 4 years ago. It works as expected in v4.3.9 (and above from what I can tell). I'd consider upgrading and see if that works.

**Comment by vip5912** [comment]
OK. Thank you. You can close the case.
