### ISSUE TITLE
[FEATURE REQ] SOCKS5 support for irc client

### ISSUE THREAD

**Issue by blixten85** [autobrr/autobrr#1554]
I want to request SOCKS5 support for the irc client.

**Comment by zze0s** [comment]
Hey!

It's being worked on. See https://github.com/autobrr/autobrr/pull/1421

and this issue https://github.com/autobrr/autobrr/issues/728

**Comment by zze0s** [comment]
Hopefully before the end of this year ;) Will pick it up again after Skip Duplicates is done.
