### ISSUE TITLE
[FEATURE REQ] Library/Archive List Tab

### ISSUE THREAD

**Issue by daymanbpi** [autobrr/autobrr#1559]
**Describe the solution you'd like**

-A tab similar to the release tab, that is searchable. Called Library or Archive or something else.
-Able to import your current library list of releases from a csv, json, text file, copy/paste, etc.
-Able to search this tab for keywords or release names.
-A release sent to the downloader, would be added to this Library List.
-Releases already in this library would not be sent to downloader.
-This would also tie into the duplicate download issue, when that is implemented.
-Would be an easy way for users with large release libraries to keep track of old releases that hit irc announces, and are not wanted.

**Describe alternatives you've considered**

Tie in to: Skip duplicates issue. 
https://github.com/autobrr/autobrr/issues/375
https://github.com/autobrr/autobrr/pull/1539

**Comment by zze0s** [comment]
Hi! Keeping multiple tables of similar data would increase complexity and actually make duplicate checks harder.

It would be much better to import your data into the existing releases table. If you have that type of data available somewhere (db, file) you should be able to write some simple scripts to help you import it into SQLite or Postgres.

ChatGPT or other similar tools does a good job with this type of thing if you lack the knowledge.
