### ISSUE TITLE
[INDEXER REQ] FinElite

### ISSUE THREAD

**Issue by lepis0** [autobrr/autobrr#1561]
# Indexer request

-  Do they have irc announce? Yes
- Indexer name: FinElite
- Short name: FE
- URL: https://finelite.org
- Download link examples with key: https://finelite.org/lataa/PERSONAL-DOWNLOAD-KEY/TORRENT-ID.torrent
Personal download key can found by checking url of any torrent download link in site.

## Announce examples

- The Dark Knight Rises 2012 UHD BluRay 2160p DTS-HD MA 5 1 DV HEVC HYBRID REMUX-FraMeSToR [Movies 4K] 69.98 GB https://finelite.org/details/71432
- Ege Zulu-Mammanpoika-WEB-FI-2024-KALEVALA [Music MP3] 72.08 MB https://finelite.org/details/71443 (43 seconds after pre)
- One Piece S01 NORDiC 1080p WEB-DL H 264 DDP5 1 Atmos-PiTBULL [TV Pack] 17.44 GB https://finelite.org/details/71410
- Transformers Collection (1984-2016) [Ebooks] 40.91 GB https://finelite.org/details/71399
- Godzilla x Kong The New Empire 2024 HDR 2160P WEB H265-POKE [Movies 4K] 16.48 GB https://finelite.org/details/71395
- Comeback 2023 FiNNiSH 1080p WEB H264-TOOSA [Movies HD] 6.11 GB https://finelite.org/details/71414 (3 minutes 10 seconds after pre)
- Tracker 2024 S01E08 1080p WEB DDP5 1 H 264-R75 [TV HD] 2.62 GB https://finelite.org/details/71445

## IRC Network

- Network name: PREDATABASE
- Network address: irc.predataba.se
- Port: 6697
- SSL/TLS: Yes
- NickServ registration required? No
- Is there a required format for the nick? No
- Invite command: n/a
- Channel: #announce
- Announce bot: FinElite

## Bonus

Categories (names are same at announce and site):
Audiobooks
Documentary
Ebooks
Games - Console
Games - PC
Kids
Movie Pack
Movies 4K
Movies BD
Movies DVD-r
Movies HD
Movies SD
Music FLAC
Music MP3
Music video
Sports
TV 4K
TV DVD-R
TV HD
TV Pack
TV SD

**Comment by mobbi-dev** [comment]
[finelite.yaml](https://raw.githubusercontent.com/mobbi-dev/autobrr/feature/FinElite/internal/indexer/definitions/finelite.yaml)
