### ISSUE TITLE
Telegram Notifications

### ISSUE THREAD

**Issue by wwsh123** [autobrr/autobrr#1564]
**Version**
autobrr 1.42.0

**Describe the bug**
Can't get Telegram notifications to work.
Logs report: telegram client request error: {error="bad status: 400 body: "= module=notification stack=[{"func":"(*telegramSender).Send","line":"113","source":"telegram.go"},{"func":"(*service).Test","line":"276","source":"service.go"},}
Docs are unhelpful.

**To Reproduce**
1. Go to Settings
2. Go to Notifcations
3. Add a name, select Telegram as type, select all events.
4. Under settings, input the settings, Bot token, Chat ID, Telegram Api Proxy. Message Thread ID is blank
5. Press 'Test' button and check logs.

**Expected behavior**
Telegram notifications to work properly.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Additional context**
Bot token, Chat ID and host are correct. They work on other apps on this device.  I even created a super group and it still shows error="bad status: 400
Thanks！
The Logs
18:04:44 ERR telegram client request error: module=notification sender=telegram
18:04:44 ERR error sending test notification: domain.Notification{ID:1, Name:"tg", Type:"TELEGRAM", Enabled:true, Events:[]string{"IRC_DISCONNECTED", "PUSH_APPROVED", "PUSH_REJECTED", "PUSH_ERROR", "IRC_RECONNECTED", "APP_UPDATE_AVAILABLE"}, Token:"648979*****:*****************", APIKey:"", Webhook:"", Title:"", Icon:"", Username:"", Host:"http://127.0.0.1:*****", Password:"", Channel:"-********", Rooms:"", Targets:"", Devices:"", Priority:0, Topic:"", CreatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), UpdatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC)} error="bad status: 400 body: "= module=notification stack=[{"func":"(*telegramSender).Send","line":"113","source":"telegram.go"},{"func":"(*service).Test","line":"276","source":"service.go"},{"func":"notificationHandler.test","line":"128","source":"notification.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"459","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"327","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"Server.IsAuthenticated-fm.Server.IsAuthenticated.func1","line":"85","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*ChainHandler).ServeHTTP","line":"31","source":"chain.go"},{"func":"(*Mux).routeHTTP","line":"459","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"327","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"459","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*Cors).Handler-fm.(*Cors).Handler.func1","line":"289","source":"cors.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"Server.Handler.LoggerMiddleware.func3.1","line":"131","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"Recoverer.func1","line":"45","source":"recoverer.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"RealIP.func1","line":"36","source":"realip.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"RequestID.func1","line":"76","source":"request_id.go"},{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"90","source":"mux.go"},{"func":"serverHandler.ServeHTTP","line":"3137","source":"server.go"}]

**Comment by zze0s** [comment]
Hey! Do you have just the ip without port in Host, or redacted the port? And you are running a telegram proxy on that ip:port?

**Comment by wwsh123** [comment]
> Hey! Do you have just the ip without port in Host, or redacted the port? And you are running a telegram proxy on that ip:port?
Hello; The symbol ** I typed was ignored.**
![微信图片_20240531111314](https://github.com/autobrr/autobrr/assets/40262350/da72f7cd-d5f0-4939-9d13-1caaab4c6bf1)

Host: http://127.0.0.1:7890;

**Comment by wwsh123** [comment]
The python script with the same configuration runs fine on the same device
![06AF5B808F182D38307CA200B3F449D0](https://github.com/autobrr/autobrr/assets/40262350/0cc9caa2-7781-4058-8880-57f468606c93)
