### ISSUE TITLE
TV Chaos

### ISSUE THREAD

**Issue by funkyronster** [autobrr/autobrr#1572]
**We currently only support indexers with IRC announces.**

# Indexer request

TV Chaos

-  Do they have irc announce? Yes / No
-  Link to existing `autodl-irssi .tracker` file: Check wiki, forums and autodl-trackers repo

Server. irc://irc.p2p-network.net
Channel. #chaosuk

### If no existing `autodl-irssi .tracker` file

- Indexer name: Indexer Name
- Short name: IN
- URL: https://indexer.request
- Download link examples with key such as `passkey, rss key, auth key, torrent pass` etc

Instructions from TV Chaos ... sorry I don't understand much of this.

Here is how you can connect to our IRC channel: All you need is a IRC client.
To download one of the stand alone clients pick one of the ones below

XChat http://xchat.org/
mIRC http://www.mirc.com/
Chatzilla https://addons.mozilla.org/en-US/firefox/addon/16

Download and run the client

For XChat, type: /server irc.p2p-irc.net You type this in the command box at the bottom of the screen. Then type /join #chaosuk
For MIRC, type: /server irc.p2p-irc.net You type this in the command box at the bottom of the screen. Then type /join #chaosuk
For Chatzilla, type: /server irc.p2p-irc.net You type this is the command box at the bottom of the screen. Then type /join #chaosuk

Server. irc://irc.p2p-network.net
Channel. #chaosuk

Registering Your Nick:
Connect to Irc via Java Chat or an Irc Client of your choice, connect at /server irc://irc.p2p-network.net
When logged type:

/msg nickserv REGISTER password email

Instead of password type your desired password and instead of e-mail, a valid email address.

Identifying Your Nick:

Every time you log in to irc you'll have to identify your nick. Do it by one of the following methods:

1) Type /msg nickserv identify password (The password used here is the one you picked when you
registered)

2) By setting your client to do it for you everytime you log in:

In your client option go to Connect -> Option > Perform

In the new window you must type /msg nickserv identify password

replacing password for your password.

After that join a channel with:
/join #chaosuk

RSS feed

https://tvchaosuk.com/rss/571.3635fe5656b8bd9a8306aaa9b8e11769

## Announce examples

<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<atom:link href="!#" rel="self" type="application/rss+xml"/>
<title>TV Chaos UK RSS Feed</title>
<link>https://tvchaosuk.com</link>
<ttl>5</ttl>
<description>Powered By UNIT3D Community Edition v2.2.7</description>
<item>
<title>Sun, Sea and Selling Houses S07E04 (06 Jun 2024) [540p mp4 subs]</title>
<link>https://tvchaosuk.com/torrent/download/172444.3635fe5656b8bd9a8306aaa9b8e11769</link>
<description>Reality / SD / 407.96 MiB </description>
<author>Uploaded By fanhtfc</author>
<pubDate>Thu, 06 Jun 2024 17:58:22 +0000</pubDate>
<comments>https://tvchaosuk.com/torrents/172444</comments>
</item>
<item>
<title>The Chase (06 Jun 2024) [576p mp4 subs]</title>
<link>https://tvchaosuk.com/torrent/download/172443.3635fe5656b8bd9a8306aaa9b8e11769</link>
<description>Entertainment / SD / 600.31 MiB </description>
<author>Uploaded By fanhtfc</author>
<pubDate>Thu, 06 Jun 2024 17:49:49 +0000</pubDate>
<comments>https://tvchaosuk.com/torrents/172443</comments>
</item>
<item>
<title>Paul Martins Antiques Showdown S01E62 (June 6 2024 [540p mp4]</title>
<link>https://tvchaosuk.com/torrent/download/172442.3635fe5656b8bd9a8306aaa9b8e11769</link>
<description>Factual / SD / 526.14 MiB </description>
<author>Anonymous Uploader</author>
<pubDate>Thu, 06 Jun 2024 17:23:38 +0000</pubDate>
<comments>https://tvchaosuk.com/torrents/172442</comments>
</item>
<item>
<title>Fifteen-Love - Series 1 (2023) [1080p mp4 subs]</title>
<link>https://tvchaosuk.com/torrent/download/172441.3635fe5656b8bd9a8306aaa9b8e11769</link>
<description>Drama / HD1080p Pack / 13.18 GiB </description>
<author>Anonymous Uploader</author>
<pubDate>Thu, 06 Jun 2024 17:21:01 +0000</pubDate>
<comments>https://tvchaosuk.com/torrents/172441</comments>
</item>
<item>
<title>Fifteen-Love - Series 1 (2023) [540p mp4 subs]</title>
<link>https://tvchaosuk.com/torrent/download/172440.3635fe5656b8bd9a8306aaa9b8e11769</link>
<description>Drama / SD Pack / 2.14 GiB </description>
<author>Anonymous Uploader</author>
<pubDate>Thu, 06 Jun 2024 17:18:07 +0000</pubDate>
<comments>https://tvchaosuk.com/torrents/172440</comments>
</item>
<item>
<title>The Turn Of The Screw - BBC R4 Horror (2004) [MP3-128kb/s]</title>
<link>https://tvchaosuk.com/torrent/download/172439.3635fe5656b8bd9a8306aaa9b8e11769</link>
<description>Radio / Radio / 52.18 MiB </description>
<author>Uploaded By alreadydead</author>
<pubDate>Thu, 06 Jun 2024 16:58:10 +0000</pubDate>
<comments>https://tvchaosuk.com/torrents/172439</comments>
</item>

Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.

- `SOME LONG ANNOUNCE`
- `OTHER ANNOUNCE`

## IRC Network

- Network name: TrackerNetwork
- Network address: irc.network.tld
- Port: 6697 is common for TLS
- SSL/TLS: Yes / No
- NickServ registration required? Check wiki, guides etc: Yes / No
- Is there a required format for the nick? Like `username|bot`? Check wiki, guides etc
- Invite command: Eg. `invitebot announce USERNAME IRCKEY`

## Bonus

Check their categories in the announce an on site

Announce category - Site category name

Note - TV Chaos specialise in hard to get UK TV progs, not available anywhere else. I have been using RSS in rtorrent but it is so unreliable. My seedbox provider recommended autobrr.

**Comment by zze0s** [comment]
Hi! @funkyronster you need to rotate your RSS key immediately. You should have redacted it or changed a number or something.

**Comment by funkyronster** [comment]
Sorry I have no idea what you are talking about. I am reasonably tech savvy, but not in this subject.

**Comment by zze0s** [comment]
On their site in your profile you need to reset your RSS key, since you posted it publicly so anyone with the link can now download as if they were you. Message stuff if there's no such button in your profile.

Also this looks to be only RSS? Use Generic RSS indexer. If they do have irc announce then open a new issue. I'll close this. Join our Discord if for further discussion.
