### ISSUE TITLE
FNP parsing issues when announce contains to many bracket pairs

### ISSUE THREAD

**Issue by gugatinho** [autobrr/autobrr#1579]
**Version**
v1.43.0

**Describe the bug**
I'm assuming problem is around [ ], but let me explain
If name announced is [something - another thing (year) [tag1 tag2] - [group]], macro TorrentName is returning group] and not something - another thing

**To Reproduce**
1. create indexer irc announce fearnopeer
2. create a filter for that indexer
3. set a external filter webhook using macro TorrentName. Like:
{
  "name": "{{ .TorrentName }}",
  "guid": "{{ .TorrentUrl }}",
  "link": "{{ .TorrentUrl }}",
  "tracker": "{{ .IndexerName | js}}"
}
4. Wait for name containing [daniflix] from itscooldani 
5. Check log

**Expected behavior**
Maybe this is what it is. Maybe [] should not be used in announced name. I don't know, but name isn't being get correctly

**Screenshots**
I cleaned up logs, I'm not sure if I can publish names so I redacted: 
{"level":"debug","module":"irc","network":"irc.librairc.net","channel":"#fearnopeer-announce","nick":"FnP","time":"2024-06-19T19:08:23-03:00","message":"[FnP] New Upload - Category: [Music] Type: [FLAC] Name: [REDACTED - REDACTED (REDACTED) - {barcode-REDACTED} - [FLAC 24bit 48kHz] - [daniflix]] Size: [535.78 MiB] Uploader: [itscooldani] Url: [https://fearnopeer.com/torrents/136309]"}
…
{"level":"debug","module":"filter","time":"2024-06-19T19:08:31-03:00","message":"successfully ran external webhook filter to: (http://10.1.2.220:2468/api/announce) payload: ({\n  \"name\": \"daniflix]\",\n  \"guid\": \"https://fearnopeer.com/torrent/download/136309.REDACTED\",\n  \"link\": \"https://fearnopeer.com/torrent/download/136309.REDACTED\",\n  \"tracker\": \"FearNoPeer\"\n}) finished in 7.783763073s"}
{"level":"debug","module":"filter","method":"CheckFilter","time":"2024-06-19T19:08:31-03:00","message":"(FILTER_NAME_REDACTED) external filter check not matching what filter wanted"}
{"level":"debug","module":"release","indexer":"fnp","filter":"FILTER_NAME_REDACTED","release":"daniflix]","time":"2024-06-19T19:08:31-03:00","message":"filter FILTER_NAME_REDACTED  rejected release: external webhook unexpected status code. got: 204 want: 200"}

**Desktop (please complete the following information):**
 - OS: Docker 26.1.4
 - Browser Safari 17.5

**Additional context**

**Comment by zze0s** [comment]
Hi! Looks like this isn't a macro problem but actually an issue with the regex for the announce line. It doesn't expect all those bracket pairs.

Will make a fix for this.
