### ISSUE TITLE
Screen to add Notifications keeps sliding away on mobile browsers

### ISSUE THREAD

**Issue by appiekap653** [autobrr/autobrr#1583]
**Version**
The autobrr version you're running. If you run something other than latest, please update before reporting issues.

1.43.0

**Describe the bug**
When trying to add a new notification agent the screen where you enter the name, type, etc. keeps sliding away off-screen when ticking on any component (name field, dropdown box, etc.).

Tried with Firefox and Chrome browsers for Android.

Android version: 14, Samsung OneUI 6.1

When on landscape mode the screen won't even show up. You just see a small grey rectangle popup on the side but no screen. 

**To Reproduce**
1. Go to Settings -> Notifications
2. Click on + Add New
3. Click on anything. 

**Expected behavior**
The screen to keep in place so you can enter text in the name field and to be able to choose the agent type from the dropdown box.

**Comment by martylukyy** [comment]
Hi!

This is a known issue that is already fixed in the develop branch by #1578 
However, i have no ETA for a new stable release that fixes this currently.

**Comment by v3ctordesign** [comment]
It's happening on desktop too. I'm running the latest in a docker container and using it in chrome.
https://imgur.com/a/MTMkL7e
The only thing that's not closing the pane is the close button :D

Any workarounds until the update comes out with the fix?

**Comment by martylukyy** [comment]
You should be able to navigate in it with your keyboard with TAB.
The buttons can be selected with SPACEBAR once reached with TAB.

**Comment by v3ctordesign** [comment]
Yup! Works great! Also you dont even have to do everything this way, just give it a name, save, and after it's created, when editing, the original issue is gone so you can do everything properly.
