### ISSUE TITLE
filter for series

### ISSUE THREAD

**Issue by bleriaf** [autobrr/autobrr#1590]
Hello, yesterday i found about this repo and i have been using it and it's been amazing, really good job!
But i was wondering how i could add a different filter for movies and for series; since i want to add an action with qbittorrent that chooses a different path for both but i cant do that.

thanks!

**Comment by zze0s** [comment]
Hey! Happy you find it useful!

The best way is to use categories that are usually part of the announce. You can find a list of the most common ones [here on the docs](https://autobrr.com/filters/categories).

Might also want to check the [filter examples](https://autobrr.com/filters/examples) :slightly_smiling_face: 

Hope that helps! If you have further questions then please [join our Discord community](https://discord.gg/WQ2eUycxyT) where we have a lot of active and helpful users!

**Comment by bleriaf** [comment]
> Hey! Happy you find it useful!
> 
> The best way is to use categories that are usually part of the announce. You can find a list of the most common ones [here on the docs](https://autobrr.com/filters/categories).
> 
> Might also want to check the [filter examples](https://autobrr.com/filters/examples) 🙂
> 
> Hope that helps! If you have further questions then please [join our Discord community](https://discord.gg/WQ2eUycxyT) where we have a lot of active and helpful users!

Thanks! that's working well!
