### ISSUE TITLE
FearNoPeer/ReelFlix trackers: wrong downloadURL

### ISSUE THREAD

**Issue by nickdemise** [autobrr/autobrr#1593]
Versions
Autobrr 1.43.0
Radarr 5.7.0.8882

Autobrr is setup with IRC feeds for FearNoPeer (FNP), ReelFlix (RF) and TorrentLeech (TL)
All IRC feeds are up and running.
I have both Radarr and Sonarr filters running for all three index/irc
Everything seems wired up correctly. New releases are grabbed from all three irc channels, and promptly sent to Radarr for validation.

TL announces get parsed correctly and gets a valid downloadURL to Radarr, and is immediately added to my torrent client.
However, the FNP/RF downloadURL are incorect. Is this field generated by Autobrr ? They are in its logs so i assume so.

The downloadURLs are of an invalid format (https://fearnopeer.com/torrent/download/151658.MY_API_KEY), and thus no .torrent is parsed/downloaded and added to my client.
Please see logs for further details

[radarr.debug.txt](https://github.com/user-attachments/files/16255829/radarr.debug.txt)
[autobrr.debug.txt](https://github.com/user-attachments/files/16255830/autobrr.debug.txt)
 
Attached autobrr debug log, and radarr debug log. If you know how to mock a valid irc announce i can set to trace for more details?

I feel like i've missed something from my setup, but strange how it works for TL fine?

Thanks for looking, glad to attach further info.

**Comment by zze0s** [comment]
Hey! Both FNP and RF uses **RSS Key** and not API key. Change those and it should work. You can verify it after you change if you create a new filter for each indexer with max downloads 1 per Ever and use a watch folder action so it actually downloads the .torrent file.

As for the arr it does not require .torrent on the end of a downloadUrl.

**Comment by nickdemise** [comment]
oh i thought it would have been me doing something dumb :) thanks!
