### ISSUE TITLE
[FEATURE REQ] Set log path

### ISSUE THREAD

**Issue by fusk-l** [autobrr/autobrr#1594]
**Is your feature request related to a problem? Please describe.**
In logs, it says "no old logs". So you go to settings/logs where it says "path" & "not set" and no option to set it.

Autobrr just crashed a while ago, and no logs were saved. It does say that "max backup" is "3", but i assume this is manual backups, as none are available.
It's a feature request as i also assume there are other methods of setting the path. But i wonder why this isn't on by default and install directory is default path.
OS: Windows

**Comment by zze0s** [comment]
Hi! You need to set this in the config file, see https://autobrr.com/configuration/autobrr#config-options and then restart autobrr. Use an absolute path for it, like `C:/autobrr/logs/autobrr.log` or similar.

The way things are setup today does not allow for on the fly update/setting of log path so autobrr must be restarted and thus it's only doable via the config file.

**Comment by dmackca** [comment]
I'm curious about why this feature is "not planned"

**Comment by zze0s** [comment]
> I'm curious about why this feature is "not planned"

The main reason is it needs a full app restart to take effect with how things are built. Log level can easily be changed but log path requires re-init of the log setup.
