### ISSUE TITLE
[FEATURE REQ] Year field to support range that extends indefinitely in one direction

### ISSUE THREAD

**Issue by luckylittle** [autobrr/autobrr#1602]
**Is your feature request related to a problem? Please describe.**
I would like to specify `Year` as an open integer range, rather than specific range or single years. 

**Describe the solution you'd like**
For example, If you want to match all the years after 2022, you would simply use open, indefinite range `2022-`. E.g. If you want everything before 1999, you would enter `-1999` in the year field. This is currently not working and only way is to explicitly say what years you want.

**Describe alternatives you've considered**
Currently, this field takes a range of years and/or comma separated single years, which requires to update this field manually every year.

**Additional context**
Strangely, you can enter `2023-` in the field and the web interface does not complain, however it does not work as intended.

**Comment by zze0s** [comment]
Just set the end or start to something unreasonable like `2022-2099`.
