### ISSUE TITLE
[FEATURE REQ] Add bash support to autobrr docker image

### ISSUE THREAD

**Issue by KyokoMiki** [autobrr/autobrr#1605]
The current autobrr docker image doesn't have bash, only ash and sh. For the exec script functionality, many scripts need to be specially modified to be compatible with sh. It would be much better if bash could be supported.

**Comment by zze0s** [comment]
Hi!

All packages added to a container image becomes a potential attack surface. We run `alpine` based images that only ship with `sh` to minimize that.

For that same reason we don't have any python/node etc either.

That leaves users with two options:
1. Rewrite their scripts into sh or something that can be compiled into binaries (Go)
2. Tag your own image that uses ours as the base and adds additional tools to it.
