### ISSUE TITLE
[FEATURE REQ] Allow disabling authentication (where external auth methods like Authelia/Authentik are used)

### ISSUE THREAD

**Issue by pentago** [autobrr/autobrr#1611]
**Is your feature request related to a problem? Please describe.**
Using external/proxy-level authentication methods like Authelia/Authentik currently results in a double login issue.

**Describe the solution you'd like**
Ability to turn off authentication via login form in scenarios where a single user exists and where external/proxy-level authentication methods are used.

**Describe alternatives you've considered**
The alternative is publicly exposing the autobrr login form, which is a privacy/security risk considering it only relies on password authentication. 

**Additional context**
N/A

**Comment by zze0s** [comment]
Dupe of https://github.com/autobrr/autobrr/issues/483

Some more context here https://github.com/autobrr/autobrr/issues/979

**Comment by pentago** [comment]
@zze0s as an alternative, would something like Calibre Web do would be possible?

They allow setting a HTTP header name in app config that allows authentication and Authelia ships a number of headers by default.

For example, upon successful login to Authelia form, they pass on User-Name header downstream which opens an app without login form.
