### ISSUE TITLE
Show version in Docker release

### ISSUE THREAD

**Issue by YourHuckleberry** [autobrr/autobrr#162]
Currently, the version of autobrr isn't displaying anywhere.  Be good to see so we can decide if we want to upgrade to newest or not.

**Comment by ludviglundgren** [comment]
Hi! Are you using the built binaries, building yourself or docker version?

The built binaries have the version info under `Settings -> Application`. If building locally just with go it will just say `dev`. If building with `goreleaser` it will have to correct info as well (this is what the github action uses). The docker build only has the commit id currently but will add more info to it :)

**Comment by YourHuckleberry** [comment]
Hey there!  Using Docker.  Not even certain where to see commit id in the webui actually.

**Comment by ludviglundgren** [comment]
For docker it will look like this currently 
![image](https://user-images.githubusercontent.com/16375387/156823229-de1d2cee-11cf-47b2-9ae1-aaec58f2eda4.png)

**Comment by YourHuckleberry** [comment]
Interesting.  I must not be getting the most recent release, mine doesn't show this.  Pulling from the URL shown in the docs.
