### ISSUE TITLE
filter categories, tags, groups etc should be case-insensitive, at least optionally.

### ISSUE THREAD

**Issue by mikebones** [autobrr/autobrr#1624]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Uploads can be inconsistently tagged and therefore to easily match (or unmatch) it would be simple to perform a case insensitive match against the release.
I can see on `internal\domain\filter.go` , https://github.com/autobrr/autobrr/blob/develop/internal/domain/filter.go#L493-L513, that there is a contains method used to determine whether a release is matched or not. Another method of comparison instead of  `.contains` can be used so that it is case insensitive. This thread has some insight https://stackoverflow.com/questions/44595669/does-go-have-a-case-insensitive-string-contains-function

It could be optional via the web interface if desired.

**Describe alternatives you've considered**
making a huge list of categories that include capitalization differences that could occur

**Comment by zze0s** [comment]
Hi! All filters are case-insensitive by default. If you follow the code you linked into our `contains` you'll get [here](https://github.com/autobrr/autobrr/blob/develop/internal/domain/filter.go#L893-L921) and see that it is indeed case-insensitive.

```golang
func containsMatch(tags []string, filters []string) bool {
	for _, tag := range tags {
		if tag == "" {
			continue
		}
		tag = strings.ToLower(tag)
		tag = strings.Trim(tag, " ")

		for _, filter := range filters {
			if filter == "" {
				continue
			}
			filter = strings.ToLower(filter)
			filter = strings.Trim(filter, " ")
			// check if line contains * or ?, if so try wildcard match, otherwise try substring match
			a := strings.ContainsAny(filter, "?|*")
			if a {
				match := wildcard.Match(filter, tag)
				if match {
					return true
				}
			} else if tag == filter {
				return true
			}
		}
	}

	return false
}
```

Have you encountered any rejections where it did not match because of casing?

**Comment by zze0s** [comment]
Closing this for now and will open up if it's relevant with any replies.

**Comment by mikebones** [comment]
> Have you encountered any rejections where it did not match because of casing?

Yes  - this is specifically why I looked into this. I was reviewing snatched torrents vs my filters and found the case insensitivity. I think it would be valuable to offer case insensitive vs insensitivity.

**Comment by zze0s** [comment]
I still don't see the need for case sensitivity for filters. Can you give me any good reasons why you would need it and why case-insensitive is a problem?

We force set insensitive `(?i)` on the RegExs for **Match Releases** as well to have consistent behavior.

**Comment by mikebones** [comment]
> I still don't see the need for case sensitivity for filters. Can you give me any good reasons why you would need it and why case-insensitive is a problem?

I want the filter to be case insensitive. I had thought I observed a situation where it was insensitive.
