### ISSUE TITLE
If *arr release isn't grabbed, consider filter not matched instead of a match

### ISSUE THREAD

**Issue by YourHuckleberry** [autobrr/autobrr#163]
Because anything sent to Sonarr/Radarr is considered a successful match, even if the release is  rejected a release doesn't go through any other filters.  This makes it impossible to use autobrr to feed *arr endpoints as well as autodl.  A way to allow this functionality would be most useful.

**Comment by ludviglundgren** [comment]
Hi. 

Yep, you are correct. We have discussed this in the [Discord](https://discord.com/invite/WQ2eUycxyT) previously but have not yet gotten to it. As an intermediate solution @brettpetch built [arrbrr](https://gist.github.com/brettpetch/9475c9117e0d58791c02587529786ad9) which essentially grabs releases from the arrs and injects them into filters. 

> Arrbrr is a way of mutilating your arrs and getting them to tell you their secrets. 
> 
> 1. Create filter in autobrr with a name that arrbrr can match
> 2. Set the database path for arrbrr to find the autobrr database.
> 3. Input the names of the filters at the appropriate variables
> 4. Collect your api info for your arr
> 5. Input the info for the arr into the provided blocks
> 6. Setup a cronjob
> 
> Essentially, you setup the variables and run it on a crontab. It will then check to see if each item is monitored, and if it is, it will be added to the filter for Autobrr in a somewhat RE compliant way. Please report bugs directly to me, and notify me of any weirdness you encounter. 
> 
> NOTE: this script will backup the database ON EVERY RUN IT DOES, successful or not. you may need to go do some garbage collection every week in your autobrr config files.

This way it will work the way you want. It's not officially supported by me, and I leave no guarantees of it working 100%, but from what I hear it does work well.

So until filter and action logic is refactored this is a workaround :slightly_smiling_face:

**Comment by YourHuckleberry** [comment]
Totally understand, just thought I'd toss this in here so it didn't get lost and I could easily track.

**Comment by ludviglundgren** [comment]
Appreciate it! There's a [project board](https://github.com/orgs/autobrr/projects/1) for some of the planned stuff, but sometimes things aren't added. The Discord gets more real time updates so join that if you want. Link in previous comment. :slightly_smiling_face:
