### ISSUE TITLE
Create Feature Requests in Discussions

### ISSUE THREAD

**Issue by zze0s** [autobrr/autobrr#1695]
Please create [new Feature Requests in Discussions](https://github.com/autobrr/autobrr/discussions/new?category=ideas) with the Ideas category.

All Feature Requests added as Issues will be moved.

**Comment by onedr0p** [comment]
@zze0s you might want to update the links here to forward people to discussions for feature requests
https://github.com/autobrr/autobrr/issues/new/choose
