### ISSUE TITLE
[FEATURE REQ] Max downloads per X time interval

### ISSUE THREAD

**Issue by nateify** [autobrr/autobrr#1702]
**Is your feature request related to a problem? Please describe.**
I have a filter which has set max downloads to 1 per month. Since I set this filter up on 8/31 it downloaded one right away, but then downloaded another torrent today since it is now September. I would actually like to only have it download once per rolling 30 days (or some other interval). In other words after the first matched release, it should count X days from the time that download started before allowing another match to download.

**Describe the solution you'd like**
A new option in the Max downloads per dropdown to specify a time frame

**Describe alternatives you've considered**
Not sure if another good way to go about it but possibly this could be an advanced feature since it would require a new text input (specifying the amount of days or other interval)

**Comment by zze0s** [comment]
Hi! Looks like you missed this pinned message I put up earlier today about feature requests. https://github.com/autobrr/autobrr/issues/1695

Similar ideas:
- https://github.com/autobrr/autobrr/discussions/1657
- https://github.com/autobrr/autobrr/discussions/1670

Continue in one of the linked Discussions.
