### ISSUE TITLE
Torrentseeds is broken

### ISSUE THREAD

**Issue by KyleSanderson** [autobrr/autobrr#172]
Getting 404s on downloads so it's even failing to push despite using exec. Jackett flipped to the new Unit3d backend, there's an API key now that they're using.

**Comment by GregTroar** [comment]
Use it all day long for weeks without issues
Did not try today I will check

**Comment by GregTroar** [comment]
I confirm it snatched properly 2 hours ago and downloaded properly

**Comment by KyleSanderson** [comment]
Got double whammied on this one. my RID was changed, and because the IRC connection didn't bounce it didn't use the new data from the indexer.
