### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AronAtGit** [autobrr/autobrr#1734]
**Version**
1.46.1 on unraid.  I used community applications to install and configure.

I can't login to the webUI using the username and password I've created.  

I've created a username and password via the CL using the commands in the documentation but I am getting this message when I use those credentials to sign into the webUI: "HTTP request to 'api/auth/login' failed with code 403 (could not login: bad credentials)."

I'm wondering what I'm missing here and if anybody could help me out. Thank you!

**Comment by zze0s** [comment]
Hi! First time you visit the webui on a fresh install it should redirect you to /onboard where you can create your account. Did that not happen? Make sure all perms are correct for the storage and config dir.

You can try stop the container and remove the autobrr.db file, then restart it and see if you get to the /onboard page.

**Comment by AronAtGit** [comment]
Hey zze0s - thanks for your help! I removed the container, deleted the autobrr.db file and re-installed the container and it brought me to the onboarding page.  Not sure why it didn't bring me there when I installed the container but I think maybe I had an old autobrr.db file that I was unaware of.

Anyway all set now, thank you!
