### ISSUE TITLE
Could not connect to client Deluge: scan element 0: cannot convert from []uint8 into *int64

### ISSUE THREAD

**Issue by StardOva** [autobrr/autobrr#1736]
**Version**
1.46.1

**Describe the bug**
Pushing torrents to my Deluge v2 client results in error above. Have been using v1.45.0 before, after upgrading this error appears. The error does not occur with every snatch, only on some occasions. Torrents are 2024 FLACs from the biggest private music tracker.

Log entry (censored):
```
process action failed: add to deluge for 'xxxxx' error="could not connect to client Deluge at xxxx: scan element 0: cannot convert from []uint8 into *int64"= module=action stack=[{"func":"(*service).delugeV2","line":"199","source":"deluge.go"},{"func":"(*service).deluge","line":"39","source":"deluge.go"},{"func":"(*service).RunAction","line":"59","source":"run.go"},{"func":"(*service).runAction","line":"326","source":"service.go"},{"func":"(*service).processFilters","line":"270","source":"service.go"},{"func":"(*service).Process","line":"177","source":"service.go"},{"func":"goexit","line":"1700","source":"asm_amd64.s"}] 
``` 

**To Reproduce**
1. Add filter to snatch 2024 FLACs from private music tracker (don't know if it happens on other trackers too)
2. Add action to filter to push the snatch to a Deluge v2 client
3. observe error above (might need a couple of attempts, as the error happens only on some occasions)

**Expected behavior**
The torrent gets pushed to deluge v2 client without errors.

**Comment by zze0s** [comment]
Hi. What exact Deluge version are you running? One issue is probably enough for this as well.

**Comment by StardOva** [comment]
Hi, feel free to close the other one. I thought they might be separate due to the different error messages, but also seems like they are connected somehow.

I am using Deluge 2.1.1 with libtorrent 2.0.8.0
