### ISSUE TITLE
Filter fails on AlphaRatio indexer: "line not matching expected regex pattern"

### ISSUE THREAD

**Issue by bloomingdalee** [autobrr/autobrr#1740]
**Version**
latest

**Describe the bug**
When using a filter to monitor AlphaRatio IRC, it throws an error about the regex pattern being used.

Example debug messages:

```
12:28:14 DBG [New Release]-[MovieHD]-[Yooper.Creoles.Finnish.Music.In.Michigans.Copper.Country.2019.1080p.WEB.H264-JAVLAR]-[URL]-[ https://alpharatio.cc/torrents.php?id=2968618 ]-[ 2968584 ] channel=#announce module=irc network=irc.alpharatio.cc nick=Voyager
12:28:14 DBG line not matching expected regex pattern: [New Release]-[MovieHD]-[Yooper.Creoles.Finnish.Music.In.Michigans.Copper.Country.2019.1080p.WEB.H264-JAVLAR]-[URL]-[ https://alpharatio.cc/torrents.php?id=2968618 ]-[ 2968584 ] indexer=AlphaRatio module=announce_processor network=AlphaRatio
12:28:14 DBG [AutoDL]-[MovieHD]-[2968584]-[ 1 | 3636 | 1 | 0 ]-[Yooper.Creoles.Finnish.Music.In.Michigans.Copper.Country.2019.1080p.WEB.H264-JAVLAR] channel=#announce module=irc network=irc.alpharatio.cc nick=Voyager
12:28:14 DBG line not matching expected regex pattern: [AutoDL]-[MovieHD]-[2968584]-[ 1 | 3636 | 1 | 0 ]-[Yooper.Creoles.Finnish.Music.In.Michigans.Copper.Country.2019.1080p.WEB.H264-JAVLAR] indexer=AlphaRatio module=announce_processor network=AlphaRatio 
```

**To Reproduce**
1. Configure the AlphaRatio IRC
2. Create a filter
3. Check the logs

**Desktop (please complete the following information):**
 - OS: Synology
 - Browser: N/A, it's not a webapp issue

**Additional context**
I believe the regex pattern can be found here:
https://github.com/autobrr/autobrr/blob/develop/internal/indexer/definitions/alpharatio.yaml

I think the issue is that it's trying to extract a `preTime` variable that is no longer being announced?

**Comment by martylukyy** [comment]
Hi!

I tried to replicate your issue but i wasn't able to unfortunatly.
We do not have a latest branch either so to further track down your issue 
i would need the exact version number of autobrr which you can find in the autobrr settings.

The capture group for the `preTime` variable is optional so this part of the announce not being there,
should not be an issue.

The last 500 announce plus the one you posted matched just fine with the current regex pattern.

https://regex101.com/r/9QWPkP/1

**Comment by bloomingdalee** [comment]
Ahh, okay this was my bad. I thought I was on the latest version because I was using a docker image created 3 days ago. In the app settings the version just said "dev". After you confirmed it was working for you, I installed the latest version from the repo and that worked, so I guess it was just a version issue after all!
