### ISSUE TITLE
Cannot validate certificate for 127.0.0.1 using SSL

### ISSUE THREAD

**Issue by ai4739** [autobrr/autobrr#175]
I am trying to set up QBT as a client, but autobrr will not test successfully, I suspect due to an SSL certificate check:

`ERR POST: do https://127.0.0.1:3535/api/v2/auth/login error="Post \"https://127.0.0.1:3535/api/v2/auth/login\": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"`

I can get QBT set up _without_ SSL, but all of my [other local] scripts already use SSL with a validation bypass.  This is perfectly normal, as I only run this instance locally, it's isolated completely from the rest of the network, and it uses a self-generated certificate.

Is there any way I can bypass this check, or we can add an option to bypass the SSL validation?

Thanks :D 

Configuration:

- qBittorrent 4.3.9
- WebUI bound to * on port 3535
- self-generated SSL certs
- Authentication bypassed for clients on localhost

autobrr:

- v0.18.0
- Commit 3b43ccba8a16c659c668387408eacc6aea867d9a
- date 2022-03-06T19:49:07.099Z

**Comment by ludviglundgren** [comment]
Hello. You're the first one to report this so probably first to run into the issue 😄 

The easiest thing would be to just add a `InsecureSkipVerify: true` to the request if it's with `https`, but having the option might be a nice to have.

Can start with the first and add the option later.

**Comment by ai4739** [comment]
I'm not used to contributing to projects, so I'm sorry for errant pull requests (and I now have `autobrr-1` instead of `autobrr` in my forks, but oh well).

I edited `pkg/qbittorrent/client.go`:

- add `"crypto/tls"` to import section
- add the following to `NewClient(s Settings) *Client` definition, before `httpClient` declaration:
```
//skip SSL verification
	tr := &http.Transport{
        	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    	}
```
- add `Transport: tr,` to `httpClient` declaration

With those changes, I re-built and can now successfully verify to my QBT client on 127.0.0.1 using SSL. Thanks for the suggestion!  [Here is my updated client.go](https://github.com/ai4739/autobrr-1/blob/master/pkg/qbittorrent/client.go)

**Comment by ludviglundgren** [comment]
Hehe yeah I saw you created a couple of forks and pr's from those 😄 but working with forks can be a bit tricky if you're not used to it.

I'll see if I can get that fixed today.

We have a [discord](https://discord.gg/WQ2eUycxyT) with a growing community if thats of interest 🙂

**Comment by ai4739** [comment]
I don't believe my "quick fix" should be rolled into the main development branch (that was not my intent), as skipping the validation should only be done if "you know what you're doing."  I can hold out for the option to bypass, and if anyone else who _knows what they're doing_ stumbles upon this, they at least have a solution :)

**Comment by ludviglundgren** [comment]
`InsecureSkipVerify: true` is not really that bad since there's no possibility to add your own certs etc, and some underlying libraries use it be default. 

I just merged a new feature with this and a toggle in the settings. Set to `false` by default 🙂 Will tag a release later this week/weekend. Available with docker `develop` tag for now.

**Comment by ai4739** [comment]
Just wanted to say thanks again!!  
I pulled the `develop` tag this morning, and the toggle is working perfectly!
Cheers!
