### ISSUE TITLE
Some seedpool announces are parsed incorrectly.

### ISSUE THREAD

**Issue by groggy9788** [autobrr/autobrr#1753]
**Version**
latest

**Describe the bug**
Announces from the seedpool indexer are not always parsed correctly, which results in them failing filters when they should pass. 

**To Reproduce**
I have a pretty simple autobrr setup for cross-seed and piping releases to sonarr/radarr. I have a cross-seed filter at the highest priority and an All Movies/Shows that pipes releases to sonarr/radarr for filtering. The only criteria I include on the filter in autobrr itself is resolution requirements to exclude SD content. These are the built in resolution filters, no custom regex/pattern matching.

I noticed that for the seedpool indexer specifically, it wasn't grabbing the [SubsPlease] releases from seedpool that I saw being accepted from other trackers. I opened the logs, and noticed that it seemed to be parsing the name of the release incorrectly. It looks like it detects the checksum at the end of the release title as the release name, and then fails parsing out any title/resolution information so it fails the filter before sending it to cross-seed. I assume that even if it did send it to cross-seed, it would not send the full title and it would fail the cross seed check as well. For now i have disabled the resolution checks on the cross-seed filter, and will see if that helps. 

**Expected behavior**
Autobrr should correctly parse incoming titles from the seedpool indexer the way it does for other indexers (subsplease/nyaa/ipt)

**Screenshots**
Here are debug logs from the ui showing the incoming release from IPT being accepted, but the same release being parsed incorrectly when it comes from seedpool a few minutes later:
```
05:45:17 DBG [Anime] [SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 51v2 (1080p) [5DAFE728] - https://www.iptorrents.com/details.php?id=<redacted> - 5.13 GB channel=#ipt.announce module=irc network=irc.iptorrents.com nick=IPT
05:45:19 DBG successfully ran external webhook filter to: (http://192.168.1.116:2468/api/announce) payload: ({ "name": "[SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 51v2 (1080p) [5DAFE728]", "guid": "https://iptorrents.com/download.php/<redacted>/[SubsPlease]+Re+Zero+kara+Hajimeru+Isekai+Seikatsu+-+51v2+(1080p)+[5DAFE728].torrent?torrent_pass=<redacted>", "link": "https://iptorrents.com/download.php/<redacted>/[SubsPlease]+Re+Zero+kara+Hajimeru+Isekai+Seikatsu+-+51v2+(1080p)+[5DAFE728].torrent?torrent_pass=<redacted>", "tracker": "IPTorrents" }) finished in 2.252459513s module=filter
05:45:19 INF Matched '[SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 51v2 (1080p) [5DAFE728]' (cross-seed) for IPTorrents filter=cross-seed indexer=ipt module=release release="[SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 51v2 (1080p) [5DAFE728]"
05:45:19 DBG release.store: &{ID:46338 FilterStatus:FILTER_APPROVED Rejections:[] Indexer:{ID:1 Name:IPTorrents Identifier:ipt IdentifierExternal:IPTorrents (Prowlarr)} FilterName:cross-seed Protocol:torrent Implementation:IRC Timestamp:2024-10-05 05:45:17.226015999 -0500 CDT m=+197972.912176349 InfoURL:https://iptorrents.com/details.php?id=<redacted> DownloadURL:https://iptorrents.com/download.php/<redacted>/[SubsPlease]+Re+Zero+kara+Hajimeru+Isekai+Seikatsu+-+51v2+(1080p)+[5DAFE728].torrent?torrent_pass=<redacted> MagnetURI: GroupID: TorrentID:<redacted> TorrentTmpFile: TorrentDataRawBytes:[] TorrentHash: TorrentName:[SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 51v2 (1080p) [5DAFE728] Size:5130000000 Title:Re Zero kara Hajimeru Isekai Seikatsu Description: Category:Anime Categories:[] Season:0 Episode:51 Year:0 Month:0 Day:0 Resolution:1080p Source: Codec:[] Container: HDR:[] Audio:[] AudioChannels: AudioFormat: Bitrate: Group: Region: Language:[] Proper:false Repack:false Website: Artists: Type:episode LogScore:0 HasCue:false HasLog:false Origin: Tags:[] ReleaseTags: Freeleech:false FreeleechPercent:0 Bonus:[] Uploader: PreTime: Other:[] RawCookie: Seeders:0 Leechers:0 AdditionalSizeCheckRequired:false FilterID:1 Filter:0xc000aec008 ActionStatus:[]} repo=release 
```

```
05:48:49 DBG Anime [SubsPlease] Re Zero kara Hajimeru Isekai Seikatsu - 51v2 (1080p) [5DAFE728] https://seedpool.org/torrents/41228 5.13 GiB channel=#announce module=irc network=irc.seedpool.org nick=seedpool
05:48:49 DBG (cross-seed) for release: [5DAFE728] rejections: (resolution not matching. got: want: [1080p 720p 2160p]) method=CheckFilter module=filter
05:48:49 DBG filter cross-seed rejected release: resolution not matching. got: want: [1080p 720p 2160p] filter=cross-seed indexer=seedpool module=release release=[5DAFE728]
05:48:49 DBG (All Movies and TV ) for release: [5DAFE728] rejections: (resolution not matching. got: want: [2160p 1080p 720p]) method=CheckFilter module=filter
05:48:49 DBG filter All Movies and TV rejected release: resolution not matching. got: want: [2160p 1080p 720p] filter="All Movies and TV " indexer=seedpool module=release release=[5DAFE728] 
```

I have attached raw JSON logs as well here. These logs also include the same release showing up on a public trackers where it originates. So in total it goes through 4 indexers, the first 3 match it correctly, but the last one (seedpool) does not.
[autobrr.txt](https://github.com/user-attachments/files/17266995/autobrr.txt)

**Desktop (please complete the following information):**
 - OS: Docker (LInux)

 
**Additional context**
the logs i shared are just the first one that i've been able to catch live, but it has been happening with multiple releases from seedpool. I know its a relatively new indexer addition, so I figure there must be a bug in the announce pattern matching for it specifically, as the other trackers seem to handle identical release titles correctly.

**Comment by Bobble5008** [comment]
This was addressed internally. GitHub had shadowbanned my account :(
