### ISSUE TITLE
qBittorrent 5.0.0 - "Add paused" not working

### ISSUE THREAD

**Issue by Icescreamlol** [autobrr/autobrr#1759]
**Version**
v1.47.0 together with qBittorrent 5.0.0

**Describe the bug**
Filters with "Add paused" checked are not being added as paused to qBittorrent 5.0.0 

**To Reproduce**
Filters -> Edit Filter -> Actions -> Rules -> Add Paused (Add torrent as paused)

**Expected behavior**
Expect torrents to be added as paused.

**Comment by zze0s** [comment]
Hi! qBittorrent 5.0.0 did some breaking changes to the APIs which we need to update to support.

A fix for this is in the works and should be available soon.
