### ISSUE TITLE
DigitalCore: new iRC-announce with newly added genre-tags

### ISSUE THREAD

**Issue by DigitGram** [autobrr/autobrr#1786]
**Version**
v1.48.0 (pr-1780)

**Describe the bug**
irc-announce regarding "tags" is broken due changes (they added genre-tags)

**To Reproduce**
see for further details: https://github.com/autobrr/autobrr/discussions/1778

**possible solution**
```
        pattern: 'NEW TORRENT in (.+) :: (.+) :: (https:\/\/.+\/).+\/([0-9a-zA-Z]+)(?: :: Tags: )?(?:\[([0-9a-zA-Z ,\-&]+)\])?(?: :: Genre: )?(?:\[([0-9a-zA-Z ,\-&]+)\])?'
        vars:
          - category
          - torrentName
          - baseUrl
          - torrentId
          - releaseTags
          - tags
```
Working fine so far.

**Comment by DigitGram** [comment]
Two suggestions for https://github.com/autobrr/autobrr/pull/1790:
1. **switch "releaseTags" with "tags"**
so `Genre: [Drama, Comedy]` belongs to tags then, and `Tags: [p2p,unrar]` to releaseTags.
Would make imho more sense?

2. **add two additional tests** (more failsafe)
IRC announce has 4 possible messages:
- no tags, no genre
- tags only
- genre only
- tags first, then genre

**Comment by s0up4200** [comment]
Added a 4th test and made sure genres are considered `tags` while e.g. `p2p,unrar` are considered `releaseTags`.
