### ISSUE TITLE
TorrentLeech download URLs result in 500 errors

### ISSUE THREAD

**Issue by jacobslusser** [autobrr/autobrr#1789]
**Version**
1.48.0

**Describe the bug**
Logs show 500 errors attempting to download .torrent files from TorrentLeech (TL). 

**To Reproduce**
1. Use the TorrentLeech indexer
2. Logs will report 500 errors 

**Expected behavior**
Torrent files will be downloaded without errors.

**Additional context**
Assuming the URL displayed in the logs are accurate, I noticed that the period characters are being replaced with plus characters and this is a problem. For example, the URL found in the logs looks like this: `https://www.torrentleech.org/rss/download/feed/key/Movie+1999+1080p+AMZN+WEB-DL+DDP+2+0+H+264.torrent`, however, if you look manually at the TorrentLeech RSS feed, the URLs will look like this: `https://www.torrentleech.org/rss/download/feed/key/Movie.1999.1080p.AMZN.WEB-DL.DDP.2.0.H.264.torrent`. Is Autobrr replacing the period characters with plus characters?

I've tested this assumption by using the URLs found in the logs (containing pluses) directly in the browser and confirm that a 500 error is the result. I've also confirmed that using the URL found in the raw RSS feed (containing periods) works as expected.

**Comment by zze0s** [comment]
Hi! This has been working for years and + is a valid character for url encoding. You likely have the wrong indexer key, or you're hitting cloudflare which was turned up lately.

Make sure you are using `rsskey` and not `passkey` or `irckey`.

If you're still having issues try one of the alternative domains.

**Comment by jacobslusser** [comment]
Plus is a valid URL encoding of a space character, not a period. Changing a period to a plus is not the same thing in a URL.

**Comment by zze0s** [comment]
They do not announce releases with the dots in them so we replace space with a + for url encoding and their webserver handles the rest.

Do you have any specific IDs that I can look for you had issues with?

Try add in a new incognito window so you don't have cookies etc that will let through invalid creds on a url.

**Comment by zze0s** [comment]
Expanding on this, the last part of the url is just the filename it downloads as. You can name it file1.torrent if you want and as long as torrentId and RSS key is valid it will download that without issues.

@jacobslusser any updates on your end?

**Comment by jacobslusser** [comment]
@zze0s good morning! Thanks for looking at this. I captured these following logs last night which made me believe this was a pattern. I have not seen this issue since, so don't know if it was a one-time-thing.

```
21:35:20 ERR release.Process: error processing filters for indexer: TorrentLeech error="could not download torrent file for release: 9-1-1 S08E05 1080p WEB H264-LAZYCUNTS : All attempts fail:\n#1: server error (500) encountered while downloading torrent (9-1-1 S08E05 1080p WEB H264-LAZYCUNTS ) file (https://www.torrentleech.org/rss/download/REDACTED/REDACTED/9-1-1+S08E05+1080p+WEB+H264-LAZYCUNTS+.torrent) - check indexer keys for TorrentLeech\n#2: server error (500) encountered while downloading torrent (9-1-1 S08E05 1080p WEB H264-LAZYCUNTS ) file (https://www.torrentleech.org/rss/download/REDACTED/REDACTED/9-1-1+S08E05+1080p+WEB+H264-LAZYCUNTS+.torrent) - check indexer keys for TorrentLeech\n#3: server error (500) encountered while downloading torrent (9-1-1 S08E05 1080p WEB H264-LAZYCUNTS ) file (https://www.torrentleech.org/rss/download/REDACTED/REDACTED/9-1-1+S08E05+1080p+WEB+H264-LAZYCUNTS+.torrent) - check indexer keys for TorrentLeech"= module=release stack=[{"func":"(*DownloadService).downloadTorrentFile.retryableRequest.func2","line":"222","source":"download_service.go"},{"func":"Do.func1","line":"116","source":"retry.go"},{"func":"DoWithData[...]","line":"180","source":"retry.go"},{"func":"Do","line":"119","source":"retry.go"},{"func":"(*DownloadService).downloadTorrentFile","line":"165","source":"download_service.go"},{"func":"(*DownloadService).DownloadRelease","line":"98","source":"download_service.go"},{"func":"(*service).AdditionalSizeCheck","line":"509","source":"service.go"},{"func":"(*service).CheckFilter","line":"437","source":"service.go"},{"func":"(*service).processFilters","line":"202","source":"service.go"},{"func":"(*service).Process","line":"177","source":"service.go"},{"func":"goexit","line":"1700","source":"asm_amd64.s"}]
```

```
21:38:04 ERR http call encountered error error="server error (500) encountered while downloading torrent (Cyborg 1989 1080p AMZN WEB-DL DDP 2 0 H 264-PiRaTeS) file (https://www.torrentleech.org/rss/download/REDACTED/REDACTED/Cyborg+1989+1080p+AMZN+WEB-DL+DDP+2+0+H+264-PiRaTeS.torrent) - check indexer keys for TorrentLeech"= module=release-download stack=[{"func":"(*DownloadService).downloadTorrentFile.retryableRequest.func2","line":"222","source":"download_service.go"},{"func":"Do.func1","line":"116","source":"retry.go"},{"func":"DoWithData[...]","line":"180","source":"retry.go"},{"func":"Do","line":"119","source":"retry.go"},{"func":"(*DownloadService).downloadTorrentFile","line":"165","source":"download_service.go"},{"func":"(*DownloadService).DownloadRelease","line":"98","source":"download_service.go"},{"func":"(*service).AdditionalSizeCheck","line":"509","source":"service.go"},{"func":"(*service).CheckFilter","line":"437","source":"service.go"},{"func":"(*service).processFilters","line":"202","source":"service.go"},{"func":"(*service).Process","line":"177","source":"service.go"},{"func":"goexit","line":"1700","source":"asm_amd64.s"}]
```

Some additional info:
- When I try the URL in the logs manually in the browser with an authenticated session, I get a 500 from TorrentLeech (not Cloudflare as best I can tell)
- When I replace the '+' with '.', I can download the .torrent file

I would like to provide more information, but this information is somewhat transient and difficult to capture in the moment.

**Comment by zze0s** [comment]
@jacobslusser I am confident that you still have the wrong key in the indexer settings as RSS key. I tried this with both wget in a terminal and an incognito window and it works. `https://www.domain.org/rss/download/241373297/RSSKEY/cyborrg.torrent`

The last part is simply what the downloaded .torrent file is named and the url above would download it as `cyborrg.torrent`. The spaces/plus/dots does not matter here for this indexer.

I also tried with a bad RSS key and got that same Error Code 705. 

So, please make sure you are using **RSS KEY** and NOT PASSKEY or IRC KEY.

**Comment by jacobslusser** [comment]
Ok, thanks for looking into this. As I said before, I haven't had the problem since. After having issues I completely deleted and readded the indexer, and haven't had a problem since, so it is entirely possible that it was incorrect the first time. Appreciate you taking the time.
