### ISSUE TITLE
Tags-based filter not working with MTV tracker.

### ISSUE THREAD

**Issue by sklm** [autobrr/autobrr#1796]
**Version**
1.48.0

**Describe the bug**
Filter by tags doesn't work with MoreThanTv announcements. Example from the debug logs (redacted):

{"level":"debug","module":"filter","method":"CheckFilter","time":"\<redacted\>","message":"(\<redacted\>) for release: Halloween.1978.BluRay.1080p.DDP.5.1.x264-hallowed rejections: ([**match tags: ALL**] **not matching**: got [h264 hd ddp.audio 1080p bluray internal.group.release **internal.release** hallowed.release subtitles **hd.movie**] want: **internal.release**, **hd.movie**)"}

**To Reproduce**
Filter - Advanced - Tags:
match tags: internal.release, hd.movie
match logic: all

**Expected behavior**
The filter should match the announcement above, because the announcement includes both required tags `internal.release` and `hd.movie`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: latest

**Additional context**
This used to work up until recently.

**Comment by zze0s** [comment]
Hi! Thanks for the detailed report. It might be as simple as the extra space after the comma in the tags field. Remove it and see if it works.

If not we'll start digging.
