### ISSUE TITLE
Deleting and readding an indexer creates multiple Feeds

### ISSUE THREAD

**Issue by mat926** [autobrr/autobrr#1800]
**Version**
1.48.0

**Describe the bug**
When I delete an indexer that has RSS feeds and later re-add it , it would cause multiple feeds to be created. Those feeds are the ones that were previously deleted plus the new one that was added.

**To Reproduce**
1. Go to Indexers
2. Add a Generic RSS 
3. Put anything in the RSS URL (test) and save
4. Go to feeds (Generic RSS should be there)
5. Go back to Indexers and delete Generic RSS
6. Verify in Feeds it was removed
7. In Indexers, re-add Generic RSS again, use the same URL from 3.
8. Go to Feeds again, now 2 Generic RSS feeds are created. 

**Expected behavior**
Deleting an indexer should automatically delete all the associated RSS with it and only create 1 feed

**Screenshots**
![Image](https://github.com/user-attachments/assets/022b0d45-2ba9-44ce-ade9-f8f24f7078f4)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Brave
 - Version 1.71.121

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by zze0s** [comment]
Hi! Does it happen if you name it something else than just leaving the default?
