### ISSUE TITLE
`{{ .TorrentName }}` titles with `"` breaks json payload

### ISSUE THREAD

**Issue by ShanaryS** [autobrr/autobrr#1802]
**Version**
v1.48.0

**Describe the bug**
Whenever titles contain `"`, it breaks the json formatting since it's not escaped. Using `{{ .TorrentName | js }}` works, but then breaks `'` which is far more common.

e.g. `"name": "A "Title" with Quotes"`

**To Reproduce**
Set payload in External tab for a Filter and receive an announce with `"` in the title.
```json
{
  "name": "{{ .TorrentName }}"
}
```

**Expected behavior**
`{{ .TorrentName }}` should escape `"` in titles, so they appear as `"name": "A \"Title\" with Quotes"`. I think this solution is best as JSON requires `"` to use for syntax.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Additional context**
I'm not sure why using `| js` breaks `'`. It escapes doubles quotes properly but it seems to mess up formatting when single quotes are present.

**Comment by zakkarry** [comment]
Is there an issue on the library already? Would you just be making something like `| b64` instead of `| js`?

**Comment by zze0s** [comment]
Did some testing and this _should work_. Notice the lack of double quotes around the value, those are added by the text func from sprig helpers.

```json
{
  "name": {{ toRawJson .TorrentName }}
}
```

**Comment by ShanaryS** [comment]
To `toRawJson` seems to be the best solution. Could you update https://autobrr.com/3rd-party-tools/cross-seed#cross-seed-filter to:
```json
{
  "name": {{ toRawJson .TorrentName }},
  "guid": "{{ .TorrentUrl }}",
  "link": "{{ .TorrentUrl }}",
  "tracker": {{ toRawJson .IndexerName }}
}
```

**Comment by nuxencs** [comment]
> The stance is js != json

pretty sure the js means javascript here, but not 100% sure

> "name": {{ toRawJson .TorrentName }}

good to know, that would be useful for my use case in seasonpackarr as well. this also deals with `'` breaking the decoding with `| js` correct?

**Comment by zze0s** [comment]
Yep those should be handled correctly with this. I'll get the docs updated. Does `tracker` really need that @ShanaryS ? 🤔

**Comment by zakkarry** [comment]
> Yep those should be handled correctly with this. I'll get the docs updated. Does `tracker` really need that [@ShanaryS](https://github.com/ShanaryS) ? 🤔

I guess he's assuming because the user can change that to whatever they want, it could be anything. Although I think it's relatively low-risk to leave it as it was.

**Comment by ShanaryS** [comment]
`"` is allowed in the tracker name so I added it to be safe. The URLs don't need it since it's encoded.
