### ISSUE TITLE
Redacted.ch tracker integration not working after domain change to redacted.sh

### ISSUE THREAD

**Issue by orbitalfitness** [autobrr/autobrr#1833]
**Version**
1.5

**Describe the bug**
Redacted.ch is now at redacted.sh which changes the base url in the tracker integration I’m not sure if this breaks the integration but I’m getting errors. It was down for a bit but is now back online and Autobrr might need an integration fix for this tracker.

**To Reproduce**
1. Go to 'edit indexer’
2. Click on previously working ‘redacted.ch'
3. Scroll down to base url and edit to 'redacted.sh' then test api with previously working integration all setup 
`HTTP request to 'api/indexer/1/api/test' failed with code 500 (test api error: test api error: could not make request: &{Method:GET URL:https://redacted.ch/ajax.php?action=index Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Authorization:[redactedAuthCode] User-Agent:[autobrr]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:redacted.ch Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> Pattern: ctx:0xc001b95560 pat:<nil> matches:[] otherValues:map[]}: Get "https://redacted.ch/ajax.php?action=index": dial tcp: lookup redacted.ch on [::1]:53: no such host) `

**Expected behavior**
Previously this worked. Redacted move domains and the api prob did too.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome 
 - Version latest

**Additional context**
Thanks for investigating!

**Comment by martylukyy** [comment]
Fix is already being worked on:
https://github.com/autobrr/autobrr/pull/1830

**Comment by flowerornament** [comment]
It looks like this hasn't made it into a release yet, but just want to confirm
