### ISSUE TITLE
Failed to create database backup

### ISSUE THREAD

**Issue by ibrahimmdfarid** [autobrr/autobrr#1842]
**Version**
The autobrr version you're running. If you run something other than latest, please update before reporting issues.

```1.51.0_windows_x86_64```

**Describe the bug**

- autobrr is attempting to create a database backup file, "autobrr.db_sv63_2024-11-25T01:14:29.backup" however Windows does not accept colons ```:``` in filenames

**To Reproduce**

1) Using a PC running Windows OS, grab the "autobrr_1.51.0_windows_x86_64.zip" file and extract it.
2) Copy over the 2 .exe files to your existing autobrr directory (if updating)
3) Now run the autobrr.exe file using CMD
4) You should get the error that the database backup file could not be created. Example below:

```
{"level":"info","time":"2024-11-25T09:14:29+08:00","message":"maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined"}
{"level":"info","module":"database","type":"sqlite","time":"2024-11-25T09:14:29+08:00","message":"Beginning database schema upgrade from version 63 to version: 65"}
{"level":"info","module":"database","type":"sqlite","time":"2024-11-25T09:14:29+08:00","message":"Database integrity check.."}
{"level":"info","module":"database","type":"sqlite","time":"2024-11-25T09:14:29+08:00","message":"Database integrity check OK!"}
{"level":"info","module":"database","type":"sqlite","time":"2024-11-25T09:14:29+08:00","message":"Creating database backup: autobrr.db_sv63_2024-11-25T01:14:29.backup"}
{"level":"fatal","module":"database","type":"sqlite","stack":[{"func":"(*DB).backupSQLiteDatabase","line":"298","source":"sqlite.go"},{"func":"(*DB).migrateSQLite","line":"136","source":"sqlite.go"},{"func":"(*DB).openSQLite","line":"80","source":"sqlite.go"},{"func":"(*DB).Open","line":"78","source":"database.go"},{"func":"main","line":"97","source":"main.go"},{"func":"main","line":"272","source":"proc.go"},{"func":"goexit","line":"1700","source":"asm_amd64.s"}],"error":"failed to create database backup: failed to backup database: unable to open database file: unable to open database: autobrr.db_sv63_2024-11-25T01:14:29.backup (14)","time":"2024-11-25T09:14:29+08:00","message":"could not migrate db"}
```

**Expected behavior**

- autobrr should successfully run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10 Home**
 - Version [e.g. 22] **10.0.19045 Build 19045**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bulletproof2k** [comment]
The same problem, I had to roll back to the previous version.

**Comment by xerta555** [comment]
Hi

Exactly same issue on my side
![Image](https://github.com/user-attachments/assets/36d0efa5-538b-406f-aff3-5ccd687ed14c)

Also back to the previous version.

**Comment by s0up4200** [comment]
This will most likely be fixed asap today.

**Comment by jkaberg** [comment]
I'm still seeing this running latest v1.52.0 (docker), coming from 1.50.0. Doing an intermittent upgrade to 1.51.0 didn't help either.

```
autobrr-1  | {"level":"info","module":"database","type":"sqlite","time":"2024-12-04T23:40:22+01:00","message":"Beginning database schema upgrade from version 63 to version: 65"}
autobrr-1  | {"level":"info","module":"database","type":"sqlite","time":"2024-12-04T23:40:22+01:00","message":"Database integrity check.."}
autobrr-1  | {"level":"fatal","module":"database","type":"sqlite","stack":[{"func":"(*DB).databaseConsistencyCheckSQLite","line":"278","source":"sqlite.go"},{"func":"(*DB).migrateSQLite","line":"132","source":"sqlite.go"},{"func":"(*DB).openSQLite","line":"80","source":"sqlite.go"},{"func":"(*DB).Open","line":"78","source":"database.go"},{"func":"main","line":"97","source":"main.go"},{"func":"main","line":"272","source":"proc.go"},{"func":"goexit","line":"1700","source":"asm_amd64.s"}],"error":"database image malformed: backup integrity check failed: \"wrong # of entries in index release_torrent_name_index\"","time":"2024-12-04T23:40:23+01:00","message":"could not migrate db"}
```

**Comment by jkaberg** [comment]
> > I'm still seeing this running latest `ghcr.io/autobrr/autobrr:v1.52.0`, coming from 1.50.0. Doing an intermittent upgrade to 1.51.0 didn't help either. Host is running Ubuntu 22.04.
> > ```
> > autobrr-1  | {"level":"info","module":"database","type":"sqlite","time":"2024-12-04T23:40:22+01:00","message":"Beginning database schema upgrade from version 63 to version: 65"}
> > autobrr-1  | {"level":"info","module":"database","type":"sqlite","time":"2024-12-04T23:40:22+01:00","message":"Database integrity check.."}
> > autobrr-1  | {"level":"fatal","module":"database","type":"sqlite","stack":[{"func":"(*DB).databaseConsistencyCheckSQLite","line":"278","source":"sqlite.go"},{"func":"(*DB).migrateSQLite","line":"132","source":"sqlite.go"},{"func":"(*DB).openSQLite","line":"80","source":"sqlite.go"},{"func":"(*DB).Open","line":"78","source":"database.go"},{"func":"main","line":"97","source":"main.go"},{"func":"main","line":"272","source":"proc.go"},{"func":"goexit","line":"1700","source":"asm_amd64.s"}],"error":"database image malformed: backup integrity check failed: \"wrong # of entries in index release_torrent_name_index\"","time":"2024-12-04T23:40:23+01:00","message":"could not migrate db"}
> > ```
> 
> Your database is corrupt unfortunately, do you have a backup?

I do, however I made Claude.ai fix it:

First checked where it was "corrupted"
```
# sqlite3 autobrr.db_corrupted "PRAGMA integrity_check;"
row 909 missing from index release_torrent_name_index
row 909 missing from index release_timestamp_index
row 909 missing from index release_indexer_index
row 909 missing from index release_filter_id_index
wrong # of entries in index release_torrent_name_index
wrong # of entries in index release_timestamp_index
wrong # of entries in index release_filter_id_index
#
```

Feeded that into Claude which gave the solution bellow:

`cp autobrr.db autobrr.db`

repair.sql
```
-- First handle journaling mode outside of any transaction
PRAGMA journal_mode = DELETE;

-- Begin the main repair process
BEGIN TRANSACTION;

-- Disable foreign key constraints temporarily
PRAGMA foreign_keys=OFF;

-- Drop the corrupted indexes
DROP INDEX IF EXISTS release_torrent_name_index;
DROP INDEX IF EXISTS release_timestamp_index;
DROP INDEX IF EXISTS release_indexer_index;
DROP INDEX IF EXISTS release_filter_id_index;

-- Verify the release table structure and data
CREATE TABLE IF NOT EXISTS release_backup AS 
SELECT * FROM release WHERE rowid != 909;

-- Drop the original table
DROP TABLE release;

-- Recreate the release table with the backup data
CREATE TABLE release AS 
SELECT * FROM release_backup;

-- Drop the backup table
DROP TABLE release_backup;

-- Recreate all the indexes
CREATE INDEX release_torrent_name_index ON release(torrent_name);
CREATE INDEX release_timestamp_index ON release(timestamp);
CREATE INDEX release_indexer_index ON release(indexer);
CREATE INDEX release_filter_id_index ON release(filter_id);

-- Analyze the database to update statistics
ANALYZE;

-- Re-enable foreign key constraints
PRAGMA foreign_keys=ON;

-- Verify integrity
PRAGMA integrity_check;

-- Commit the transaction
COMMIT;

-- Vacuum the database to reclaim space and defragment
VACUUM;

-- Switch back to WAL journal mode
PRAGMA journal_mode = WAL;
```

`sqlite3 autobrr.db < repair.sql`

```
# sqlite3 autobrr.db "PRAGMA integrity_check;"
ok
```

And I was then able to upgrade to v1.52 without issues

**Comment by zze0s** [comment]
Nicely done. Did you at some point run a PR tag/binary by chance? If so then that might be why it was missing indexes.

**Comment by jkaberg** [comment]
> Nicely done. Did you at some point run a PR tag/binary by chance? If so then that might be why it was missing indexes.

Always YOLO aka latest 😆
