### ISSUE TITLE
Can't connect to IRC BeyondHD with TLS

### ISSUE THREAD

**Issue by newkind** [autobrr/autobrr#1858]
**Version**
1.52.0 (Docker)

**Describe the bug**
BeyondHD started to enforce the TLS connection on port 6697, but since that change I cannot connect to the IRC. I have updated my IRC connection configuration - changed the port, enabled TLS but my connection still gets refused. Its not my network because I can connect fine from my desktop IRC client.

I have enabled Debug logs in the autobrr but all I can see is this:

```
08:36:45 DBG Disconnecting... module=irc network=irc.beyond-hd.me
08:36:45 DBG stopped network: irc.beyond-hd.me module=irc
08:36:45 DBG starting network: BeyondHD-IRC module=irc
08:36:45 DBG connect attempt 0 module=irc network=irc.beyond-hd.me
08:36:45 ERR client encountered connection error error="Disconnected by server"= module=irc network=irc.beyond-hd.me
08:37:00 DBG connect attempt 1 module=irc network=irc.beyond-hd.me
08:37:01 ERR client encountered connection error error="Disconnected by server"= module=irc network=irc.beyond-hd.me
08:37:01 DBG BeyondHD-IRC connect attempt 1 module=irc network=irc.beyond-hd.me
08:37:31 DBG connect attempt 2 module=irc network=irc.beyond-hd.me
08:37:31 ERR client encountered connection error error="Disconnected by server"= module=irc network=irc.beyond-hd.me
08:37:31 DBG BeyondHD-IRC connect attempt 2 module=irc network=irc.beyond-hd.me 
```

**To Reproduce**
1. Modify the IRC connection port to 6697 and enable TLS
2. Restart the IRC network connection

**Expected behavior**
IRC should connect properly to the server.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d98b6348-a3b1-4123-bede-eb428c837541)

![Image](https://github.com/user-attachments/assets/10bfdca5-9ed8-4d22-aa8b-92e680ae2d1b)

**Comment by zze0s** [comment]
Hi! The recently moved the irc server and lots of users reports that NickServ got reset. Check if you need to reregister with nickserv and group your bot. If you change log level to Trace in settings and then hit restart on the irc network you'll see more info about the connection. Look for something like `SASL authentication failed` which indicates the nickserv registration isn't valid anymore.

**Comment by newkind** [comment]
Awesome! You were right, setting the LOG to TRACE indeed showed the SASL authentication issue and re-registering the nick on NickServ worked like a charm!

Thank you!
