### ISSUE TITLE
Exec Error on External Filter (ARM64)

### ISSUE THREAD

**Issue by desi76** [autobrr/autobrr#1865]
** Autobrr Version**
1.52.0

**Describe the bug**
I'm running **autobrr** on Docker, on Ubuntu Linux, on an ARM64 SBC, using a shell script in an external filter to calculate free space and fail the filter if free space < 100 GB. The external filter is failing with the logged error:

`(Television) external filter check error error="error executing external command: fork/exec /config/freespace.sh: exec format error"= method=CheckFilter module=filter stack=[{"func":"(*service).RunExternalFilters","line":"564","source":"service.go"},{"func":"(*service).CheckFilter","line":"451","source":"service.go"},{"func":"(*service).processFilters","line":"205","source":"service.go"},{"func":"(*service).Process","line":"182","source":"service.go"},{"func":"goexit","line":"1223","source":"asm_arm64.s"}] `

The script is set as executable and I've set CHOWN to assign the script with the container's PUID / PGID.  I can run the shell script successfully when logged into autobrr's container.

**To Reproduce**
Run:
`/config/freespace.sh` as external filter.

Result (when executed manually, in container):
`More than 100 GB of storage space is available.
Free Space: 355.5G GB`

**Expected behavior**
Expecting successful execution of shell script and filter.

**Screenshots**
![Image](https://github.com/user-attachments/assets/cd4ae84e-1c51-4843-97cb-5f43f343720c)

**Desktop (please complete the following information):**
 - OS: `Linux SHADE 5.4.180 #1.5 SMP PREEMPT Tue Apr 25 16:40:09 CST 2023 aarch64 aarch64 aarch64 GNU/Linux.    Ubuntu 22.04.5 LTS`
 - Docker: `27.3.1, build ce12230`

**Additional context**
Shell script:

```
set -e

reqSpace=10000000 # 100GB
SPACE=$(df "/Media" | awk 'END{print $4}')
if [ "$SPACE" -le $reqSpace ]
then
  SPACE=$(df -kh . | tail -n1 | awk '{print $4}')
  echo "Less than 100 GB of storage space is available."
  echo "Free Space: $SPACE GB"
  exit 1
fi

if [ "$SPACE" -gt $reqSpace ]
then
  SPACE=$(df -kh . | tail -n1 | awk '{print $4}')
  echo "More than 100 GB of storage space is available."
  echo "Free Space: $SPACE GB"
  exit 0
fi

```

**Docker Compose:**

autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    network_mode: bridge
    restart: unless-stopped
    # logging:
      # driver: json-file
      # options:
        # max-file: ${DOCKERLOGGING_MAXFILE}
        # max-size: ${DOCKERLOGGING_MAXSIZE}
    # user: 1000:1000
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - AUTOBRR__LOG_PATH="/log"
    - AUTOBRR__LOG_MAX_SIZE=64 # string/int without MB
    - AUTOBRR__LOG_MAX_BACKUPS=7
    - AUTOBRR__LOG_LEVEL=INFO
    volumes:
    - ${CONF}/autobrr/:/config
    - ${LOGS}/autobrr/:/log
    - ${MEDIA}:/Media
    ports:
    - 7474:7474

**Comment by zze0s** [comment]
Hi! Did you skip the header of the script here or is it missing? The container only has sh, no full bash so you need to have it as 

```bash
#!/bin/sh

set -e

reqSpace=10000000 # 100GB
SPACE=$(df "/Media" | awk 'END{print $4}')
if [ "$SPACE" -le $reqSpace ]
then
  SPACE=$(df -kh . | tail -n1 | awk '{print $4}')
  echo "Less than 100 GB of storage space is available."
  echo "Free Space: $SPACE GB"
  exit 1
fi

if [ "$SPACE" -gt $reqSpace ]
then
  SPACE=$(df -kh . | tail -n1 | awk '{print $4}')
  echo "More than 100 GB of storage space is available."
  echo "Free Space: $SPACE GB"
  exit 0
fi
```

Also make sure it has executable permissions `chmod +x freespace.sh`

**Comment by desi76** [comment]
> Hi! Did you skip the header of the script here or is it missing? The container only has sh, no full bash so you need to have it as 
> 
> ```bash
> #!/bin/sh
> 
> set -e
> 
> reqSpace=10000000 # 100GB
> SPACE=$(df "/Media" | awk 'END{print $4}')
> if [ "$SPACE" -le $reqSpace ]
> then
>   SPACE=$(df -kh . | tail -n1 | awk '{print $4}')
>   echo "Less than 100 GB of storage space is available."
>   echo "Free Space: $SPACE GB"
>   exit 1
> fi
> 
> if [ "$SPACE" -gt $reqSpace ]
> then
>   SPACE=$(df -kh . | tail -n1 | awk '{print $4}')
>   echo "More than 100 GB of storage space is available."
>   echo "Free Space: $SPACE GB"
>   exit 0
> fi
> ```
> 
> Also make sure it has executable permissions `chmod +x freespace.sh`

It looks like I missed the shell script header. I'll update it and advise.

**Comment by zze0s** [comment]
@desi76 How did it go?

**Comment by desi76** [comment]
For unrelated reasons, my SBC suffered a catastrophic failure.  I think Docker updated and now it won't start.  I'll update you when I can.

**Comment by desi76** [comment]
> [@desi76](https://github.com/desi76) How did it go?

@zze0s Including the shell script header resolved the error.  Thank you.
