### ISSUE TITLE
Error: HTTP request to 'api/release/recent' failed with code 500 (error scanning row: sql: Scan error on column index 33, name "hybrid": sql/driver: couldn't convert <nil> (<nil>) into type bool)

### ISSUE THREAD

**Issue by rand0mdud3** [autobrr/autobrr#1893]
**Version**
1.56

**Describe the bug**
After upgrade from 1.54, starting seeing this error when getting on the main page. I am using postgres for DB.

![Image](https://github.com/user-attachments/assets/e042fa08-afc4-4589-bf3c-dbae3eb37f07)

**Comment by rand0mdud3** [comment]
Don't think I ever used the develop tag.

**Comment by vember31** [comment]
Just noting that the way this issue manifested for me was that the dashboard would not load - the loading circle would just spin.  Running `UPDATE "release" set hybrid = false;` as a query on the autobrr database in postgres resolved the issue for me too, and the dashboard was immediately working again.

Thanks!
