### ISSUE TITLE
Can't edit filter

### ISSUE THREAD

**Issue by F4n4t** [autobrr/autobrr#196]
Hi,
since the latest build i can't edit any Filter.
I retrieve the Error: ERR filter: 0 : error scanning data to struct error="sql: no rows in result set"

**Comment by ludviglundgren** [comment]
Latest build as in develop from just a few minutes ago, or some other?

Can you change to `logLevel = "TRACE"` in the config and restart and try again and post those logs?

We have a [Discord server](https://discord.gg/WQ2eUycxyT) for a quicker feedback loop if you use Discord.

**Comment by F4n4t** [comment]
Since the commit where you switched back to modernc sqlite. 3c323004c0a5a4fafc7625dfb55515fb5cae9a65
I setup everything and tried to add a Filter but the Page was empty.

`2022/03/22 18:58:10 http: panic serving 127.0.0.1:21932: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
net/http.(*conn).serve.func1()
	/usr/lib/go/src/net/http/server.go:1802 +0xb9
panic({0xb59260, 0x14f3aa0})
	/usr/lib/go/src/runtime/panic.go:1047 +0x266
database/sql.(*Rows).close(0x0, {0x0, 0x0})
	/usr/lib/go/src/database/sql/sql.go:3267 +0x8e
database/sql.(*Rows).Close(0x7f037b23bb78)
	/usr/lib/go/src/database/sql/sql.go:3263 +0x1d
panic({0xb59260, 0x14f3aa0})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
database/sql.(*Rows).Next(0x0)
	/usr/lib/go/src/database/sql/sql.go:2944 +0x27
github.com/autobrr/autobrr/internal/database.(*ActionRepo).FindByFilterID(0xc000010540, {0x1028c00, 0xc0002b0a20}, 0xb4b780)
	/home/f4n4t/github/autobrr/internal/database/action.go:32 +0x188
github.com/autobrr/autobrr/internal/filter.(*service).FindByID(0xc0001b6bc0, {0x1028c00, 0xc0002b0a20}, 0x1)
	/home/f4n4t/github/autobrr/internal/filter/service.go:73 +0x7c
github.com/autobrr/autobrr/internal/http.filterHandler.getByID({{}, {0x7f035041f0e8, 0xc0001b6bc0}}, {0x1023a48, 0xc00026a1c0}, 0x8)
	/home/f4n4t/github/autobrr/internal/http/filter.go:65 +0x9b
net/http.HandlerFunc.ServeHTTP(0xb55ce0, {0x1023a48, 0xc00026a1c0}, 0xc0007ac90a)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010e840, {0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc00069f628, {0x1023a48, 0xc00026a1c0}, 0x450274)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010e840, {0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e
github.com/go-chi/chi.(*Mux).Mount.func1({0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c
net/http.HandlerFunc.ServeHTTP(0xb55ce0, {0x1023a48, 0xc00026a1c0}, 0xc0007ac900)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010e6c0, {0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc00069f7b8, {0x1023a48, 0xc00026a1c0}, 0x450274)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010e6c0, {0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e
github.com/go-chi/chi.(*Mux).Mount.func1({0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c
net/http.HandlerFunc.ServeHTTP(0xb541e0, {0x1023a48, 0xc00026a1c0}, 0xc)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/autobrr/autobrr/internal/http.Server.IsAuthenticated.func1({0x1023a48, 0xc00026a1c0}, 0x1)
	/home/f4n4t/github/autobrr/internal/http/middleware.go:15 +0xc7
net/http.HandlerFunc.ServeHTTP(0xc000201e30, {0x1023a48, 0xc00026a1c0}, 0xc0001842e8)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xb55ce0, {0x1023a48, 0xc00026a1c0}, 0xc0005c8304)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/chain.go:31 +0x2c
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010e5a0, {0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc0000e62c0, {0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/rs/cors.(*Cors).Handler.func1({0x1023a48, 0xc00026a1c0}, 0xc00012a900)
	/home/f4n4t/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x1028b58, {0x1023a48, 0xc00026a1c0}, 0x14f3770)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010e5a0, {0x1023a48, 0xc00026a1c0}, 0xc00012a800)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:87 +0x442
net/http.serverHandler.ServeHTTP({0xc000021170}, {0x1023a48, 0xc00026a1c0}, 0xc00012a800)
	/usr/lib/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000180000, {0x1028c00, 0xc000201f80})
	/usr/lib/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:3034 +0x4e8
2022/03/22 18:58:10 http: panic serving 127.0.0.1:21936: runtime error: invalid memory address or nil pointer dereference
goroutine 86 [running]:
net/http.(*conn).serve.func1()
	/usr/lib/go/src/net/http/server.go:1802 +0xb9
panic({0xb59260, 0x14f3aa0})
	/usr/lib/go/src/runtime/panic.go:1047 +0x266
database/sql.(*Rows).close(0x0, {0x0, 0x0})
	/usr/lib/go/src/database/sql/sql.go:3267 +0x8e
database/sql.(*Rows).Close(0x7f037b23bb78)
	/usr/lib/go/src/database/sql/sql.go:3263 +0x1d
panic({0xb59260, 0x14f3aa0})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
database/sql.(*Rows).Next(0x0)
	/usr/lib/go/src/database/sql/sql.go:2944 +0x27
github.com/autobrr/autobrr/internal/database.(*ActionRepo).FindByFilterID(0xc000010540, {0x1028c00, 0xc0002b11a0}, 0xb4b780)
	/home/f4n4t/github/autobrr/internal/database/action.go:32 +0x188
github.com/autobrr/autobrr/internal/filter.(*service).FindByID(0xc0001b6bc0, {0x1028c00, 0xc0002b11a0}, 0xc0003fd880)
	/home/f4n4t/github/autobrr/internal/filter/service.go:73 +0x7c
github.com/autobrr/autobrr/internal/http.filterHandler.getByID({{}, {0x7f035041f0e8, 0xc0001b6bc0}}, {0x1023a48, 0xc00026a2a0}, 0x8)
	/home/f4n4t/github/autobrr/internal/http/filter.go:65 +0x9b
net/http.HandlerFunc.ServeHTTP(0xb55ce0, {0x1023a48, 0xc00026a2a0}, 0xc0007ad2da)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010e840, {0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc00069f628, {0x1023a48, 0xc00026a2a0}, 0x450274)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010e840, {0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e
github.com/go-chi/chi.(*Mux).Mount.func1({0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c
net/http.HandlerFunc.ServeHTTP(0xb55ce0, {0x1023a48, 0xc00026a2a0}, 0xc0007ad2d0)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010e6c0, {0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc00069f7b8, {0x1023a48, 0xc00026a2a0}, 0x450274)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010e6c0, {0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e
github.com/go-chi/chi.(*Mux).Mount.func1({0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c
net/http.HandlerFunc.ServeHTTP(0xb541e0, {0x1023a48, 0xc00026a2a0}, 0xc)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/autobrr/autobrr/internal/http.Server.IsAuthenticated.func1({0x1023a48, 0xc00026a2a0}, 0x6)
	/home/f4n4t/github/autobrr/internal/http/middleware.go:15 +0xc7
net/http.HandlerFunc.ServeHTTP(0xc000201e30, {0x1023a48, 0xc00026a2a0}, 0xc00012f258)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xb55ce0, {0x1023a48, 0xc00026a2a0}, 0xc0005c8684)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/chain.go:31 +0x2c
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00010e5a0, {0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9
net/http.HandlerFunc.ServeHTTP(0xc0000e62c0, {0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/rs/cors.(*Cors).Handler.func1({0x1023a48, 0xc00026a2a0}, 0xc00012ac00)
	/home/f4n4t/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x1028b58, {0x1023a48, 0xc00026a2a0}, 0x14f3770)
	/usr/lib/go/src/net/http/server.go:2047 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00010e5a0, {0x1023a48, 0xc00026a2a0}, 0xc00012aa00)
	/home/f4n4t/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:87 +0x442
net/http.serverHandler.ServeHTTP({0xc0002b1080}, {0x1023a48, 0xc00026a2a0}, 0xc00012aa00)
	/usr/lib/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000242140, {0x1028c00, 0xc000201f80})
	/usr/lib/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:3034 +0x4e8`

**Comment by ludviglundgren** [comment]
Try the latest stuff from today, a few fixes and think one related to that.

**Comment by ludviglundgren** [comment]
Resolved in #197
