### ISSUE TITLE
Supported download clients and actions

### ISSUE THREAD

**Issue by ludviglundgren** [autobrr/autobrr#2]
Supported actions and clients:

- [x] Test (Simple action to only log action)
- [x] Watch folder
- [x] qBittorrent
- [x] Exec Command (custom command and arguments) https://github.com/autobrr/autobrr/pull/7
- [x] Deluge (v1,v2) https://github.com/autobrr/autobrr/pull/12
- [x] Radarr https://github.com/autobrr/autobrr/pull/13
- [x] Sonarr https://github.com/autobrr/autobrr/pull/14
- [x] Lidarr https://github.com/autobrr/autobrr/pull/15

Planned:
- Open for ideas

**Comment by ludviglundgren** [comment]
Added support for exec action: https://github.com/autobrr/autobrr/pull/7

**Comment by rouggy** [comment]
Do you plan any rtorrent support ?
For the watch folder I did not find it in the drop down list of download clients.

Thanks

**Comment by rouggy** [comment]
Ok found in the filter, thanks

**Comment by ludviglundgren** [comment]
There's no plans to support rtorrent in an integrated way like qbittorrent, but watch folder is supported and works good enough.

**Comment by rouggy** [comment]
Watch folder is indeed good enough
Thanks
