### ISSUE TITLE
Feature Request: Option to set max-download

### ISSUE THREAD

**Issue by mkgeeky** [autobrr/autobrr#211]
A option to set max download on hourly, daily, weekly basis.
It can come handy for testing etc., or if you just want to download X amounts of torrents in the filter 
autodl-irssi have this, so hope this chould be added 💪

**Comment by ludviglundgren** [comment]
Hi. This is in the plans. There's an item in the [Project board](https://github.com/orgs/autobrr/projects/1/views/4) named `Scheduling X per Y` which isn't the most descriptive title but it's there :smile:
