### ISSUE TITLE
Feature request [action]: save a copy to local directory

### ISSUE THREAD

**Issue by ai4739** [autobrr/autobrr#220]
It would be pretty cool to have an action that saves the torrent file to a local directory ... I "catalog" all the torrents I DL, which I'm now going back on site and doing manually after autobrr grabs them, so it would be super cool to add an action for saving the torrents too :D

Cheers!

**Comment by KyleSanderson** [comment]
`Watch Dir` does this today.

**Comment by ai4739** [comment]
Actually ... will the watch dir action work in conjunction with a qbittorrent action?  I've had it running for about a day now, and torrents are not being copied.

The only other thing I can think of is maybe a trailing slash on my dir?

/path/to/watch/dir/ is currently how I have it...

**Comment by GregTroar** [comment]
Actually normally all torrents downloaded by autobrr should be in /tmp dir already isn't it ?

**Comment by ai4739** [comment]
There are a handful of files in /tmp ... they're all named `autobrr-999999999` (digits different ofc), and the files appear to be binary data (not torrents).

**Comment by GregTroar** [comment]
Ok I will test the double action with one being watch folder to see if I have same issue. If it does not work it is a bug as it should

**Comment by ludviglundgren** [comment]
> There are a handful of files in /tmp ... they're all named `autobrr-999999999` (digits different ofc), and the files appear to be binary data (not torrents).

Torrentfiles have a bit of binary data, but not everything. At the top you should be able to see some text that is readable. You can just add the extension `.torrent` and load it in a client to test.

**Comment by ai4739** [comment]
@GregTroar The copy does in fact work ... but it copies using the `autobrr-###` format, so it's not easy to see the torrent contents/names.  I guess I just need to let go of my desire to save the torrents, and accept what's made it into my clients :)

**Comment by gl0ryus** [comment]
In qbittorrent theres these options under Options > Downloads. Might be able to use that.
![image](https://user-images.githubusercontent.com/96798013/163213434-d2fe0ddd-eb2e-4a95-a6eb-333a598c159c.png)
