### ISSUE TITLE
Radarr/Sonarr Error

### ISSUE THREAD

**Issue by zecatz** [autobrr/autobrr#248]
Hey, thanks for this fantastic app. I'm having some trouble when I try to connect Sonarr and Radarr once set up in Autobrr. I installed this via Swizzin. Here's what I get from the log:

2022-04-15T14:20:21ZERROR radarr client request error : https://my.ip.address.here/radarr/api/v3/system/status
2022-04-15T14:20:21ZERROR radarr client get error
2022-04-15T14:20:21ZERROR radarr: connection test failed: https://my.ip.address.here/radarr

The link ending with api/v3/system/status does nothing when I paste it into my address bar. It gives a 401 error. Also, I have tried setting up username and pass for both as well.

**Comment by s0up4200** [comment]
Hey. I use autobrr through swizzin and I've added Radarr and Sonarr like this:

Radarr:
```
Host: http://localhost:7878/radarr
API: redacted
```
Sonarr:
```
Host: http://localhost:8989/sonarr
API: redacted
```

Obviously change the ports if they don't match your set up. No basic auth is needed. This should work for you as well!

**Comment by zecatz** [comment]
> Hey. I use autobrr through swizzin and I've added Radarr and Sonarr like this:
> 
> Radarr:
> 
> ```
> Host: http://localhost:7878/radarr
> API: redacted
> ```
> 
> Sonarr:
> 
> ```
> Host: http://localhost:8989/sonarr
> API: redacted
> ```
> 
> Obviously change the ports if they don't match your set up. No basic auth is needed. This should work for you as well!

This worked, thanks!
