### ISSUE TITLE
Improve list views

### ISSUE THREAD

**Issue by ludviglundgren** [autobrr/autobrr#26]
Some things that will improve the UX.

* [x] Filter list: Make item clickable, change edit to dots with dropdown. Edit, toggle, remove
* [x] IRC list: push TLS label to the right
* [x] IRC list: Make item clickable, change edit to dots with dropdown. Edit, toggle, remove
* [x] Download Clients: Make item clickable, change edit to dots with dropdown. Edit, toggle, remove

Would probably be good to continue and use HeadlessUI components for accessibility. Take a look at https://headlessui.dev/react/menu It's already in some places of the app.

## Future ideas

* [ ] Filter list: show actions or number of actions in list item

**Comment by smallobject** [comment]
This PR adds the number 5 item on the list:
`Download Clients: Make item clickable, change edit to dots with dropdown. Edit, toggle, remove`

https://github.com/autobrr/autobrr/pull/28
