### ISSUE TITLE
Indexer Request: ExoticaZ/AvistaZ network

### ISSUE THREAD

**Issue by kaizensh** [autobrr/autobrr#290]
ExoticaZ, but the entire family of sister sites would be cool too
- AvistaZ
- AnimeZ
- PrivateHD
- CinemaZ

**Comment by ludviglundgren** [comment]
I know PHD doesn't have IRC announces, but no idea about the others.

You can still use them as torznab feeds via Prowlarr, until they are implemented natively or get raw RSS support.

**Comment by ludviglundgren** [comment]
None of these have IRC announces so I'll close this. Next best thing is RSS support which will come soon. 

For now you can use torznab feeds via Prowlarr.
