### ISSUE TITLE
watch dir action dont create folders

### ISSUE THREAD

**Issue by DerUntote** [autobrr/autobrr#349]
Iam using rutorrent for downloading my files and want to use the autolabel feature, which works with subdirs in the watchfolder

Currently, i get errors, cause of "watch dir" action doesn't create folders on its way to place the torrent file.

Can we have this please as an option or forced?

**Comment by ludviglundgren** [comment]
Hi! That should likely be taken care of. Does that plugin create deeply nested structures or is it just subdirs in the main download dir?

Does it save to say `movies`? If so just create the directories yourself to start with.

**Comment by DerUntote** [comment]
https://github.com/DerUntote/autobrr
I added what I meant to my own fork. Thanks for sharing your work so we can extend our needs ourselves :)

**Comment by ludviglundgren** [comment]
Oh nice, well in that case let's get that into here as well! 😄

**Comment by DerUntote** [comment]
made a pull request ;)
