### ISSUE TITLE
Do not duplicate release download

### ISSUE THREAD

**Issue by Sonic3R** [autobrr/autobrr#375]
I created filter which downloads releases from 5 different trackers through IRC announce channels.

The problem if within 1 minute is announced same release on every tracker, autobrr sends 5 torrents to client and although I have 5 items in clients

It is possible in filter to specify unique download no matter from which tracker it downloads ?

**Comment by zze0s** [comment]
Hi! There was a Discussion started a couple of months ago to try and define what a duplicate is because there were some different ideas. https://github.com/autobrr/autobrr/discussions/294

Not yet settled on it but should be given some prio in the near future.

**Comment by jkaberg** [comment]
@zze0s I'd say this example is a good candidate on what an duplicate is,

![image](https://user-images.githubusercontent.com/613363/182791545-b77609b4-50f4-4d0c-834b-da54b870e21e.png)

An idea perhaps would be to be able to ignore previous releases with the exact same name? I think that would catch 90% of all cases this is relevant

**Comment by jkaberg** [comment]
Just to follow up on my last post (and seeing a lot of duplicates recently in my clients), what I mean was something simple like this (psuedo code):

```python
release_name = 'Cool Movie 2022 720p WEB h264-ReleaseGroup'
dedup_releases = True # config variable to enable or disable if we want duplicates sent to client

if release_name in db.query("SELECT 1 FROM approved_release WHERE name = {release_name}") and dedup_releases:
    continue # drop this release as it already existed in DB and dedup_releeases is true
else:
    push_release(release_name) # push to client
```

I think with this rudementary approach we can catch 98% of all these duplicates getting approved and pushed to clients.

**Comment by persuaded6414** [comment]
> I think with this rudementary approach we can catch 98% of all these duplicates getting approved and pushed to clients.

Indeed great. I believe this could somehow be connected with cross-seed. I'm not certain how it would behave when the first torrent is still being downloaded and the next announce comes. It should only happen once the first is completed, right? (looking at the screenshots posted by @jkaberg

**Comment by luckylittle** [comment]
> I'm not certain how it would behave when the first torrent is still being downloaded and the next announce comes. It should only happen once the first is completed, right? (looking at the screenshots posted by @jkaberg

@stxmqa There is complexity with fetching the information about completion from the download client. What we are really asking is even if it's just started downloading and the next announce comes in, it will be ignored. There are indexers which upload the same content at almost exactly the same time (e.g. within a second), so this will prevent the duplication.

**Comment by jkaberg** [comment]
> > I'm not certain how it would behave when the first torrent is still being downloaded and the next announce comes. It should only happen once the first is completed, right? (looking at the screenshots posted by @jkaberg
> 
> @stxmqa There is complexity with fetching the information about completion from the download client. What we are really asking is even if it's just started downloading and the next announce comes in, it will be ignored. There are indexers which upload the same content at almost exactly the same time (e.g. within a second), so this will prevent the duplication.

Actually what I'm referring to is looking up the autobrr database and if the (incoming) release has been "registered" in the (autobrr) database and the (autobrr) config option is checked then don't send the release to client (radarr/sonarr/torrent etc)

**Comment by luckylittle** [comment]
I'm currently testing this approach:

```bash
# Get the list of last 20 releases via API
last20releases=$(curl -X GET "http://${AUTOBRR_HOST}:7474/api/release" -H "X-API-Token: ${AUTOBRR_API_KEY}" | jq -r '.data[].name')

# Check if the new release is in the list of last 20 or not and quit with appropriate exit code
if echo "${last20releases}" | grep -q "${1}" ; then
  echo "$(date -u) |${1}| already in last 20 releases, stopping" >> preventMultigrab.log
  exit 1
else
  echo "$(date -u) |${1}| is being downloaded" >> preventMultigrab.log
  exit 0
fi
```

Screenshot:
![Screenshot from 2024-04-12 18-15-15](https://github.com/autobrr/autobrr/assets/8032159/ed9c83f9-e441-4dba-b2df-e6c7e81447f7)

**Comment by daymanbpi** [comment]
> I'm currently testing this approach:
> 
> ```shell
> # Get the list of last 20 releases via API
> last20releases=$(curl -X GET "http://${AUTOBRR_HOST}:7474/api/release" -H "X-API-Token: ${AUTOBRR_API_KEY}" | jq -r '.data[].name')
> 
> # Check if the new release is in the list of last 20 or not and quit with appropriate exit code
> if echo "${last20releases}" | grep -q "${1}" ; then
>   echo "$(date -u) |${1}| already in last 20 releases, stopping" >> preventMultigrab.log
>   exit 1
> else
>   echo "$(date -u) |${1}| is being downloaded" >> preventMultigrab.log
>   exit 0
> fi
> ```
> 
> Screenshot: ![Screenshot from 2024-04-12 18-15-15](https://private-user-images.githubusercontent.com/8032159/321913529-ed9c83f9-e441-4dba-b2df-e6c7e81447f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTQwNjMsIm5iZiI6MTcxNTk1Mzc2MywicGF0aCI6Ii84MDMyMTU5LzMyMTkxMzUyOS1lZDljODNmOS1lNDQxLTRkYmEtYjJkZi1lNmM3ZTgxNDQ3ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMTM0OTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGJkYTc4MTUxNGMyNGU1NzQ2Y2IwNjJiNTkwMDU1OWRmOGRlYzM5YTU5NTA0NWNkMTczZjZhODVjOTI5ZDhlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rgDTrhT1dD5Ni1d2mFvdA1EyWd5FW1LjyeF6KtAOj98)

I have the same issue as you with multiple indexers grabbing the same torrents. How is this script working for you?

**Comment by Snake883** [comment]
Same problem.

What happens is multiple torrents are created for the same files.  I don't think qBittorent allows swarms/merge like BiglyBT, so problems occur.  Also, I have QBT move completed torrents.  So one tracker completes before the others, moves the completed files, and now the other trackers have problems.  QBT will report the tracker as missing files, or attempt to move the completed files again to the download folder, and overwrite the files.  Basically a mess starts to happen.

Solutions:

- QBT to implement swarm merging like BiglyBT. (I can wish)
- AutoBrr to not download torrents with the same name and/or same folder/file name.  I then use cross-seed to link the trackers.
