### ISSUE TITLE
IRC UI Optimization

### ISSUE THREAD

**Issue by Hollander-1908** [autobrr/autobrr#376]
![image](https://user-images.githubusercontent.com/93162595/181202141-1a02a69c-e050-4da1-b1b5-2bea458522fd.png)

The GREEN blinking dot should be RED when no channel is connected when network is enabled.
It should only be GREEN when atleast 1 channel is connected.

**Comment by Audionut** [comment]
Not connected to a network and not connected to a channel are 2 different problems.

I would prefer Amber. Indicating that the network is connected to, but the underlying channels are not connected.

**Comment by Hollander-1908** [comment]
Agree with that!

**Comment by zze0s** [comment]
It's actually supposed to be yellow/orange/amber if there is any errors, so this is a bug.

**Comment by tom0010** [comment]
I'm getting the same issue after upgrading to the latest version. Not that I want to hijack this, but is this related that I cannot connect to a channel now? I didn't make any changes apart from doing docker pull.

**Comment by zze0s** [comment]
> I'm getting the same issue after upgrading to the latest version. Not that I want to hijack this, but is this related that I cannot connect to a channel now? I didn't make any changes apart from doing docker pull.
> 
> Edit: This is just hanging at sending connect command.

Yeah this is a bit of a hijack but what errors are you seeing on connect? If you haven't done it already, change to `logLevel = "TRACE"` in your `config.toml`, no restart needed and try re-connect and see what it says. Open an issue or post in the Discord and I'll try to help you and figure this out.

**Comment by tom0010** [comment]
> > I'm getting the same issue after upgrading to the latest version. Not that I want to hijack this, but is this related that I cannot connect to a channel now? I didn't make any changes apart from doing docker pull.
> > Edit: This is just hanging at sending connect command.
> 
> Yeah this is a bit of a hijack but what errors are you seeing on connect? If you haven't done it already, change to `logLevel = "TRACE"` in your `config.toml`, no restart needed and try re-connect and see what it says. Open an issue or post in the Discord and I'll try to help you and figure this out.

Thanks, that helped a lot, not an autobrr issue. Just needed to identify myself on IRC using a different invite command to what I already had.

**Comment by zze0s** [comment]
Fixed in #399

**Comment by Hollander-1908** [comment]
> Fixed in #399

Thanks for your hard work! Looks pretty good now. Much appreciated.
