### ISSUE TITLE
Cancel Button Not Working

### ISSUE THREAD

**Issue by Hollander-1908** [autobrr/autobrr#377]
The cancel button in filters is not working.
Nothing happens when you press it.

It seems to be only at filters where it is not working.
For settings the cancel button works as it should be.

**Comment by zze0s** [comment]
Hi!

Is it the Cancel button on inside the filter?

That button is to **reset non-saved changes** in the form, and not a back button if that's what you're expecting?

Would adding a back button make more sense? And a button `reset` button that would clear all fields?

**Comment by Hollander-1908** [comment]
I think `cancel` should be both **back** and **reset non-saved changes**.
`reset` sounds more like resetting all values to default.
