### ISSUE TITLE
Misleading feed refresh interval

### ISSUE THREAD

**Issue by KptCheeseWhiz** [autobrr/autobrr#389]
Hello,

The refresh interval for the feed interface is misleading..

If we look at the code, it is adding the minutes to a ["*/%d * * * *" cron job interval](https://github.com/autobrr/autobrr/blob/develop/internal/feed/service.go#L277), so if you put a number that is not a multiple of 60, the job will also be executed at the start of the hour. 

As an example, if we put in 25 minutes, the job will be executed at [0, 25 and 50 minutes every hour.](https://crontab.guru/#*/25_*_*_*_*) which makes a 25-25-10 minutes interval.

Thank you :)

**Comment by KyleSanderson** [comment]
hi - if you want to test you can try this image `ghcr.io/autobrr/autobrr:pr-390`. Based on feedback it will be merged in the coming days.
