### ISSUE TITLE
No log history

### ISSUE THREAD

**Issue by rouggy** [autobrr/autobrr#40]
Hello,

It is complicated to find out what the issues are cause if we change from tab log to settings and come back to log, the log is completely empty, we have to remain on the tab to know what is going on.

Any chance to have an history of the log ?

Thanks

**Comment by ludviglundgren** [comment]
Hi!

He current implementation/library which is used for SSE does have an option to keep all the logs/events. 

But when the application has been active for a couple of months that could be 100s of thousands of events that would be sent back.

I'll look into if I can hook up my own cache or something for a couple of hundred events, but in the mean time you can use either the log to file feature, or if you run it with systemd, check/tail the logs to stdout with journalctl.

**Comment by rouggy** [comment]
Hi why not just keeping the last 1,000 lines ? or similar ?

Thanks

**Comment by ludviglundgren** [comment]
The library used to hook the logger to server sent events (sse) doesn't support that currently but I saw discussions about it so we'll see.

You can enable the log to file in the config if you uncomment the logPath line, and set it to a directory you can write to.

LogLevel TRACE will give you the most output.

So you can either tail that log file, or if you run it with systemd, use journalctl to tail it's logs.

As I said before, documentation will get priority in the next weeks.

**Comment by rouggy** [comment]
Yep done exactly the above and works well.
Thanks
