### ISSUE TITLE
Watch folder issue

### ISSUE THREAD

**Issue by GregTroar** [autobrr/autobrr#41]
Hello,

I am having an issue with watch folder.
I am getting this error: ERRORcould not create new temp file '/home/user/watch/Series/b07d6448f565f476f7f1eb0ba31dbca6

this folder is accessible and I made it chmod 777 for testing purpose but still I am getting this error.
Any idea where it is coming from ?

Thanks

**Comment by ludviglundgren** [comment]
How are you running the application? 

And are you using the published binary or built it locally?

**Comment by rouggy** [comment]
I am not able to built it locally, I tried all day long and I am also not used to go at all.
I think I understood I had to go to cmd/autobrr and run go build but I keep having the same error message:

../../web/build.go:14:12: pattern build: no matching files found

While I have no issue to build autobrrctl

To answer your question I got a published binary.
Now, as I created 2 yaml files for 2 new indexers I would like to try and achieve to build the app to be able to test but no luck till now.

I am on Debian 11 and running golang-1.17.5

**Comment by rouggy** [comment]
How am I running the app ?
Just took the two binaries and put them in /opt/Autobrr
Created a service in /etc/systemd/system to start automatically the app.

Everything works as expected, I have 2 active indexers / irc's and a filter and it seems to work as expected. Also a bit sad that I cannot get more information about the parsing and decision making on whether the download is triggered or not in the log but again the program is very new but it is promising.
