### ISSUE TITLE
Wrong id was used to get size information through api

### ISSUE THREAD

**Issue by rinomi** [autobrr/autobrr#412]
Hi,I found a mistake when I was downloading torrents from tracker 'Redacted'.
When autobrr used the 'Torrent Details' api for getting size of torrents, it used the groupId, instead of torrentId.

For example, When autobrr wanted to get the size information of the torrent that torrent id is 3769078(Sandilé - Home Again 04 [2022] [EP] - FLAC / Lossless / WEB),
it used 1789830 to get the size through the 'Torrent Details' api.

**Comment by KyleSanderson** [comment]
Can you please test https://github.com/autobrr/autobrr/pull/413 when it's built and report your findings back
