### ISSUE TITLE
What license is this project utilising?

### ISSUE THREAD

**Issue by grawlinson** [autobrr/autobrr#416]
Hey, I've just packaged this on the AUR, and I was wondering what the license is for this project, e.g. GPL/MIT/BSD/other. I think the *arr projects generally follow GPL-3.0.

I'd appreciate if a license was placed at the root of the project, and the license type stated in the README.md.

Thanks! :)

**Comment by zze0s** [comment]
Hi! Thank you very much for doing that!

Currently there's none defined, but we'll make sure to set one soon. Is it needed to publish or can you publish without it for now? Will reply here once done.

**Comment by grawlinson** [comment]
It's fine *for now*, but a license does need to be applied at some point. :+1:

**Comment by grawlinson** [comment]
Just a reminder that the chosen license has to be explicitly agreed by all past contributors. If any of these contributors disagree with the license, their contributions need to be reverted.

I strongly suggest that a license is chosen ASAP and all past contributors explicitly state that their contributions can be licensed under the chosen license.

**Comment by zze0s** [comment]
I'm in the process of contacting contributors to get an OK, but wondering how this should be collected/accounted for? 

This could potentially take quite some time.

**Comment by grawlinson** [comment]
I think the simplest thing to do would be to create a new issue that mentions all contributors and as each contributor replies, tick them off a checklist.

**Comment by OhMyGuus** [comment]
@zze0s Any update on this? Since it's quite important to know what license this project has, especially since the project is getting bigger with more contributors.

**Comment by fabricionaweb** [comment]
Do we have a position on this issue?

**Comment by FollieHiyuki** [comment]
Also +1 from me. A license is essential for serious downstream packaging.

**Comment by zze0s** [comment]
We finally did it :smile:  https://github.com/autobrr/autobrr/pull/897

Now it's under GPLv2-or-later. Hope that will help you all with packaging it for various package managers etc.
