### ISSUE TITLE
Load config from ENV

### ISSUE THREAD

**Issue by zze0s** [autobrr/autobrr#419]
To simplify docker setups, add option to load config from ENV vars.

**Comment by onedr0p** [comment]
Might be worth switching viper to  https://github.com/knadh/koanf, there are some notes on improvements this has over viper https://github.com/knadh/koanf#alternative-to-viper

**Comment by zze0s** [comment]
We made improvements for this in #691. You can now override with env vars starting with the `AUTOBRR_` prefix. Still need to document it properly.

We discovered that Viper has issues with merging config file and env vars but the solution should work. omegabrr is using `koanf` and it's pretty nice so we might do more improvements in the future.
