### ISSUE TITLE
IRC Shows grey

### ISSUE THREAD

**Issue by coolcat97** [autobrr/autobrr#426]
![image](https://user-images.githubusercontent.com/29034657/185882384-2e869ebc-c801-45c8-b94e-04cd1e0c6eb2.png)

erm.. help? These same credentials I used work on autodl-RSSI

**Comment by coolcat97** [comment]
I'm an idiot, and to the other idiots, you must enable them...... 

Click edit, toggle enabled then save

**Comment by Mattssn** [comment]
> I'm an idiot, and to the other idiots, you must enable them......
> 
> Click edit, toggle enabled then save

Just had to admit, I have been trying to figure out for the last half hour why it wont connect. >.>
