### ISSUE TITLE
make it possible for temporary logLevel changes via UI

### ISSUE THREAD

**Issue by stacksmash76** [autobrr/autobrr#429]
Should ideally be implemented as a dropdown, instead of a checkbox as is the case now. Useful for setting the log level to trace

**Comment by stacksmash76** [comment]
closed in #704

**Comment by zze0s** [comment]
> closed in #704

It took some time but we finally got there..! Went with your proposed approach of just reading lines and changing it. Soon time for the famous revisit-later onboarding PR :smile:
