### ISSUE TITLE
Tracker request: Locadora.xyz

### ISSUE THREAD

**Issue by Fotguedes** [autobrr/autobrr#432]
I don't know if i need to provide any info, but if it's necessary i would be happy to help!

**Comment by zze0s** [comment]
Hi! Yeah that's doable but I need you to gather all the info. We currently only support indexers with IRC announces.

# Indexer request

-  Do they have irc announce? Yes / No
-  Link to existing autodl-irssi .trackers file: Check wiki, forums and autodl-trackers repo

## Announce examples

Please provide 1-5 different announces. And change release titles for good measure

- `SOME LONG ANNOUNCE`
- `OTHER ANNOUNCE`

## IRC Network

- Network name: TrackerNetwork
- Network address: irc.network.tld
- Port: 6697 is common for TLS
- SSL/TLS: Yes / No
- NickServ registration required? Check wiki, guides etc: Yes / No
- Is there a required format for the nick? Like `username|bot`? Check wiki, guides etc
- Invite command: Eg. `invitebot announce USERNAME IRCKEY`

## Bonus

Check their categories in the announce an on site

Announce category - Site category name

**Comment by nihues** [comment]
no irc for them... only rss.

**Comment by zze0s** [comment]
Then use **Generic RSS** which is available from **v1.5.0** 👍
