### ISSUE TITLE
spaces in filter tags prevents matching

### ISSUE THREAD

**Issue by F4n4t** [autobrr/autobrr#437]
Hi,
i noticed the tag filter does not work with spaces.

this does not work e.g.:
Tracker Tag: `Science Fiction`
Filter: `Science Fiction`

it seems that the spaces from the announce is removed

Maybe it would be better to remove the spaces in the filters too before it gets checked in https://github.com/autobrr/autobrr/blob/9813f5718d748a434434e55881e51849b8890498/internal/domain/filter.go#L319

**Comment by zze0s** [comment]
Can you format that with backticks ` start and end of the tag examples ? Like `Science Fiction`.

**Comment by zze0s** [comment]
Is it surrounding spaces or in you mean? :thinking: 

It does clean surrounding extra spaces, makes it lowercase and tries to match, but the spaces in the tag should still be there. Could you post a full announce example but just replace the release name with something random?

**Comment by F4n4t** [comment]
I meant the spaces in between.

LOG:
> 12:51:31.000TRACE announce: process line: NEU Test.S03.GERMAN.DL.FS.DVDRiP.x264-P2P [Kategorie] [P2P] [15.26 GB] -- https://test-tracker.com/torrent.php?id=00000 | Adventure, Fantasy, Science Fiction, Encode, AVC, DL, tt0112167
> 2:51:31.000TRACE filter.Service.CheckFilter: checking filter: Test Tags {ID:1 Name:Test Tags Enabled:true CreatedAt:2022-09-04 12:58:57 +0000 UTC UpdatedAt:2022-09-05 09:01:03 +0200 CEST MinSize: MaxSize: Delay:0 Priority:0 MaxDownloads:0 MaxDownloadsUnit: MatchReleases:*GERMAN* ExceptReleases: UseRegex:false MatchReleaseGroups: ExceptReleaseGroups: Scene:false Origins:[] ExceptOrigins:[] Bonus:[] Freeleech:false FreeleechPercent: Shows: Seasons: Episodes: Resolutions:[] Codecs:[] Sources:[] Containers:[] MatchHDR:[] ExceptHDR:[] MatchOther:[] ExceptOther:[] Years: Artists: Albums: MatchReleaseTypes:[] ExceptReleaseTypes: Formats:[] Quality:[] Media:[] PerfectFlac:false Cue:false Log:false LogScore:0 MatchCategories: ExceptCategories: MatchUploaders: ExceptUploaders: Tags:Science Fiction ExceptTags: TagsAny: ExceptTagsAny: ExternalScriptEnabled:false ExternalScriptCmd: ExternalScriptArgs: ExternalScriptExpectStatus:0 ExternalWebhookEnabled:false ExternalWebhookHost: ExternalWebhookData: ExternalWebhookExpectStatus:0 ActionsCount:0 Actions:[] Indexers:[] Downloads:0xc000042ff0}
> 12:51:31.000TRACE filter.Service.CheckFilter: checking filter: Test Tags for release: &{ID:0 FilterStatus:PENDING Rejections:[] Indexer:test FilterName:Test Tags Protocol:torrent Implementation:IRC Timestamp:2022-09-10 12:51:31.478982719 +0200 CEST m=+398.443664093 GroupID: TorrentID:00000 TorrentURL:https://test-tracker.com/download.php?id=00000 TorrentTmpFile: TorrentHash: TorrentName:Test.S03.GERMAN.DL.FS.DVDRiP.x264-P2P Size:15260000000 Title:Test Category:Kategorie Season:3 Episode:0 Year:0 Resolution: Source:DVDRiP Codec:[x264] Container: HDR:[] Audio:[] AudioChannels: Group:P2P Region: Language: Proper:false Repack:false Website: Artists: Type: LogScore:0 IsScene:false Origin:P2P Tags:[Adventure Fantasy ScienceFiction Encode AVC DL tt0112167] ReleaseTags: Freeleech:false FreeleechPercent:0 Bonus:[] Uploader: PreTime: Other:[FS] RawCookie: AdditionalSizeCheckRequired:false FilterID:1 Filter:0xc000ab7200 ActionStatus:[]}
> 12:51:31.000DEBUG filter.Service.CheckFilter: (Test Tags) for release: Test.S03.GERMAN.DL.FS.DVDRiP.x264-P2P rejections: (tags not matching. got: [Adventure Fantasy ScienceFiction Encode AVC DL tt0112167] want: Science Fiction)

**Comment by zze0s** [comment]
Thanks! Fixed now in #459 and will be released with next version.
