### ISSUE TITLE
Basic Auth for rTorrent

### ISSUE THREAD

**Issue by guimello87** [autobrr/autobrr#451]
Thanks for adding rTorrent to the list of clients!

However, I am unable to connect as my server requires Basic Auth. Would it be possible to add this?

**Comment by ludviglundgren** [comment]
Hi!

It works if you put it in the url like `http://user:password@mydomain.com`.

There was a PR for the library where a proper solution was discarded for some reason. https://github.com/mrobinsn/go-rtorrent/pull/1
