### ISSUE TITLE
qBittorrent sets time limits in minutes, not seconds.

### ISSUE THREAD

**Issue by CarlitoGil** [autobrr/autobrr#453]
The qBittorrent Action's "SEED TIME LIMIT" caption should say "(MINUTES)" not "(SECONDS)".

![image](https://user-images.githubusercontent.com/5706999/188999305-531962ff-b10e-4316-ac0f-a024afd5ba8b.png)

**Comment by KyleSanderson** [comment]
Are you sure

**Comment by CarlitoGil** [comment]
Yes. If you put 60 in that field in autobrr it would show 60 **minutes** in qBittorrent.

![image](https://user-images.githubusercontent.com/5706999/189063265-c9215bda-0b08-4dcb-8db4-b2ec11e264a7.png)

![image](https://user-images.githubusercontent.com/5706999/189062955-08749d91-ff20-4f68-891f-51df7fce4b50.png)

**Comment by CarlitoGil** [comment]
To clarify: the settings seem to work fine, it's just the caption that needs to changed to minutes.

**Comment by KyleSanderson** [comment]
Yeah you're right - there's transparent conversions elsewhere in the qBittorrent WebUI: this is not one of them.

**Comment by CarlitoGil** [comment]
100%.

[image: image.png]

*— Carlos Antonio Gil*
