### ISSUE TITLE
[FR] qBittorrent added torrent priority

### ISSUE THREAD

**Issue by bjeanes** [autobrr/autobrr#463]
**Is your feature request related to a problem? Please describe.**

I have a freeleech filter to try to get in on the swarm early. However, the new torrents are always added to the end of the download list, so won't actually start downloading, potentially until it is too late.

**Describe the solution you'd like**

I'd like the option to specify whether a qBittorrent action adds the torrent to the front or the end of the list. 

**Describe alternatives you've considered**

I had hoped that this option did what I hoped:

<img width="596" alt="Screen Shot 2022-09-17 at 4 36 20 pm" src="https://user-images.githubusercontent.com/2560/190844020-5149aee7-ff16-4d29-807b-64ddb15737d9.png">

As it stands, I'm better keeping that off and only grabbing freeleech torrents when qB is mostly idle, but unfortunately that is pretty rare.

**Comment by zze0s** [comment]
Hi! 

There's no options in the api to send priority to qBittorrent when adding the torrent, so there's nothing for autobrr to do.

So this is more about how you use qBittorrent. Do you usually have a lot of stuff in the download queue?

That option, **ignore client rules** is for the rules on the download client in autobrr. It can control like max active torrents and only add if it's below a certain threshold. Ignore client rules in the action simply skips that check and adds stuff anyway.

**Comment by bjeanes** [comment]
Hmm then might I suggest "Ignore client rules" set it to forced mode then, which definitely does exist? That will make the torrent active regardless of the queue position.

**Comment by CarlitoGil** [comment]
> There's no options in the api to send priority to qBittorrent when adding the torrent, so there's nothing for autobrr to do.

Hi, @zze0s 
Could you check on this again, please?

qBittorrent's API is able to set the priority after adding the torrent:
[https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#maximal-torrent-priority](url)
The *arrs are able to add the torrent with top priority.

It would also help with Timed Freeleech!

Thanks.
