### ISSUE TITLE
Max downloads per X buggy

### ISSUE THREAD

**Issue by zze0s** [autobrr/autobrr#467]
Hi, @mjvotaw

I deleted your issue since you had posted logs with your rss key in them. It might be a good idea to update the key.

As for the issue, I seemed to work for a bit but not all the time. I've done some debugging of the issue and we might have to update the logic for how it's calculated.

So need to look into this more.

**Comment by mjvotaw** [comment]
d'oh, thanks for the heads up.

**Comment by jonasstaehle** [comment]
I am having issues with the max downloads not being reached.
Filter rejects for max downloads per hour being reached, even though it didn't download anything in the last hour.

In one example i set max downloads to 8 per hour. It started rejecting when it reached 8 downloads total, over 4 hours.
