### ISSUE TITLE
Special characters such as æ, ø and å not supported in announces from Norbits

### ISSUE THREAD

**Issue by kuleis1** [autobrr/autobrr#469]
**Describe the bug**
Autobrr does not seem to handle special characters such as æ, ø and å in announces from the tracker Norbits. These characters are displayed as a question mark � in the logs. Release names with such characters are pushed from Autobrr to Sonarr with � in the release name which makes the release not match even though the show is monitored in Sonarr.

**To Reproduce**
1. Have Autobrr join the NB announce channel where a torrent with a show name containing the characters æ, ø or å is announced
2. Check the Releases tab or logs, and show name will be displayed with at � instaed of æ, ø or å.
3. The release will not be accepted due to the � in the title does not match show monitored in Sonarr.

**Expected behavior**
Autobrr should push the correct show name.

**Enviroment:**
 - unRAID 6.11.0-rc5 
 - Autobrr v1.7.0 (docker)
 - Norbits announce channel

**Comment by KyleSanderson** [comment]
Are you on discord? Is this still a problem?

**Comment by s0up4200** [comment]
I've submitted a ticket to the tracker staff to make them aware of the issue and I see that you made a forum post as well @kuleis1 
Let's hope they fix it.

**Comment by s0up4200** [comment]
Response from NB staff:

"Hello.

It is probably ISO-8859-15. Unfortunately, it is not very trivial to change to UTF-8.
The vast majority of clients cope with this just fine, and it's been like this forever without anyone reacting, so it's probably not the highest priority for us to fix."

**Comment by s0up4200** [comment]
Closing this. There's not much we can do about it unfortunately.
