### ISSUE TITLE
Freeleech Filter Option Fails for Generic RSS

### ISSUE THREAD

**Issue by CarlitoGil** [autobrr/autobrr#476]
**Describe the bug**
The filter option for Freeleech fails to detect it on Generic RSS feeds.

**To Reproduce**
1. Add an RSS feed for a tracker that includes "Freeleech" in it.
2. Create a filter for that indexer with the `Advance>Freeleech` option enabled.

**Expected behavior**
Torrents should be filtered out if they are not Freeleech.

**Desktop:**
 - OS: Windows 10 x64
 - autobrr 1.7.1

**Additional context**
TorrentDB's feeds serve as example of a tracker that includes the Freeleech information.
The parser can use regex on each item of the feed.
The pattern `\bFreeleech\b` can detect it, as it's not term used in other contexts that would create false positives.

**Comment by zze0s** [comment]
Hi! The RSS parser is very bare-bones but will be dealt with and improved.

Part of the issue tho is that there's no standard and almost all feeds does it's own thing, so it will take time to get it working everywhere.
