### ISSUE TITLE
Allow Users to Set Cron Jobs

### ISSUE THREAD

**Issue by budgetfermium** [autobrr/autobrr#479]
**Is your feature request related to a problem? Please describe.**
Users can only set the refresh interval in autobrr, making fine-grained control over refresh times impossible.

**Describe the solution you'd like**
Add an option for advanced users to specify the cron schedule manually.

**Comment by zze0s** [comment]
Hi! 

Is this related to Feeds or something else? The only other thing using a schedule is the check for app updates, which we might make that configurable in the future.

**Comment by budgetfermium** [comment]
My request is related to feeds. Cron job schedules are useful in preventing IP bans on trackers which allow generating multiple RSS feeds (e.g. Nyaa).

**Comment by KyleSanderson** [comment]
OK so the real request is to not run queries at the same time as each other. If there was a flag added to run the same domains in sequence of delay, would that resolve the quandary?

Just trying to avoid overly complex cronjobs, some users are struggling with filters so to add stuff like this only raises the support burden. Personally, I'm not against it (totally for it, actually), but I know the initial request is going to cause users lots of pain in the future.

**Comment by budgetfermium** [comment]
That would partly solve my problem - I would like some feeds from the same domain to be checked more often than others. 

I think it would be easier to allow users to set cron job schedules that suit their needs than to hardcode solutions to many edge cases, especially since cron is already used internally in autobrr. Having users explicitly confirm that they want to use cron and linking to something like https://crontab.cronhub.io/ might help minimize the support burden.

**Comment by zze0s** [comment]
> That would partly solve my problem - I would like some feeds from the same domain to be refreshed more often than others.
> 
> I think it would be easier to allow users to set cron job schedules that suit their needs than to hardcode solutions to many edge cases, especially since cron is already used internally in autobrr. Having users explicitly confirm that they want to use cron and linking to something like https://crontab.cronhub.io/ might help minimize the support burden.

Is this still something you want or need? We did change the interval thing a bit some months ago and that's fine for 99% of users. We don't want to ignore the last 1% of power users but can't do everything :sweat_smile:
