### ISSUE TITLE
Category not matching (Prowlarr)

### ISSUE THREAD

**Issue by focheur91300** [autobrr/autobrr#481]
Hello,

I am currently experiencing a problem with the "MATCH CATEGORIES" option in the Advanced tab of a filter.

I tried to pass all the category IDs of Prowlarr or the category names but nothing works.
![image](https://user-images.githubusercontent.com/25317272/193306867-50ab688e-a0bb-417a-ab5d-94d220f82840.png)
With the following log errors:
```
{"level":"debug","module":"release","indexer":"torznab-prowlarr","filter":"SHOW_See","release":"See.S03E06.MULTI.FRENCH.4K.X265.2160p.10bit.HDR.WebRip.E-AC-3.5.1-Shiro","time":"2022-09-30T13:34:25Z","message":"release rejected: category not matching. got:  want: TV,Anime,tv,tv/anime,5000,5070,102184,102179"}
{"level":"debug","module":"release","indexer":"torznab-prowlarr","filter":"SHOW_See","release":"See.S03E06.MULTI.FRENCH.1080p.WEBRip.DDP5.1.Atmos.x265","time":"2022-09-30T13:34:25Z","message":"release rejected: category not matching. got:  want: TV,Anime,tv,tv/anime,5000,5070,102184,102179"}
{"level":"debug","module":"release","indexer":"torznab-prowlarr","filter":"SHOW_See","release":"See.S03E06.FRENCH.720p.ATVP.WEB-DL.DDP5.1.Atmos.H264-FRATERNiTY (Jour noir)","time":"2022-09-30T13:34:26Z","message":"release rejected: category not matching. got:  want: TV,Anime,tv,tv/anime,5000,5070,102184,102179"}
```

Of course as soon as I remove the category filter it works.
![image](https://user-images.githubusercontent.com/25317272/193306703-75429f48-4aec-4e18-80ea-c50ba3720e43.png)
```
{"level":"info","module":"release","indexer":"torznab-prowlarr","filter":"SHOW_See","release":"See.S03E06.MULTI.FRENCH.4K.X265.2160p.10bit.HDR.WebRip.E-AC-3.5.1-Shiro","time":"2022-09-30T14:41:28Z","message":"Matched 'See.S03E06.MULTI.FRENCH.4K.X265.2160p.10bit.HDR.WebRip.E-AC-3.5.1-Shiro' (SHOW_See) for torznab-prowlarr"}
{"level":"info","module":"release","indexer":"torznab-prowlarr","filter":"SHOW_See","release":"See.S03E06.MULTI.FRENCH.1080p.WEBRip.DDP5.1.Atmos.x265","time":"2022-09-30T14:41:30Z","message":"Matched 'See.S03E06.MULTI.FRENCH.1080p.WEBRip.DDP5.1.Atmos.x265' (SHOW_See) for torznab-prowlarr"}
```

I can't figure it out.

Thanks in advance.

**Comment by zze0s** [comment]
Did you update to `v1.8.1`?  Can you check the feed manually if you can see categories in it? It should parse them. And also, even if that's a local url you shouldn't post your apikeys like that.

**Comment by focheur91300** [comment]
Yes, I am up to date:
![image](https://user-images.githubusercontent.com/25317272/197531766-0955c7ae-ec83-4fd4-8130-0c856ddcf7d1.png)

From a Prowlarr point of view, the categories are clear:
![image](https://user-images.githubusercontent.com/25317272/197532840-cd6f9e5c-5331-421a-a3c6-611e9e95d8c0.png)

After use in CURL for example: 
`curl -s "https://prowlarr.fochcraft.priv/1/api?t=search&apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&cat=5000,5070" 2>/dev/null`

Then I don't understand your question.

**Comment by zze0s** [comment]
I suggest you change api key for Prowlarr since you have now leaked it.

Anyhow, the prowlarr feed doesn't do search by category with autobrr, it fetches all/latest, and then the filter checks whatever was returned from the search.
