### ISSUE TITLE
[FEATURE REQ] ability to create re-usable webhooks

### ISSUE THREAD

**Issue by brandon-barker** [autobrr/autobrr#486]
**Is your feature request related to a problem? Please describe.**
I use the same webhook for all my filters, it's very tedious to have to replicate it across all filters especially if I change something within the POST body

**Describe the solution you'd like**
A section within settings called "Webhooks" where I can create hooks to be re-used within filters

**Describe alternatives you've considered**
Nothing I can think of besides updating all filters manually

**Additional context**
I use the cross-seed /api/announce as a way of filtering out duplicate releases, so I have this applied to all my filters. It would be nice if I could create a central webhook called "Cross-Seed" where I can add Host, Data and Expected HTTP Status

**Comment by zze0s** [comment]
Hi!

The easiest and best way to solve this is to have one high priority filter in front of all the other filters, and only that one has the cross-seed webhook. You need to set some action on it for it to load, but the test or run cmd with just an echo would be fine.

**Comment by brandon-barker** [comment]
Unfortunately that doesn't seem to work. I've created a "Webhook Filter" with a priority of 10, has the webhook included and an action of Test

Then a "Test" filter with a priority of 0 and an action to send to rTorrent (which works by itself)

It matches the "Webhook Filter" but then doesn't move on to the Test filter

**Comment by brandon-barker** [comment]
Sorry, I deleted the comment you replied to

> Also worth noting that in this case the expected status should be the inverse of a match

This was the exact problem 🤦‍♂️ Works perfectly now. Thanks so much, so happy I made the switch from autodl-irssi!

**Comment by zze0s** [comment]
Great! Happy to hear :) 

There's lots of useful stuff in our Discord that haven't made it's way (or probably ever will) to the docs etc, and we have a thriving and friendly community, if that's of interest. https://discord.gg/WQ2eUycxyT
