### ISSUE TITLE
[FEATURE REQ] Readarr support

### ISSUE THREAD

**Issue by awesomekyle** [autobrr/autobrr#487]
**Is your feature request related to a problem? Please describe.**
Readarr is the one *arr that I use that autobrr doesn't support, and would go great with the MyAnonamouse integration

**Describe the solution you'd like**
Readarr support that works like the other *arr's

**Describe alternatives you've considered**
Manually downloading, or using RSS feeds like always

**Comment by voltron4lyfe** [comment]
Added basic support: https://github.com/autobrr/autobrr/pull/490  Only tested with MaM

**Comment by zze0s** [comment]
Tested and merged #490
