### ISSUE TITLE
[FEATURE REQ] ZNC support

### ISSUE THREAD

**Issue by Nodens-** [autobrr/autobrr#488]
**Is your feature request related to a problem? Please describe.**
There are a lot of use cases where ZNC is essential.

1) I have a server, for example, that has no other way to connect to IRC without the connection to IRC being detected (chat networks are not allowed in this specific environment). I managed to actually connect everything through ZNC but autobrr does not detect any announces for some reason (although everything is green), leaving `last announce` to `n/a`.

2) Another use case is retention and replay on outages.

3) Third one is the ability to monitor an indexer with several seedboxes. Some indexers do not allow you to set up a million different usernames in their IRC network and some others may flag and autoban you if you try it.

**Describe the solution you'd like**
Proper ZNC support. It is strange for anything IRC related not to support ZNC. This is really a deal breaker for switching from autodl-irssi for my setup.

**Describe alternatives you've considered**
For most of these use cases there are no alternatives. For 1) you may be able to use a tunnel IF the environment allows you to do complex routing but that is not always the case.

**Comment by KyleSanderson** [comment]
> **Describe the solution you'd like** Proper ZNC support. It is strange for anything IRC related not to support ZNC. This is really a deal breaker for switching from autodl-irssi for my setup.

Did you hack the autodl-irssi definitions to support ZNC? I don't specifically remember it being possible with that platform, but this could be helpful for what you're trying to accomplish: https://www.reddit.com/r/seedboxes/comments/iipm4e/autodlirssi_and_znc_help/

Before support for this lands, in the meantime, you could also create custom definitions for the networks that you're unable to connect to.

> Third one is the ability to monitor an indexer with several seedboxes. Some indexers do not allow you to set up a million different usernames in their IRC network and some others may flag and autoban you if you try it.

It's certainly possible to use a single autobrr instance, and send the results to remote endpoints not on your network. Perhaps it's also possible to run autobrr on your bouncer, and forward the results that way.

3 options at least today to make this work 😜

**Comment by Nodens-** [comment]
> Did you hack the autodl-irssi definitions to support ZNC? I don't specifically remember it being possible with that platform, but this could be helpful for what you're trying to accomplish: https://www.reddit.com/r/seedboxes/comments/iipm4e/autodlirssi_and_znc_help/

autodl-irssi supports ZNC and BNC out of the box. You just have to have different alias hostnames per indexer due to the duplicate host limitation but everything else, parsing, connecting etc etc works out of the box. I use different CNAME DNS records per indexer since it's MUCH easier to handle at scale while I can still resolve them privately but `/etc/hosts` definitions work as well. It's how I have everything set up for years now, heh. I just want to get rid of autodl-irssi for a while now and it was just today that I decided to take the plunge on a few servers to see how autobrr handles things, hoping to migrate everything eventually.

Is the problem for not catching the announcements a hardcoded hostname in the definitions? If that's the case I can work around that for now. I will have to check the definitions. If I can just override the hostnames to my CNAME records for the bouncer and have it work, it'll make my day a whole lot easier heh.

> It's certainly possible to use a single autobrr instance, and send the results to remote endpoints not on your network. Perhaps it's also possible to run autobrr on your bouncer, and forward the results that way.

This is out of the question for several reasons. The main ones are the detectable httprpc plugin and that we're talking about a LOT of servers, indexers and filters. A single instance of autobrr would be impossible to handle it even if there were no privacy concerns. . While having 200 instances of autobrr monitoring a single bouncer is efficient.

> 3 options at least today to make this work
I must have missed something. I see 2 proposed workarounds, one for issue 1 and one for issue 3 (the later is not feasible but I'll be happy to solve the first for now).

So, to reiterate, if I override the original IRC server hostnames locally or make custom definitions, I can go through the bouncer, correct? If that is so, it actually helps 3 as well although it's a huge pain to maintain at the scale we're talking about. Still if it works it will at least let me proceed with the migration and start editing my scripts :D

**Comment by Nodens-** [comment]
Ok, so making copies of the definitions and replacing the server fields to the CNAME DNS aliases for the bouncer and everything works fine.

This means that in order to implement basic ZNC support, albeit with the same caveat as autodl-irssi, the only thing that needs to be done is to decouple the server name from the definition file. So I propose a `Bouncer` toggle that adds a dropdown menu, allowing the selection of one of the present IRC entries and reading the server hostname from there. That, or the `Bouncer` toggle adding an input box to manually input the hostname for the particular indexer, overriding the definition file.

Also if it was possible to not exit non-announcement channels when the `Bouncer` toggle is on and simply ignore them, the need to setup a secondary grouped nick would also go away which would make bouncer support as good as it gets, sort of implementing bouncer aware network handling which is kind of overkill for this use case.

Unfortunately, as an engineer, JS, its ecosystem and transpiles are probably the only languages I have never touched, otherwise I would submit a PR myself. I did try building the develop branch on my Fedora workstation but got lost in yarn dependency hell. Will try again in a VM, as I don't want to start fiddling with custom packages on my workstation, once I'm done with migrating about 20 servers to check how autobrr is doing compared to autodl-irssi and also test performance with transmission and qbittorrent now that I have IRC monitoring uncoupled from rutorrent.

**Comment by zze0s** [comment]
> This is out of the question for several reasons. The main ones are the detectable httprpc plugin and that we're talking about a LOT of servers, indexers and filters. A single instance of autobrr would be impossible to handle it even if there were no privacy concerns. . While having 200 instances of autobrr monitoring a single bouncer is efficient.

Could you explain a bit more about this? Is this say 200 different users, or you only with 200 servers?

> once I'm done with migrating about 20 servers to check how autobrr is doing compared to autodl-irssi and also test performance with transmission and qbittorrent now that I have IRC monitoring uncoupled from rutorrent.

And this. Are you talking about 20 servers where you have autodl-irssi? With autobrr you can communticate with local and remote instaces of your clients. I have one single instance that controls 5-6 servers and twice the amount of clients. All in a single instance of autobrr with 20+ indexers and lots of filters, which makes it easy to manage in one place.

As for building, you need Golang which the backend is built with, and Node/Yarn to build the web. Easiest is to build it with Docker, and there's a `make build/docker` for that. If you don't like docker, then build the web first, then build the backend. 
There's make commands for that.

The BNC bits been talked about in the past in other issues and on Discord etc. Maybe it looks super simple from your side to implement that, but doing it reliably requires some effort, and since a single instance can handle lots of servers/clients and not bound 1-1 rutorrent and autodl-irssi per server, there's not a huge need for a BNC IMO.

But maybe your usecase is different and it does make sense, but I would like some clarifications to answer that :)

**Comment by Nodens-** [comment]
> Could you explain a bit more about this? Is this say 200 different users, or you only with 200 servers?

I will not get into specific numbers for privacy reasons but I help manage 8 different networks for a total of over 200 servers. Each server has several instances of rtorrent+rutorrent+autodl-irssi running on very different configurations, very few of them are running transmission or deluge. Some are containerized, some are VMs, some are running on bare metal. The sum of rtorrent instances running on all the servers of all the networks are in the 5 digits (but not all of them pull from the same sources, a lot of them are grouped and a lot are independent or rented). Trust me when I say there is no chance, whatsoever, that a single autobrr instance can handle even a small portion of this. And even if it could, resource-wise, there's still the issue of the httprpc plugin being detectable when accessed remotely in a lot of these environments (corporate proxies involved), so the IRC monitoring has to be local. That's as much as I can say. :)

>As for building, you need Golang which the backend is built with, and Node/Yarn to build the web. Easiest is to build it with Docker, and there's a make build/docker for that. If you don't like docker, then build the web first, then build the backend.
There's make commands for that.

For the develop branch it wanted golang 1.19, Fedora 36 comes with 1.18.6 and for some of the web yarn dependencies my environment was getting newer packages than the version range required. Hence I decided not to start messing with that and get a VM building environment. No problem with docker since podman is compatible. The docker build takes care of the building environment dependencies inside the container?

>The BNC bits been talked about in the past in other issues and on Discord etc. Maybe it looks super simple from your side to implement that, but doing it reliably requires some effort, and since a single instance can handle lots of servers/clients and not bound 1-1 rutorrent and autodl-irssi per server, there's not a huge need for a BNC IMO.

As we speak I am currently running 83 instances of autobrr, serving 311 rtorrent instances through a bouncer just fine using the custom definitions. I migrated the lowest utilization server to test and if it works properly without crashing, or other issues, for a week, I'll start deploying to the rest of the servers.
Seriously the only thing that prevents the use of the bouncer (ZNC, I do not use and did not test anything else), is the hardcoded server hostname in the definition. So basic bouncer support is just allowing to override this and you achieve autodl-irssi functionality when it comes to using a bouncer. Not sure why this is not simple or reliable?

If you're talking about the requirement for bouncer hostname aliases, that can not be avoided without implementing bouncer aware network management and I agree that this is not simple but it is also not required. It's pretty simple to maintain a local hosts aliases file to append to /etc/hosts or DNS CNAMES to pull from anywhere ,that I use, if you really need to use a bouncer.

**Comment by zze0s** [comment]
That's quite the setup! Would love to chat about performance and help out with setup. If you're up for that, find me on `irc.autobrr.racing 6697`. General chat is `#chat`.

**Comment by zze0s** [comment]
Hi @Nodens- :wave: 

There's now a PR for initial bouncer support! https://github.com/autobrr/autobrr/pull/951

I've tested it for a bit and it does what it should but would appreciate if you are able to try it out as well.

The PR have database changes so backup before if you would need to revert later for some reason.

**Comment by Nodens-** [comment]
@zze0s I just saw this. I've been traveling due to some family issues. I'll test asap and get back to you.
