### ISSUE TITLE
No option to ignore SASL and use nickserv, prevents login on servers where SASL fails

### ISSUE THREAD

**Issue by Nodens-** [autobrr/autobrr#489]
**Describe the bug**

```
03:29:32.000DEBUG connect attempt 3
03:29:32.000TRACE Connecting to irc.myanonamouse.net:6697 (TLS: true)
03:29:33.000TRACE Connected to irc.myanonamouse.net:6697 (51.38.125.128:6697)
03:29:33.000TRACE --> CAP LS 302
03:29:33.000TRACE <-- :irc2.myanonamouse.net NOTICE Auth :*** Looking up your hostname...
03:29:33.000TRACE <-- :irc2.myanonamouse.net NOTICE Auth :*** Found your hostname (a.hostname.here) -- cached
03:29:33.000TRACE <-- :irc2.myanonamouse.net CAP 2DBAA07WT LS :away-notify extended-join account-notify sasl
03:29:33.000TRACE --> CAP REQ sasl
03:29:33.000TRACE <-- :irc2.myanonamouse.net CAP 2DBAA07WT ACK :sasl
03:29:33.000TRACE --> AUTHENTICATE PLAIN
03:29:33.000TRACE <-- AUTHENTICATE +
03:29:33.000TRACE --> AUTHENTICATE keyhere
03:29:33.000TRACE <-- :irc2.myanonamouse.net 904 2DBAA07WT :SASL authentication failed
03:29:33.000TRACE --> CAP END
03:29:33.000TRACE --> QUIT
03:29:33.000TRACE --> CAP END
03:29:33.000TRACE --> NICK Username
03:29:33.000TRACE --> USER Username s e Username
03:29:33.000TRACE <-- ERROR :Closing link: (unknown@a.hostname.here) [Client exited]
03:29:33.000TRACE ERROR received from server: Closing link: (unknown@a.hostname.here) [Client exited]
```

Notice that I am unable to use SASL on that particular server with mIRC as well. No idea why it also fails. Nickserv auth works fine but autobrr has no option to select and tries SASL only if the server aknowledges SASL capability.

**To Reproduce**
1. Try to login on MAM IRC.

No idea if SASL auth is broken just for me or there's an issue with their IRC daemon, but without an option to ignore SASL it's impossible to login.

**Expected behavior**
Ability to select auth mechanism.

**Comment by zze0s** [comment]
Hi! It's a known issue with MAM, and they run some ancient version of their irc server which I don't think helps. It works fine for main nick, but no ungrouped ones.

I have some ideas to test but haven't gotten to it yet but will update when I have some updates.

**Comment by Nodens-** [comment]
You could try not sending `QUIT` in response to failure but `AUTHENTICATE '*'` to abort. Then proceed with `NICK` and `USER`, and try authenticating with Nickserv. This should work according to the 3.1 capability specification.

**Comment by zze0s** [comment]
It's the underlying IRC library that handles it so we can't do much in autobrr, other than change or make it configurable how auth is made. It's been on the todo for quite some time but will try and finally get it done this weekend.

**Comment by ngovil21** [comment]
It seems like SASL is set optional [here](https://github.com/autobrr/autobrr/blob/72be86a34f2a79d11b8ee1ed56dcfc65ea301e43/internal/irc/handler.go#L162).

Work around for me right now is to leave the password blank and msg nickserv in the invite command

`/msg NickServ IDENTIFY [BOT_USERNAME] [BOT_PASSWORD]`
