### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by daomengRen** [autobrr/autobrr#49]
hi, are there any plans to get more information about torrent, such as imdb, etc., or is there any way to do this,thanks

**Comment by ludviglundgren** [comment]
Hi!

In what way? More like radarr/sonarr does? 

Maybe in the future, but if you need that then it's integrated with radarr and sonarr already so you can send stuff directly to them.

**Comment by daomengRen** [comment]
maybe can set it as an API, get this information through the API, and then run more custom commands

**Comment by daomengRen** [comment]
maybe this information can be used to filter the torrent, for example, the score of imdb, of course, this may not be useful

**Comment by daomengRen** [comment]
in addition, does the current custom commands support python or shell

**Comment by ludviglundgren** [comment]
If you have a more concrete use for something like that it's easier to discuss.

As for the custom commands, it's runs like a regular shell, so scripts or programs will work. There's docs coming about what variables are available when you run custom actions.

**Comment by daomengRen** [comment]
Ok, looking forward to the docs, I don’t know whether the variable includes every complete message content in the irc notification channel

**Comment by ludviglundgren** [comment]
> Ok, looking forward to the docs, I don’t know whether the variable includes every complete message content in the irc notification channel

The initial docs are now available and there's a section about available variables for exec actions at https://autobrr.com/docs/filters/actions#custom-commands--exec

I'll close this issue, and if you want to continue, then [open up a discussion](https://github.com/autobrr/autobrr/discussions/new) about it :)
