### ISSUE TITLE
BTN announce parsing tags missing out the Foreign tag.

### ISSUE THREAD

**Issue by KurtzPT** [autobrr/autobrr#498]
I mentioned this on discord channel but I'll make it official here. 

There's an issue with BTN announce parsing/interpreting tags.

At the moment, when a foreign release is announced in BTN it will have the following line:

`[ 2022 ] [ Season ] [ MKV | H.264 | WEB-DL | 1080p | Scene | FastTorrent | Foreign - 16 ] [ Uploader: xxx ]`

The "Foreign - 16"  value here will only appear when there's a foreign release (the number is an ID to a language, so the number will change)

I noticed that this value is being picked up by the BTN regex as "releaseTags", which then autobrr most likely discards it since the value is not a known field.

My suggestion would be making it so that autobrr puts this value available to be filtered in the TAGS field in filters, where one could put `*Foreign*` in the EXCEPT TAGS and avoid downloading foreign language releases for example.

**Comment by zze0s** [comment]
Partially solved with #506 where you can now filter on `releaseTags` with both match and except.
