### ISSUE TITLE
[FEATURE REQ] Tokyo Toshokan support

### ISSUE THREAD

**Issue by Drapersniper** [autobrr/autobrr#500]
**Is your feature request related to a problem? Please describe.** N/A

**Describe the solution you'd like**
Similar to SubPlease it would be great if support for Tokyo Toshokan was to be added

**Describe alternatives you've considered**
A Standalone script that processes entries just for this indexer, but it would be great if autobrr supported it natively to keep everything in a single place

**Additional context**

Website: tokyotosho.info
IRC: #tokyotosho-api

entry format: https://www.tokyotosho.info/pico/?sub%2FIRC_API

**Comment by zze0s** [comment]
Please open a new issue with the **Indexer Request** template instead with the proper info.
