### ISSUE TITLE
[FEATURE REQ] Watch dir Torrent Name

### ISSUE THREAD

**Issue by Tab-Top** [autobrr/autobrr#507]
Is it possible to **save** the torrent with the **original name** like auto-irssi?

Now:
autobrr-16724942.torrent
autobrr-31441925.torrent
autobrr-83239149.torrent
autobrr-1054017765.torrent

i need:
tracker-RELEASE.torrent

**Comment by KyleSanderson** [comment]
you can do this today (and many prior versions) with the exec command. invoke CP and use the text macros to accomplish this.

**Comment by Tab-Top** [comment]
in Filters --> Actions --> Exec ?

For example, What command should be written to save the Torrent ({{.TorrentName}}) in a /torrent/ folder?

**Comment by zze0s** [comment]
@Tab-Top  Once a new release is out, you'll be able to do it like this in the watch folder field:

`/mnt/watch/{{.Indexer}}-{{.TorrentName}}.torrent`
