### ISSUE TITLE
MAM - error downloading torrent file 

### ISSUE THREAD

**Issue by Cyprez13** [autobrr/autobrr#517]
**Describe the bug**
Having issues downloading MAM torrent file

**To Reproduce**
1. Configure Indexer - MAM and Cookie (mam_id) 
2. Enable IRC monitoring
3. Wait for new release
4. Error - error downloading torrent file for release / status code: 401

**Expected behavior**
The torrent should be injected to qBittorrent

**Screenshots**
![Screen Shot 2022-10-28 at 1 11 42 PM](https://user-images.githubusercontent.com/89241372/198420803-2dda3431-51a5-4207-aab0-f6fbeba57716.png)

**Additional context**
Can confirm that the Cookie (mam_id) is valid - works with Prowlarr

**Comment by Kakise** [comment]
You need to create a new session on your security page in your profile option and use this cookie.

Autobrr doesn't add "mam_id" to the session string so the resulting cookie in your indexer should be: "mam_id=<session_cookie>;"

**Comment by Cyprez13** [comment]
Thanks Kakise.

Got this to work by putting mam_id=_<session_cookie>_  in my MAM indexer.

<img width="670" alt="Screen Shot 2022-10-30 at 10 50 36 PM" src="https://user-images.githubusercontent.com/89241372/198872651-ddfb2223-eeeb-44d5-bfbc-f610bf6216f3.png">
