### ISSUE TITLE
[FEATURE REQ] Filter based on number of files in torrent

### ISSUE THREAD

**Issue by Ckrisirkc** [autobrr/autobrr#530]
**Is your feature request related to a problem? Please describe.**  

Right now I'm downloading all weekly episodes for an airing show. Once the entire season of a show is available there will often be batches for the show, which consist of all the episodes in a single torrent.  
While I do want individual episodes, I do not want to re-download all of them in a batch, which is currently what happens as I am not able to filter these batches out.  

**Describe the solution you'd like**  

A filter for the number of files in a torrent would solve this issue.  
I've looked into trying to make a pull request myself, however I'm not familiar enough with the way the autobrr db/schema is setup.  
I was able to grab the number of files in a torrent via modifying [internal/domain/release.go](https://github.com/autobrr/autobrr/blob/develop/internal/domain/release.go#L368).
Around line 368:
```go
. . .
r.NumFiles = len(torrentMetaInfo.Files)
. . .
```
Would give the number I'm looking to filter on.  
  
This filter could go under the General or Advanced filter tabs. It would have two filter fields for max/min number of files in torrent.  
In my attempted PR I created a filter for "Max number of files", but I think it would be helpful if we could filter max/min instead; since it's possible to want to filter different actions based on whether it is a batch (number of files >1) or not, and then take actions accordingly. 

**Describe alternatives you've considered**  

Filtering based on max size doesn't work, as different shows will have different average sizes. I use a max of 5GB, which works for some batches, but there are still a number that wind up being less than that.  

Another alternative I've considered is running an external script to do this check.  
Using the same library as autobrr, I can get the number with the following snippet:
```go
package main

import (
    "fmt"
    "github.com/anacrolix/torrent/metainfo"
    )

func main() {
    // Currently uses a static file, would need to pull from args for use.
    meta, err := metainfo.LoadFromFile("test.torrent")
    if err != nil {
        fmt.Printf("Error not nil? %+v\n", err)
    }
    torrentMetaInfo, err := meta.UnmarshalInfo()

    // Print the number of files
    fmt.Printf("%v\n", len(torrentMetaInfo.Files))
    // 12  

    // Print the file array itself
    fmt.Printf("%+v\n", torrentMetaInfo.Files)  
    // [{Length:347344547 Path:[FileNameAppearsHere.mkv] PathUtf8:[]} {. . .} *repeats for all 12 files* ]
}
```
An external script that does this would probably be the next most viable approach. Something like `FileFilter.exe --max 1 /path/to/temp.torrent` with other options for `--min #` or `--exact #`   

**Additional context**  

Since I'm already downloading all the episodes individually, I do have a folder they're grouped in. Given there are no v2 releases, I'll likely try to point the batch torrents at the existing files in the future, but I would still need to filter the release as a batch or not before taking action.

**Comment by zze0s** [comment]
Hello! That's a lot of added complexity for simply using the filter and doing this: `Season: 1-99` and `Episodes: 1-99`. That way it will always grab **episodes only.**

If you or someone else would want **only seasons** then settings `Season: 1-99` and `Episodes: 0`, explicitly set to 0.

**Comment by Ckrisirkc** [comment]
It wasn't clear that setting the season/episodes would work like that.  
That would certainly be an alternative solution to this, thanks! Will close this request.

**Comment by Ckrisirkc** [comment]
Thought it would be worth posting here just in case anybody else runs into this issue, but the proper way for episodes seems to be `Season: 0-99` along with `Episodes: 1-9999`.  
Using `Season: 1-99` resulted in:
```
"release rejected: season not matching. got: 0 want: 1-9999"
```
Even though the release is -technically- season 1, I am guessing that it isn't parsing any 'season' and so it defaults to `0`.
