### ISSUE TITLE
[FEATURE REQ] Add support for native ntfy notifications

### ISSUE THREAD

**Issue by Kjeldgaard** [autobrr/autobrr#535]
Hi,

It like to request native support for [ntfy](https://github.com/binwiederhier/ntfy) notifications.

Currently, it is possible to execute a custom exec actions to send a ntfy notifications.

**Comment by zze0s** [comment]
Hi!

It's been on the TODO for a while to implement webhook/http notifications for a lot of flexibility. Lets see if that can get some prio in the near future.

**Comment by onedr0p** [comment]
Having a generic webhook (like radarr/sonarr) for notifications would be great, something that can sent a post request with the follow data to some endpoint:

```json
{
  "release": "Blah",
  "status": "Approved",
  "indexer": "MyAwesomeIndexer",
  "filter": "BestDamnFilterEver"
}
```

**Comment by onedr0p** [comment]
I think one of these issues can be close... https://github.com/autobrr/autobrr/issues/867 and title updated to support more notification providers.
