### ISSUE TITLE
AvistaZ RSS size filter issue

### ISSUE THREAD

**Issue by Cyprez13** [autobrr/autobrr#536]
**Describe the bug**
Autobrr is parsing AvistaZ size incorrectly

**To Reproduce**
1. Create an AvistaZ RSS
2. Create a filter with size requirements
3. When a new release is picked up, review the torrent size in RSS and compare to Autobrr logs

**Expected behavior**
Filter size correctly

**Screenshots**
<img width="1101" alt="Screen Shot 2022-11-12 at 8 28 54 PM" src="https://user-images.githubusercontent.com/89241372/201462871-486411f6-3e5e-44f5-b040-a4183c8974cf.png">
<img width="1101" alt="Screen Shot 2022-11-12 at 8 28 33 PM" src="https://user-images.githubusercontent.com/89241372/201462873-6e642f45-bcb5-488a-829a-6c9b083d69ed.png">

**Logs**
AvistaZ RSS
Size: 20.2 GB

```
<title>Get On A Flat S01 2022 1080p KKTV WEB-DL AAC x264-ADWeb</title>
<category>TV-Show</category>
<link>https://avistaz.to/torrent/219017-3821567ab553a87c09628943e51064f4caa098e4</link>
<guid isPermaLink="true">https://avistaz.to/torrent/219017-3821567ab553a87c09628943e51064f4caa098e4</guid>
<description><![CDATA[<p><strong>File Name</strong>: Get On A Flat S01 2022 1080p KKTV WEB-DL AAC x264-ADWeb<br><strong>Type</strong>: TV-Show<br><strong>Size</strong>: 20.2 GB<br><strong>Uploaded</strong>: Nov 12, 2022<br><strong>Seed</strong>: 21 | <strong>Leech</strong>: 4 | <strong>Completed</strong>: 25<br><strong>Uploader</strong>: Anonymous</p><p><strong>Rip Type</strong>: WEB-DL<br><strong>Video Quality</strong>: 1080p<br><strong>Video Resolution</strong>: 1920x1080</p><p><strong>TV Show</strong>: Full SeasonSeason: 1   <p><a href="https://avistaz.to/tv/43273-get-on-a-flat" title="Get On A Flat (2022)">Get On A Flat (2022)</a><br><br><br>TheMovieDB: <a href="https://anon.to?https://www.themoviedb.org/tv/209736" target="_blank">209736</a><br>TheTVDB: <a href="https://anon.to?https://www.thetvdb.com/?id=426130&tab=series" target="_blank">426130</a><br>Runtime: 42m 59s<br>Subtitles: Chinese, English<br></p>]]></description>
<dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Anonymous</dc:creator>
<pubDate>Sat, 12 Nov 2022 03:45:28 +0100</pubDate>
<enclosure
url="https://avistaz.to/rss/download/[REDACTED]/219017-get.on.a.flat.s01.2022.1080p.kktv.web.dl.aac.x264.adweb.torrent" 
type="application/x-bittorrent" 
length="39399" 
/>
```

Autobrr logs
Size: 39399

```
release.store: &{ID:1808 FilterStatus:FILTER_APPROVED Rejections:[] Indexer:rss-avistaz FilterName:AvistaZ Protocol:torrent Implementation:RSS Timestamp:2022-11-12 02:49:40.279536724 +0000 UTC m=+688691.738870535 GroupID: TorrentID: TorrentURL:https://avistaz.to/rss/download/[REDACTED]/219017-get.on.a.flat.s01.2022.1080p.kktv.web.dl.aac.x264.adweb.torrent TorrentTmpFile: TorrentDataRawBytes:[] TorrentHash: TorrentName:Get On A Flat S01 2022 1080p KKTV WEB-DL AAC x264-ADWeb Size:39399 Title:Get On A Flat Category:TV-Show Season:1 Episode:0 Year:2022 Resolution:1080p Source:WEB-DL Codec:[x264] Container: HDR:[] Audio:[AAC] AudioChannels: Group:ADWeb Region: Language: Proper:false Repack:false Website: Artists: Type: LogScore:0 IsScene:false Origin: Tags:[] ReleaseTags: Freeleech:false FreeleechPercent:0 Bonus:[] Uploader:Anonymous PreTime: Other:[] RawCookie: AdditionalSizeCheckRequired:false FilterID:6 Filter:0xc0003e4900 ActionStatus:[]}
```

**Additional information**

- Tried to set filter to 20 GiB
- Another torrent with a size of 33.77 GiB got approved but I didn't have logs at the time

**Comment by zze0s** [comment]
Hi! Don't they have the `<torrent>....</torrent>` object in item like the other sites in their network? At least PHD does, and we parse the size from that.

And what version are you on? There was improvements to RSS parsing in 1.8.0, 1.8.1, 1.9.0 and 1.10.0, so if you run something older please update.

**Comment by Cyprez13** [comment]
Hey zze0s,

Yes they do:

```
<torrent>
<fileName>Get On A Flat S01 2022 1080p KKTV WEB-DL AAC x264-ADWeb</fileName>
<contentLength>21666686721</contentLength>
<infoHash>3821567ab553a87c09628943e51064f4caa098e4</infoHash>
<trackers>
<group order="ordered">
<tracker seeds="41" peers="2">https://tracker.avistaz.to/[REDACTED]/announce</tracker>
</group>
</trackers>
</torrent>
```

I'm still on v1.6.0, I'll upgrade once it's available on TrueCharts on TrueNAS. Or if I have time, spin up a docker container.

Thanks,

cyprez

**Comment by zze0s** [comment]
Great, then that's already supported in newer versions.

Looks like TrueCharts already have the [latest version ](https://github.com/truecharts/charts/blob/master/charts/stable/autobrr/values.yaml#L4), so try and update because there's a lot of improvements since v1.6.0 :smiley:

**Comment by Cyprez13** [comment]
Thanks mate. Just updated, will test and let you know if there's any issues.
