### ISSUE TITLE
Max daily downloads ignored with multiple filters.

### ISSUE THREAD

**Issue by p8757181** [autobrr/autobrr#546]
**Version**

v1.11.0

**Describe the bug**

The max daily downloads is ignored when used with multiple filters.
I don't believe it is time zone related for me (I've asked on discord), as I'm seeing the limit be broken consistently across days by a large amount (its set to 3 downloads, and its downloaded over 10 in a few hours).

**To Reproduce**

1. Create a filter with *arr in, set to highest priority.
2. Create a second filter without arr in, set to a lower priority, have it do downloads, but a limit of 3 daily downloads.
3. Hook both up to same indexer.
4. Release comes in, is rejected by *arr, downloaded by second filter.
5. Repeat step 4, and the limit will be ignored.

**Expected behavior**

I would expect the max download number to be respected, downloading 3 things then stopping.

**Additional context**

I've done a few tests:

1. Two filters together: Download limit ignored.
2. Download filter by itself: Download limit respected.
3. Download filter by itself, then together : If I only run the download filter, let it reach max downloads, then enable the *arr filter again, everything works as expected and the limit is respected.

I should probably test doing the download filter first, then the TV filter second, as I expect the ordering is the issue.

zze0s on discord said the actions store the state, which should prevent this, but as far as I can see in the part here: 

https://github.com/autobrr/autobrr/blob/a93b54bbbc757ef297a18fd9f080ca981189b359/internal/database/filter.go#L1016-L1050

the number of downloads is counted with the filter ID on the release table, not the actions.
That will cause issues because the releases are only stored with the first filter ID that passes, not all of them / the last one:

https://github.com/autobrr/autobrr/blob/a93b54bbbc757ef297a18fd9f080ca981189b359/internal/release/service.go#L133-L142

So you'd end up with a release passing on the *arr filter, being stored with that filter ID, then downloaded by the second filter.
The next release would then try and count the number of releases for the second filter and get 0, as that filter ID was not stored, when it should be 1.

That would explain why the limit works when the filters are combined after the download limit is reached (test 3 above): The DB does have 3 entries with that filter ID in, whereas if they always run together its always empty for that ID.

**Comment by zze0s** [comment]
Appreciate the digging you did on this. It's more clear now that it's an issue.

Maybe a we need to use `release_action_status` table and check the filter, timestamp, status = PUSH_APPROVED. :thinking: 

Will have to think about this and what we do to properly fix it.
