### ISSUE TITLE
Perfect FLAC filters and score above 100

### ISSUE THREAD

**Issue by gl0ryus** [autobrr/autobrr#576]
**Version**
1.12

**Describe the bug**
On the music tab

**To Reproduce**
1. Select perfect flac check box
2. Edit any other relevant numbers

**Expected behavior**
When selecting Perfect Flac, other choices should be limited.
I.E. Log/Cue/Log Score (which can also, Format and Quality.
Media and Type are probably safe to keep as choices.

**Screenshots**
![image](https://user-images.githubusercontent.com/96798013/209237172-2a7045db-1905-45b9-950e-9a8730b658af.png)

**Comment by zze0s** [comment]
Behind the scenes the other options get ignored then perfect flac is selected. But we should make the fields disabled to be more clear.
