### ISSUE TITLE
Drop down menu interactions

### ISSUE THREAD

**Issue by gl0ryus** [autobrr/autobrr#577]
**Version**
1.12

**Describe the bug**
When using a drop down menu, you can click on the down arrow and meditatively click away without issue. But if you click on a choice within that menu you have to click the up arrow to exit out and make another choice.

**To Reproduce**
[See video](https://cdn.discordapp.com/attachments/881214803325091841/1055617991930294422/Untitled_video_-_Made_with_Clipchamp.mp4)

**Expected behavior**
If the user clicks away from the drop down menu it should exit.

**Comment by s0up4200** [comment]
Clicking outside the form works when you tick `Select all`, but not when you tick any of the other options.
Maybe the solution lies there somewhere.
