### ISSUE TITLE
[FEATURE REQ] - Transmission Seed Ratio/Time per action

### ISSUE THREAD

**Issue by carlosjfcasero** [autobrr/autobrr#581]
As other clients already have, it would be nice if we were able to set Seed Ratio and Seed Time in the action Tranmission.

Thanks

**Comment by mokahless** [comment]
Why was this closed? If it's not possible, I guess it can't be helped but it would be nice to know if that's the reason. I was looking around and found this before opening my own issue request for this feature.

**Comment by zze0s** [comment]
> Why was this closed? If it's not possible, I guess it can't be helped but it would be nice to know if that's the reason. I was looking around and found this before opening my own issue request for this feature.

No idea, wasn't me who closed it. We can reopen it sure.
