### ISSUE TITLE
[FEATURE REQ] Email as a notifier, or perhaps Shoutrrr

### ISSUE THREAD

**Issue by sentriz** [autobrr/autobrr#583]
hi! thanks for a very nice project. currently you support Telegram, Discord, and Notifiarr

I don't use any of these currently, but I do use email. are there plans to support it / SMTP? if so I'd be happy help add it myself

------------

alternatively there is a go library called Shoutrrr (inspired by [apprise](https://github.com/caronc/apprise))

https://containrrr.dev/shoutrrr/v0.5/

which supports Telegram, Discord, and many more (like email)

users just provide their own simple notification URIs like `discord://token@channel`

**Comment by zze0s** [comment]
Hi! Hope you're enjoying it!

The initial notifications implementation was actually with shoutrrr. The premise of the library was good, but while implementing it I struggled to get it working and caused more headache than needed. Docs were meh and reading the code wasn't much clearer, which is uncommon for Go projects. Anyhow, I ripped it out and started from scratch with our own implementation for notifications.

Maybe I'll should take a look at it again.

**Comment by Metigoth** [comment]
https://github.com/caronc/apprise 
I prefer pushover.

**Comment by buroa** [comment]
+1

**Comment by sam272** [comment]
+ 1 for email notifications like Radarr/Sonarr
