### ISSUE TITLE
AlphaRatio bug

### ISSUE THREAD

**Issue by techguruz** [autobrr/autobrr#589]
**Version**
v1.12.1
**Describe the bug**
Small sample from my log but shows what I'm talking about. I've tried using bare minimum options but it doesn't seem to like the format. 
10:10:26.000
DEBUG
[AutoDL]-[Music]-[2520136]-[ 1 | 106 | 0 | 1 ]-[Greg_Jake_-_Spinnin_Sessions_502-CABLE-12-23-2022-TALiON]
10:10:26.000
TRACE
announce: process line: [New Release]-[Music]-[Greg_Jake_-_Spinnin_Sessions_502-CABLE-12-23-2022-TALiON]-[URL]-[ https://alpharatio.cc/torrents.php?id=2520167 ]-[ 2520136 ]
10:10:26.000
TRACE
announce: queued line: [AutoDL]-[Music]-[2520136]-[ 1 | 106 | 0 | 1 ]-[Greg_Jake_-_Spinnin_Sessions_502-CABLE-12-23-2022-TALiON]
10:10:26.000
DEBUG
line not matching expected regex pattern: [New Release]-[Music]-[Greg_Jake_-_Spinnin_Sessions_502-CABLE-12-23-2022-TALiON]-[URL]-[ https://alpharatio.cc/torrents.php?id=2520167 ]-[ 2520136 ]
10:10:26.000
TRACE
announce: process line: [AutoDL]-[Music]-[2520136]-[ 1 | 106 | 0 | 1 ]-[Greg_Jake_-_Spinnin_Sessions_502-CABLE-12-23-2022-TALiON]
10:10:26.000
DEBUG
line not matching expected regex pattern: [AutoDL]-[Music]-[2520136]-[ 1 | 106 | 0 | 1 ]-[Greg_Jake_-_Spinnin_Sessions_502-CABLE-12-23-2022-TALiON]

**To Reproduce**
set up AR and the problem should be there from the start.

**Comment by zze0s** [comment]
It got fixed in https://github.com/autobrr/autobrr/pull/582 and available on the `develop` tag if using docker. Otherwise wait for a release scheduled for tomorrow.
