### ISSUE TITLE
Cannot add IRC / Clients (403 error)

### ISSUE THREAD

**Issue by GitHubMilo** [autobrr/autobrr#59]
This is setup using the downloaded binary, and installed as a service on Linux.

I keep hitting these 403 errors when using the service and trying either add an IRC network, or a client (like radarr / sonarr).

Any suggestions?

```
    at APIClient.ts:32
    at s (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at APIClient.ts:21
```

DEBUG logs don't appear to provide anything useful for this.

**Comment by GregTroar** [comment]
Could you try to update your config.toml with TRACE log instead and relaunch ??

**Comment by GitHubMilo** [comment]
> Could you try to update your config.toml with TRACE log instead and relaunch ??

Unfortunately still nothing more in the log.
This is all I get with "TRACE" on:
`{"level":"debug","time":"2022-01-01T18:37:48Z","message":"Starting autobrr"}
{"level":"debug","time":"2022-01-01T18:37:48Z","message":"Log-level: TRACE"}
{"level":"info","time":"2022-01-01T18:37:48Z","message":"Starting server. Listening on 10.20.20.140:9999"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/alpharatio.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/beyondhd.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/btn.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/emp.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/filelist.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/gazellegames.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/hd-torrents.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/iptorrents.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/nebulance.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/orpheus.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/ptp.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/red.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/superbits.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/torrentleech.yaml"}
{"level":"trace","time":"2022-01-01T18:37:48Z","message":"parsing: definitions/uhdbits.yaml"}
{"level":"info","time":"2022-01-01T18:37:48Z","message":"Loaded 15 indexer definitions"}`

Then I see this in the front-end:
[https://imgur.com/a/CEfhOuq]

**Comment by GregTroar** [comment]
Got exact same issue myself with one of my server...it seems itay have something to do with worker session I will try to send u a screenshot later on

**Comment by GregTroar** [comment]
In Chrome try to click F12 then go to Application and Service Workers if you see one try to click unregister.
Let me know if this works as on my side I re-install completely the OS as I did not have this solution before.

**Comment by brettpetch** [comment]
https://github.com/autobrr/autobrr/pull/67
