### ISSUE TITLE
HD-Torrents Bug

### ISSUE THREAD

**Issue by techguruz** [autobrr/autobrr#591]
**Version**
v1.12.1

**Describe the bug**
Freeleech percentage not working.

**Comment by zze0s** [comment]
Not a bug. HD-Torrents does not announce freeleech. It's available only on their site.

They do freeleech for their internals so the solution is for you to check what their internal groups are and make a `Match groups` filter with those.

**Comment by techguruz** [comment]
That's helpful to know, I have been sitting in the announce channel for ages watching to see what is actually announced. It would be great if we could get some documentation about which filters fork for which trackers etc.

**Comment by zze0s** [comment]
That's slowly being worked on :)

For now you can check the indexer definitions like https://github.com/autobrr/autobrr/blob/develop/internal/indexer/definitions/hd-torrents.yaml#L60 and see what the announce we expect and what we capture.

**Comment by techguruz** [comment]
thanks buddy looks like I have some reading to do.
