### ISSUE TITLE
[FEATURE REQ] Indexer disables IRC Network

### ISSUE THREAD

**Issue by techguruz** [autobrr/autobrr#592]
Would be great if when you disable an indexer it parts you from the IRC network/channel. This would make it a lot easier when trying to figure out why certain filters are not working since you won't have so many different channels spamming the logs.

**Comment by zze0s** [comment]
The way it currently works is it will only grab filters for enabled indexers, so if you disable the indexer it won't filter for that one any more.

You can also go into Settings -> Irc networks and click the three dots on the network, edit then disable it there. Just beware that quite a few indexers share same networks. P2P-network is a popular one that many use.

**Comment by techguruz** [comment]
Yeah I understand that the filters need to be enabled but say I am working on testing a filter for an indexer on P2P-network it would be great if disabling the other trackers parted from that channel so you don't see all the announces in the log for things that you have no active filters for.

**Comment by martylukyy** [comment]
I feel like what you want could be achieved by generating a log file (in case you don't already do) and then
filtering the log file for lines containing `"module":"release"` and `"module":"filter"`.
Additionally you can filter by `"indexer":"<insert you indexer identifier here>"`
That way you only get announce lines processed by a matching filter for that indexer.
If desired you can also can get a little bit more out of the logs by setting the loglevel to `TRACE` in case you haven't done that yet.
Read more about this here: https://autobrr.com/configuration/autobrr

**Comment by techguruz** [comment]
yeah, that's currently what I am doing but only turned on the log files while I'm testing filters since they could grow quite fast.

**Comment by martylukyy** [comment]
Don't worry about the log size too much since autobrr will create a maximum of 4x 50MB log files.
It has log rotation built in.

**Comment by techguruz** [comment]
perfect I can leave it on all the time then :)
