### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ludviglundgren** [autobrr/autobrr#6]
Start with some basic documentation to get up and running, how filters work etc.

**Comment by rouggy** [comment]
How to install ?!

**Comment by ludviglundgren** [comment]
Hi! I plan on writing some proper documentation in the coming weeks.

Currently it's integrated into Swizzin for easy install, but binaries and docker install guides are coming.

**Comment by rouggy** [comment]
Ok i will wait for the docs.

Thanks

**Comment by brettpetch** [comment]
vote to close based on https://autobrr.com/ now being available.

**Comment by GregTroar** [comment]
Yep
