### ISSUE TITLE
TorrentSeeds is broken again on 1.13.0

### ISSUE THREAD

**Issue by phenomeni** [autobrr/autobrr#610]
**Version**
1.13.0

**Describe the bug**
Hi .. I'm the guy who reported the broken TorrentSeeds Bug after the last update. It's broken again on 1.13.0 : (

**Comment by martylukyy** [comment]
Hi!

Since I couldn't reproduce your issue may I ask what exactly isn't working?

**Comment by phenomeni** [comment]
Thank you for the response!

Readded the tracker(s) and irc to autobrr, then restarted the clients too - and voila it works.

Weird, but it works!

Closing this as a bug. Thank you for your time!
