### ISSUE TITLE
[FEATURE REQ] Filter for language

### ISSUE THREAD

**Issue by buzzqw** [autobrr/autobrr#613]
Hi
will be possible to filter by language the series/movie ?

i suggest a field where to specify allowed languages
thanks

**Comment by zze0s** [comment]
Hi! We only grab info from release names and no outside sources so we are limited to what is in the release name. Properly named releases will have language in there and we already parse it, but it's not exposed as a filter.

I'll put it on the todo.

**Comment by buzzqw** [comment]
Hi
how language filter is supposed to work ?
for Italian language the filter say "iTALiAN"  , but for italian release is "ITA" not iTALiAN .
Would be better to let user write own tongue sigle ?

thanks
BHH
