### ISSUE TITLE
Filters: Max Downloads Per Hour not honored

### ISSUE THREAD

**Issue by Starblaster100** [autobrr/autobrr#643]
**Version**
v1.15.0

**Describe the bug**
After setting my filter to only download 1 release per hour, autobrr pushed multiple releases to my download client, not honoring the 1 Max Downloads Per Hour setting I enabled in the filter.

Release log shows grab dates as:
- 2023-01-08T06:47:38-08:00
- 2023-01-08T06:52:18-08:00
- 2023-01-08T06:59:19-08:00

**To Reproduce**
- Enable 1 download client: qBit. No max active downloads set
- Create 1 new filter: 
  - Max downloads: 1; 
  - Max downloads per: Hour; 
  - Resolutions: 1080p, 1080i; 
  - Match Categories: Season
  - Action: Type: qBittorrent, select client

I don't think resolution or category will affect the bug, but included as this is what I had it set to.

Wait for season packs to come in via IRC in quick succession. All are added to qBit instead of only 1 per hour

**Expected behavior**
Only 1 season should have been pushed to qBit per hour. Others should have been ignored.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Not sure this is applicable, but adding anyway
 - OS: Docker, running on Linux
 - Browser: Chrome
 - Version: Version 108.0.5359.124 (Official Build) (arm64)

**Additional context**
N/A

**Comment by s0up4200** [comment]
Are you setting such limits on more than one filter by any chance?
Related: https://github.com/autobrr/autobrr/issues/546

**Comment by Starblaster100** [comment]
Thanks for the reply
No, I only have 1 filter and one download client

**Comment by Starblaster100** [comment]
Thanks! Will test again tonight, and report back with the results
