### ISSUE TITLE
[FEATURE REQ] More Examples

### ISSUE THREAD

**Issue by buzzqw** [autobrr/autobrr#644]
Hi all

for newby user or without experience in regexp the many and more filter in autobrr could be cumbersome to understand the many implication of each filters.

would be possibile to add some more examples (with pics) how to build a filter for series ?

thanks
BHH

**Comment by s0up4200** [comment]
Hello! You don't need to use regex with autobrr at all.

- Use the `Movies/Shows` field and write a comma separated list of the shows or movies you want to monitor. (Make separate filters for shows and movies.)
- Set your desired resolution(s) in the `Resolution` field.
- Select `WEB` `WEB-DL` and `WEBRip` in the `Sources` field if you only want that.
- Alternatively use `Categories` as well. You can find out which categories your indexers use [here](https://autobrr.com/filters/categories).
- Set up your `Actions`

The [docs ](https://autobrr.com/filters/)have good explanations of the different fields as well as some [examples](https://autobrr.com/filters/examples). Everything you need is in there.

Come to our [Discord](https://discord.gg/WQ2eUycxyT) if you need any help 😃

**Comment by buzzqw** [comment]
let's say i want to download a tv series called "Santa isn't coming this year"  and i want the italian series. The title could be in english or italian, that's not matter (i would specify it on "Movie / Shows" but the series must be in italian language.

in **General** tab
- i put on "Filter Name" : "Santa isn't coming this year"
- i specify all indexer to use
- i don't specify size, delay, priority, max download or Max downloads per

in **Movie and TV tab**
- in "Movies / Shows" i put "Santa isn't coming this year" 
- in years i don't specify anything
- in season i want all season , the first to the last, and since the serie is running.. i don't know the last.. should i put "1-100" ??
- in episodes i don't specify anything. I need from the first episode
- on Quality .. i put only resolution as "2160p" and "1080p"

on **Advanced**
- on Match language specify "iTALiAN" even if the correct tag is "ITA".  Or i can specify "ITA"  on what field ?

Is this the correct way to add a series ?

thanks
BHH

**Comment by buzzqw** [comment]
any hint?
thanks

BHH
