### ISSUE TITLE
Unable to clear log score once set

### ISSUE THREAD

**Issue by Audionut** [autobrr/autobrr#650]
Pretty much the title.

You can leave the log score empty when creating a filter just fine, but if you save a filter with a log score, you cannot then clear the log score and save the filter.

Error
{"message":"json: cannot unmarshal string into Go struct field Filter.log_score of type int"} 

edit: Same problem when trying to clear 'max downloads'.

**Comment by s0up4200** [comment]
What version are you on?

**Comment by Audionut** [comment]
1.15.0
