### ISSUE TITLE
Windows Deluged error : Temp\autobrr-1036921526: bencode: syntax error (offset: 0): unknown value type 'I'

### ISSUE THREAD

**Issue by Zauxst** [autobrr/autobrr#655]
**Version**
latest, last night downloaded
Vs: 1.15.0
Commit: 5c402b6d6ce6a812b9b77e65634ab5372e5c6bb5

**Describe the bug**

A filter with 3 actions that push to Sonarr, Radarr, or directly to Deluge. Also looks for freelech, nothing else is configured. Freeleech box is also empty to ensure it does the default value 100%

Filelist indexer.
```
Type: DELUGE_V2
Client: Deluge v2
Filter: freeleech
Time: 2023-01-16 04:32:06
Rejected: All attempts fail:
#1: metainfo could not load file contents: C:\Users\*****\AppData\Local\Temp\autobrr-1036921526: bencode: syntax error (offset: 0): unknown value type 'I'
#2: metainfo could not load file contents: C:\Users\*****\AppData\Local\Temp\autobrr-1036921526: bencode: syntax error (offset: 0): unknown value type 'I'
#3: metainfo could not load file contents: C:\Users\*****\AppData\Local\Temp\autobrr-1036921526: bencode: syntax error (offset: 0): unknown value type 'I'
```

logs:

```

INFO
Matched 'TORENT_NAME_CENSORED' (freeleech) for fl
04:41:16.000
DEBUG
release.store: &{ID:30 FilterStatus:FILTER_APPROVED Rejections:[] Indexer:fl FilterName:freeleech Protocol:torrent Implementation:IRC Timestamp:2023-01-16 04:41:16.2170807 +0200 EET m=+92470.782890501 GroupID: TorrentID:814329 TorrentURL:CENSORED_TORRENT_NAME_URL TorrentTmpFile: TorrentDataRawBytes:[] TorrentHash: TorrentName:TORENT_NAME_CENSORED Size:2350000000 Title:TORENT_NAME_CENSORED Category:Seriale HD Categories:[] Season:1 Episode:1 Year:0 Resolution:720p Source:WEB-DL Codec:[H.264] Container: HDR:[] Audio:[DDP Atmos] AudioChannels:5.1 Group:playWEB Region: Language:[] Proper:false Repack:false Website: Artists: Type: LogScore:0 IsScene:false Origin:Internal Tags:[] ReleaseTags: Freeleech:true FreeleechPercent:0 Bonus:[Freeleech] Uploader:Anonymous PreTime: Other:[] RawCookie: AdditionalSizeCheckRequired:false FilterID:1 Filter:0xc0008af200 ActionStatus:[]}
```

**To Reproduce**

- Windows 10
- Deluged v2 (+web plugin, Sonarr uses web plugin this uses Daemon)
- Standard configuration. Just actions configured.
- I don't know anything else...

**Expected behavior**

Actually working.......

This doesn't seen to be working properly at all... Also, Sonarr uses Deluge Web instead of Daemon, directly...

**Comment by Zauxst** [comment]
I got the same issue with qBittorrent

```
Type: QBITTORRENT
Client: qBittorrent
Filter: freeleech
Time: 2023-01-16 22:11:05
Rejected: error downloading torrent file for release: REDACTED_TORRENT NAME.AAC2.0.H.264-B2B: All attempts fail:
#1: metainfo could not load file contents: C:\Users\REDACTED_USER\AppData\Local\Temp\autobrr-2765442832: bencode: syntax error (offset: 0): unknown value type 'I'
#2: metainfo could not load file contents: C:\Users\REDACTED_USER\AppData\Local\Temp\autobrr-2765442832: bencode: syntax error (offset: 0): unknown value type 'I'
#3: metainfo could not load file contents: C:\Users\REDACTED_USER\AppData\Local\Temp\autobrr-2765442832: bencode: syntax error (offset: 0): unknown value type 'I'
```

**Comment by s0up4200** [comment]
Hi there. I am 90% sure this is because you have the wrong passkey added to autobrr.

Go to `/my.php` on FL and scroll down to where you see "Reset passkey".

<img width="915" alt="image" src="https://user-images.githubusercontent.com/18177310/212766817-6621a8c1-e715-4916-b992-49ee0cf2fcfe.png">

If you dont see a passkey, then manually download a torrent, add it to your download client and copy the passkey from it. In qBIttorrent (Right click and copy, then grab the passkey from the URL in Notepad or something):

<img width="433" alt="image" src="https://user-images.githubusercontent.com/18177310/212766999-60e709fe-d674-4334-b588-08eebe38e31b.png">

**Comment by s0up4200** [comment]
Did you figure it out @Zauxst ?

**Comment by Zauxst** [comment]
God damn I am stupid. I copied the Passkey from the Prowlarr proxy instead of the proper one... Thanks... works like a charm... I am stupid....
