### ISSUE TITLE
[TorrentBytes] dh key invalid length

### ISSUE THREAD

**Issue by Motophan** [autobrr/autobrr#665]
**Version**
1.16.0

**Describe the bug**
Autobrr is working correctly 
torrentbytes has a valid tls certificate but an invalid dh key length on their https announce url
this means that the announce url given in irc will give you a http tracker as this is the (torrentbytes) sysadmins work around instead of the url that autobrr tries to use.
Skipping tls verification in libtorrent will not work because libtorrent relies on openssl, and openssl is refusing the key length on a "technically valid" tls cert. Anyone who uses swizzin will have a libtorrent 1.x setup due to the bugs involved w/ libtorrent 2.x and skipping verification wont work

I know the ideal solution is for the sysadmin for torrentbytes to replace the ssl with a proper one

**To Reproduce**
1. curl -k https://www.torrentbytes.net/download.php?id=3473665
2. curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

**Expected behavior**
Exactly what is happening, which is undesired. 

I accept that this could be closed as "wont fix" because everything in the toolchain is working as intended. 
Please consider an exception to either

1. rewrite announce url to http one in .torrent
2. force autobrr to download the announce url which feeds a http tracker

Thanks for your time

**Comment by s0up4200** [comment]
I guess we could solve this by adding an optional baseURL without SSL.
That way you can change to the nonSSL version in the UI. Just like with the numerous Torrentleech URLs.

**Comment by zze0s** [comment]
Fixed by #705 by using the link for the http only torrents.
