### ISSUE TITLE
"Approved" Notification After Stalled Deleted

### ISSUE THREAD

**Issue by CarlitoGil** [autobrr/autobrr#671]
**Version**
1.16.0

**Describe the bug**
After the qBittorrent action is done reannouncing and the stalled torrent is deleted the notification shows status "Approved" instead of an error or warning.

**To Reproduce**
1. Use qBittorrent Action.
2. Enable "Delete stalled".
3. Set fewer reannounce attempts and/or frequency to stall sooner.
4. Enable Discord notifications "Push Approved" and "Push Error".

**Expected behavior**
Perhaps a yellow notification with status "Stalled". 
Not a green "Approved" notification.

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Chrome

**Comment by CarlitoGil** [comment]
Also, this could be messing with the "Max Download Per" counts.

**Comment by zze0s** [comment]
Aware of this behaviour/issue and just need time to fix it.

**Comment by zze0s** [comment]
@CarlitoGil Do you know if this is still an issue? With v1.25.0 we added a new `PENDING` state which might have solved this, but I have not tried to reproduce the issue.

**Comment by CarlitoGil** [comment]
Hi, @zze0s 

I just got around to test this with 1.28.0.

Sadly, the issue remains.

It's easy enough to reproduce:
I just set reannounce to 1 second and 1 try.

![image](https://github.com/autobrr/autobrr/assets/5706999/a59412a1-510c-454c-bcd6-ca32dd18669f)

The torrent is added and removed 2 seconds later, but I still get a green "approved " status notification.



```
17:00:16.000
TRACE
release.Process: indexer: <indexer>, filter: TEST STALLED release: <release> , run action: Download
17:00:18.000
TRACE
events: 'PUSH_APPROVED' '&{Subject: Message: Event:PUSH_APPROVED ReleaseName:<release> Filter:TEST STALLED Indexer:<indexer> InfoHash: Size:2799000000 Status:Approved Action:Download ActionType:QBITTORRENT ActionClient:BOX Rejections:[] Protocol:torrent Implementation:IRC Timestamp:2023-09-07 17:00:18.3058861 -0400 -04 m=+49615.627831901}'
```

**Comment by zze0s** [comment]
Thanks for confirming. Then I still need to look into this.
