### ISSUE TITLE
[INDEXER REQ] LST

### ISSUE THREAD

**Issue by Yankees4life** [autobrr/autobrr#672]
**We currently only support indexers with IRC announces.**

# Indexer request

-  Do they have irc announce? Yes

### If no existing `autodl-irssi .tracker` file

- Indexer name: LST
- Short name: LST
- URL: https://lst.gg
- Download link examples with key such as `passkey, rss key, auth key, torrent pass` etc
https://lst.gg/torrent/download/10986.randomrsskey

## Announce examples

Please provide 1-5 different announces. And change release titles for good measure. If they have tags like freeleech and internals etc make sure to get examples of those.

- `Category [Movies] Type [Remux] Name [Movie1995 1080p BluRay REMUX AVC DTS-HD MA 5.1-Ripper] Resolution [1080p] Freeleech [0%] Internal [No] Double Upload [No] Size [37.81 GiB] Uploader [GRiMM] Url [http://lst.gg/torrents/00000]`
- `Category [Movies] Type [Remux] Name [Some Random Movie 1985 1080p BluRay REMUX VC-1 DTS-HD MA 5.1-Ripper] Resolution [1080p] Freeleech [0%] Internal [No] Double Upload [No] Size [25.35 GiB] Uploader [GRiMM] Url [http://lst.gg/torrents/00000]`

## IRC Network

- Network name: LST
- Network address: irc.lst.gg
- Announce channel: #announce
- Port: 6697
- SSL/TLS: Yes
- NickServ registration required? Check wiki, guides etc: No
- Is there a required format for the nick? Like `username|bot`? Has to be the username on the tracker
- Invite command: just need the IRC key found on the profile in order to enter the server

## Bonus

Check their categories in the announce an on site
Movies
TV
XXX
Anime
Music
Game 
Application
Packs
Education
Ebook/Manga

**Comment by Yankees4life** [comment]
Looks like the announce channel is offline so disregard this 🤣😂

**Comment by wengj9** [comment]
The announce channel appears to be online now, should this be reopened?

**Comment by Yankees4life** [comment]
The admin has reopened the announce channel so I would like to reopen this request

**Comment by s0up4200** [comment]
What is the announce bot called?

**Comment by Yankees4life** [comment]
LSTANNOUNCE
