### ISSUE TITLE
Autobrr did filter, and recognise torrent, but didn't add it to rtorrent client

### ISSUE THREAD

**Issue by rogales** [autobrr/autobrr#675]
**Version 1.16.0**
The autobrr version you're running. If you run something other than latest, please update before reporting issues.

**Describe the bug**
Autobrr did recognise the rule, and found torrent on announce channel, but it did't add to rtorrent client
**Had to add the torrent mannually.**
I would like to add, that other rules, with other indexers work properly.

**Expected behavior**
Automatically add the torrent to client, to start the download.

**Screenshots**
https://apm.anonify.eu/fjhtdadk.png

**Desktop (please complete the following information):**
 - OS: Linux niobe 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux
 - Browser [e.g. Chrome 109.0.5414]

**Additional context**
I've restarted the autobrr plugin, and maybe it helps, but right now just wanted to let You know about this issue.
Will inform You it it happens again with any other rule.

**Comment by zze0s** [comment]
Gonna need a bit more info to be able to answer anything, but some common issue with the rtorrent action can be that the label must exist in r(u)torrent before adding the torrent, and same with the save path.

**Comment by zze0s** [comment]
No response so closing.
