### ISSUE TITLE
[FEATURE REQ] Add a start-up script for docker container to customize the environment

### ISSUE THREAD

**Issue by Gylesie** [autobrr/autobrr#689]
**Is your feature request related to a problem? Please describe.**
When running an official autobrr docker container and utilizing custom script filters, it is complicated to write some scripts without tools like `jq`. Also, there is no `python` interpreter, so python scripts can't be written at all.

**Describe the solution you'd like**
I would like to be able to define a start-up script that would run each time the container starts. It would be able to customize the container's environment, for example installing additional packages from apt. Having a special location in the container to mount the startup script which would be then run at start would suffice.

**Describe alternatives you've considered**
The workaround now is to build a new docker image with the autobrr as the base, however that would require for the user to rebuild each time autobrr gets updated, which can be tedious.

**Comment by zze0s** [comment]
Hi!

The default image is meant to be lean without a bunch of extra tools. We can however consider adding an additional tag that has more features built in, but I don't think we'll ever please everyone since everyone have their own ideas and workflows and toolchains.

> I would like to be able to define a start-up script that would run each time the container starts. It would be able to customize the container's environment, for example installing additional packages from apt. Having a special location in the container to mount the startup script which would be then run at start would suffice.

Do you have any examples of what would look like?

> The workaround now is to build a new docker image with the autobrr as the base, however that would require for the user to rebuild each time autobrr gets updated, which can be tedious.

You could setup new repo with GitHub Actions running on a schedule and build from latest or tags etc.

**Comment by Gylesie** [comment]
> The default image is meant to be lean without a bunch of extra tools

> everyone have their own ideas and workflows and toolchains

I very much agree with that. That's why I kind of like the idea of a custom and optional start-up script that would prepare the container's environment to users' exact needs. That way, there would not be the drawback of extra unnecessary tooling for users that don't need it, but at the same time it would allow others to do so if they opt for it.

**This is how I imagine it could work like**
Let's define a folder in a special location that would contain startup scripts. For example: `/init.d/*.sh`. All script files within this folder would be executed sequentially on container start, before starting autobrr instance.

The users would just need to mount a new folder containing their startup script(s), the same way they already do with the /config mount.

**How it could be implemented**
Add a script to the docker image that would check the hard-coded special folder location for any start-up scripts. Each script within the folder would get executed sequentially _(for security reasons it might be better to require scripts to be owned by root)_. Right after all scripts the autobrr instance would be started: `/usr/local/bin/autobrr --config /config`

The Dockerfile's `ENTRYPOINT` directive would point to the script described above.

**Comment by Gylesie** [comment]
Unfortunately, I have just realized that the script will be run by the user specified by `--user`. Unless it is root, the startup script won't be able to install new packages via `apk add`. I do not know how to resolve this issue.

**Comment by zze0s** [comment]
As much as possible should be installed during the Dockerfile build. What tools do you need in the container? If you have custom scripts you could mount those in as long as the deps to run them are there.

**Comment by Gylesie** [comment]
> As much as possible should be installed during the Dockerfile build. What tools do you need in the container? If you have custom scripts you could mount those in as long as the deps to run them are there.

As a user of numerous linuxserver.io containers, I wanted to install those deps via the custom script by running `apk add` commands. However it appears I have hit a roadblock since autobrr is a rootless container and therefore there is no way to do that kind of thing. I am desperately in need of `jq` tool to parse complex JSON responses.

**Comment by zze0s** [comment]
Yeah adding stuff afterwards is not really an option. Is it only jq you need? That's fine to add to the default image.

**Comment by Gylesie** [comment]
Jq is the only tool I need besides others that are already there. Having it in the container would be awesome!

**Comment by KyleSanderson** [comment]
I haven't run retail docker in a while, but can't you just do `docker exec -u0 autobrr -- apk add --no-cache jq`

**Comment by Gylesie** [comment]
> I haven't run retail docker in a while, but can't you just do `docker exec -u0 autobrr -- apk add --no-cache jq`

Yes, of course that is possible, but that won't survive when the container recreates. So that's why having it in the image itself would be nice.
