### ISSUE TITLE
Lossless also matches 24bit Lossless

### ISSUE THREAD

**Issue by s0up4200** [autobrr/autobrr#703]
**Version**
1.17.0

**Describe the bug**
Quality type `Lossless` also matches `24bit Lossless`

**To Reproduce**
1. Create a filter matching `Lossless`
2. Filter matches announces containing `24bit Lossless`

**Expected behavior**
It should only match `24bit Lossless` when that is selected as a quality.

**Log output**:
{"level":"info","module":"release","indexer":"redacted","filter":"!! 24bit Lossless test","release":"Various Artists - Hogwarts Legacy (Study Themes from the Original Video Game Soundtrack) [2023] [Soundtrack] - FLAC / 24bit Lossless / WEB","time":"2023-02-10T17:04:42Z","message":"Matched 'Various Artists - Hogwarts Legacy (Study Themes from the Original Video Game Soundtrack) [2023] [Soundtrack] - FLAC / 24bit Lossless / WEB' (!! 24bit Lossless test) for redacted"}

**Comment by Jaonea** [comment]
Can confirm experiencing the same issue

**Comment by Jaonea** [comment]
Issue is still occurring on v1.27.1 when using redacted as indexer
