### ISSUE TITLE
enhancement: brighter icons on the light theme

### ISSUE THREAD

**Issue by stacksmash76** [autobrr/autobrr#707]
the newly added icons are rather distracting. there is no reason for the information icon (a hidden action) to have a vastly greater contrast than the description.

![image](https://user-images.githubusercontent.com/98354295/218292226-4f06b29c-8453-4293-a52d-7fcc4eefc87a.png)

**Comment by stacksmash76** [comment]
the same goes for the navbar, where the icon next to the docs link is strikingly unbalanced (icon becomes dominant over the text). for a second i thought it was some kind of a pause button.

we read from left to right, so as soon as our brains finish reading the 'docs' text, it's to be expected that an indication of an action will concretize this to make it abundantly clear. hence, arrows are the perfect choice.
the icons can be moved to the left, however. but i don't think they'll improve the design.

as-is, looks as a regression to me.

**Comment by KyleSanderson** [comment]
> the same goes for the navbar, where the icon next to the docs link is strikingly unbalanced (icon becomes dominant over the text). for a second i thought it was some kind of a pause button.

It's an information icon, but may not be internationalized. Perhaps a question mark?
 
> we read from left to right, so as soon as our brains finish reading the 'docs' text, it's to be expected that an indication of an action will concretize this to make it abundantly clear. hence, arrows are the perfect choice. the icons can be moved to the left, however. but i don't think they'll improve the design.

What do you think would be better?

> as-is, looks as a regression to me.

Functionality wise it's very helpful for new users 😸.

It looks OK to me, despite the advanced theme.

![image](https://user-images.githubusercontent.com/1184902/218295200-b123a6e6-c1f0-4871-864e-0a6369fdca07.png)
