### ISSUE TITLE
[FEATURE REQ]  A variable/macro for the torrent files/data?

### ISSUE THREAD

**Issue by justchil** [autobrr/autobrr#720]
This may exist and I'm just not able to figure it out.

Using an exec action to rsync .torrent files from filters works no problem using path/{{.TorrentName}}.torrent

--ignore-existing -avz -e "ssh -i /home/user/.ssh/key-rsa" "/home/user/torrents/{{.TorrentName}}.torrent" "user@remote.host:/home/user/torrents/"

I would like to be able to rsync the torrent data the same way but I can't figure out a way to do it with an exec action.   I do need to turn on higher logging to see what's going on deeper.  The files are always named "{{.TorrentName}}.extension" or "{{.TorrentName}}" as a folder name.

--ignore-existing -avz -e "ssh -i /home/user/.ssh/key-rsa" "/home/user/data/{{.TorrentName}}.*" "user@remote.host:/home/user/data/"

--ignore-existing -avz -e "ssh -i /home/user/.ssh/key-rsa" "/home/user/data/{{.TorrentName}}/" "user@remote.host:/home/user/data/"

Could someone please steer me in the right direction.  The end goal is to get the torrent data to rsync to the remote rtorrent then push over the torrent (so it doesn't download the data again).

**Comment by KyleSanderson** [comment]
Check https://autobrr.com/filters/actions#available-variables and you can use TorrentPathName. Also feel free to ask these questions on Discord if you'd like as it's easier for all involved 😸. Feel free to reopen if for whatever reason Discord doesn't work for you.
