### ISSUE TITLE
Log File Download Downloading HTML not log file

### ISSUE THREAD

**Issue by bakerboy448** [autobrr/autobrr#724]
**Version**
Version:
1.18.0
Commit:
088cb8154c5f174bad984c3e8876ab3291ec291a
Build date:
2023-02-12T17:56:56Z

**Describe the bug**

download logs from UI gives html

```
<!doctype html><html lang="en"><head><meta charset="utf-8" /><link rel="icon" href="./static/favicon.ico" /><meta name="viewport" content="width=device-width,initial-scale=1" /><meta name="theme-color" content="#000000" /><meta name="description" content="autobrr" /><link rel="apple-touch-icon" href="./static/logo192.png" /><link crossorigin="use-credentials" rel="manifest" href="./static/manifest.json" /><title>autobrr</title><base href="/autobrr/"><script>window.APP={},window.APP.baseUrl="\/autobrr\/"</script><script defer="defer" src="./static/js/main.d237753a.js"></script><link href="./static/css/main.5fc95aec.css" rel="stylesheet"></head><body class="bg-color"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root" class="pattern"></div></body></html>
```

**To Reproduce**
1. Settings => Logs
2. Click on 
![image](https://user-images.githubusercontent.com/55419169/220412852-5be01dda-d5a6-4347-a4e2-656a0f954272.png)
3.  Open downloaded file

**Expected behavior**
log file to download

**Screenshots**

n/a

**Desktop (please complete the following information):**
agnostic
**Smartphone (please complete the following information):**
agnostic

**Additional context**

- using baseurl

**Comment by s0up4200** [comment]
Fixed in develop: https://github.com/autobrr/autobrr/pull/713
