### ISSUE TITLE
Deluge v1 `save_path` not working

### ISSUE THREAD

**Issue by Sonic3R** [autobrr/autobrr#727]
**Version**
1.18.0

**Describe the bug**
I setup filter, in Action tab, for `Save path` I have like: `/home/myuser/downloads/{{.TorrentName}}`

The path `/home/myuser/downloads` exists.

But in client, the {{.TorrentName}} seems to be empty and ignored.
**To Reproduce**
1. Setup Deluge client
2. Setup filter, then go to Action, set Deluge type, for `Save Path` set to `/home/myuser/downloads/{{.TorrentName}}`
3. Save and make sure that filter is enabled

**Expected behavior**
I expected that path with torrent name is appended at end.

**Screenshots**
![image](https://user-images.githubusercontent.com/6311947/220845216-8b597fe4-8f87-4419-a77e-2673a922cd3b.png)

![image](https://user-images.githubusercontent.com/6311947/220845279-092ddeae-c245-4784-9ced-ba28d27d7632.png)

![image](https://user-images.githubusercontent.com/6311947/220845407-2d5425ba-8c2d-4cbd-8746-58a8f83c3d84.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser no matter, I use often Chrome

**Comment by zze0s** [comment]
As answered on Discord, it's a known issue with the 3rd party library we use for Deluge v1. Works fine with Deluge v2. Will investigate when there's time.

**Comment by zze0s** [comment]
Finally took the time to debug this and left a reply in the active issue for the library. https://github.com/gdm85/go-libdeluge/issues/44

It's been quiet from the dev for some time so I do not expect a response. We might have to fork the library.
