### ISSUE TITLE
Xspeeds links not working

### ISSUE THREAD

**Issue by koolmon10** [autobrr/autobrr#734]
**Version**
1.16.0

**Describe the bug**
After setting up cross-seed with autobrr, I noticed cross-seed is unable to follow the links sent by autobrr. It looks like autobrr is sending links for xspeeds.eu, which is serving an expired cert. The main site is at www.xspeeds.eu (which xspeeds.eu redirects to after bypassing the bad cert). The announce messages in IRC point to www.xspeeds.eu, so I am assuming autobrr is writing the links manually.

Error from cross-seed: "error: failed to access https://xspeeds.eu/download.php?type=rss&secret_key=<removed>&id=xxxxxxx"

**To Reproduce**
1. Setup Xspeeds IRC
2. Setup cross-seed
3. cross-seed gives "failed to access" error for all announces

**Expected behavior**
autobrr sends links with correct hostname to cross-seedd

**Comment by zze0s** [comment]
Please update to latest version, then you can override the base url in the indexer settings. Set that to `https://www.xpseeds.eu` and that should be good.

I'll update the definition.

**Comment by koolmon10** [comment]
Yeah, I noticed I was behind after posting this and updated. Looks like the override worked, thanks!

**Comment by sameep22** [comment]
Seems like the issue has stared again. The IRC channel for Xspeeds has no announce since 2 days. Removing and adding the indexer again does not help. Changing the URL to "https://www.xpeeds.eu" from "https://xpeeds.eu" did not help either.

**Comment by s0up4200** [comment]
https://xpeeds.eu/ seems to be down for me, might be related.

**Comment by sameep22** [comment]
That is strange... My IRC channel remains unhealthy. It does tell me the the indexer was added successfully each time I add it, but I receive no announces on the the channel... 
I have checked the pass key, the URL, and the nickname matches my account on the site. I don't understand why did it suddenly stop working about 2 days ago.

**Comment by zze0s** [comment]
Their IRC network has been down for about 2 days or however long ago your last announce was.

No info on the forums. Probably a good idea to reach out to them and ask. It's hopefully only something temporary. Servers go down all the time.

> That is strange... My IRC channel remains unhealthy. It does tell me the the indexer was added successfully each time I add it, but I receive no announces on the the channel... I have checked the pass key, the URL, and the nickname matches my account on the site. I don't understand why did it suddenly stop working about 2 days ago.
