### ISSUE TITLE
[BUG] RED - EP being parsed as source

### ISSUE THREAD

**Issue by jonandeva** [autobrr/autobrr#746]
**Version**
1.19.0

**Describe the bug**
I have a filter on RED that is not working properly. In the Media field I have selected all, but the list does not include EP. I see that EP is not on the media list though. In the log I noticed that torrents are being rejected because they have EP in the media field. I've only been running the filter for about 6 hours and dozens have been rejected. I checked RED's site and the upload page does not include EP in the media dropdown, so I assume people are uploading with "EP" in that field via the API. I do have EP selected in the Type field. I guess EP should be added to the Media list, or somehow make an "any media" option? 

`{"level":"trace","module":"release","indexer":"redacted","filter":"RED FLAC","release":"Album - Name [2022] [EP] - FLAC / Lossless / WEB","time":"2023-03-08T17:45:15+01:00","message":"release.Process: indexer: redacted, filter: RED FLAC release: Album - Name [2022] [EP] - FLAC / Lossless / WEB, no match. rejections: media not matching. got: EP want: [CD WEB DVD Vinyl Soundboard DAT Cassette Blu-Ray SACD]"}`

I could copy/paste more examples, if needed. I have about 70.

<img width="1212" alt="Screenshot 2023-03-08 at 17 02 19" src="https://user-images.githubusercontent.com/12461075/223849254-153bb8a2-3008-4b2f-9d88-212ce22c3cd5.png">

**Comment by zze0s** [comment]
Hello!

Can you try set EP as a category instead? Looking at the [definition it's mapped to category](https://github.com/autobrr/autobrr/blob/develop/internal/indexer/definitions/red.yaml#L92) so the dropdown alternatives for type might be misleading.

**Comment by jonandeva** [comment]
> Hello!
> 
> Can you try set EP as a category instead? Looking at the [definition it's mapped to category](https://github.com/autobrr/autobrr/blob/develop/internal/indexer/definitions/red.yaml#L92) so the dropdown alternatives for type might be misleading.

Category is not an option in the GUI. The list of what I "want" that isn't matching in the log is the same as the list under Media that I have selected all on in the GUI.

**Comment by zze0s** [comment]
Dismiss what I said about category. It is mapped to type so that is fine. But somewhere during parsing EP becomes source :thinking: 

Will debug further. 

If you have everything selected in type and media you might as well leave them empty since that will match everything in those fields.

**Comment by zze0s** [comment]
This only happens with titles of the type EP. The ordering is the key issue here.

[In this PR](https://github.com/autobrr/autobrr/commit/08826db0360c89eb4660e163efc2bed463878717) we changed what was considered the torrentName to improve parsing in general. We did however not test the case with EP's. It does not happen with any other as far as I can tell.

## Potential solution:

Iterate and create a new parser/torrentName reconstruction (like AB) to remove the `[category] from the title`.

I'll at it with some prio and see what we do about it. 

## Temporary fix

For now, remove the Media filter values since that will get it past the checks.

**Comment by zze0s** [comment]
This got fixed in https://github.com/autobrr/autobrr/releases/tag/v1.22.0

Let me know if you still get issues with it.

**Comment by s0up4200** [comment]
Seems to be bugged still.

Version: `develop`
Build date: `2023-05-09T16:26:16.353Z`

`{"level":"trace","module":"release","indexer":"redacted","filter":"RED - Anjuna","release":"Joseph Ray - Blue Nights [2023] [EP] - FLAC / Lossless / WEB","time":"2023-05-12T10:21:56+02:00","message":"release.Process: indexer: redacted, filter: RED - Anjuna release: Joseph Ray - Blue Nights [2023] [EP] - FLAC / Lossless / WEB, no match. rejections: media not matching. got: EP want: [CD WEB]"}`

**Comment by zze0s** [comment]
I'm finally working on a fix for this and other music related issues all in one go. See #1373

Plan is to get it out in the next release. Will need some testers, preferably running docker since it's easy to just change the tag.
