### ISSUE TITLE
Size check error on RED

### ISSUE THREAD

**Issue by jonandeva** [autobrr/autobrr#747]
**Version**
1.19.0

**Describe the bug**
I added a min file size to my RED filter and it stopped working. I tried reseting the API. That didn't help. My scope is set to User, Torrents, as per instructions. When I removed the minimum file size criteria, it started working fine again.

Getting errors like this:
`{"level":"debug","module":"filter","time":"2023-03-09T00:23:48+01:00","message":"filter.Service.CheckFilter: found and matched filter: RED FLAC"}
{"level":"debug","module":"filter","time":"2023-03-09T00:23:48+01:00","message":"filter.Service.CheckFilter: (RED FLAC) additional size check required"}
{"level":"debug","module":"filter","time":"2023-03-09T00:23:48+01:00","message":"filter.Service.AdditionalSizeCheck: (RED FLAC) additional size check required"}
{"level":"trace","module":"filter","time":"2023-03-09T00:23:48+01:00","message":"filter.Service.AdditionalSizeCheck: (RED FLAC) preparing to check via api"}
{"level":"trace","module":"indexer-api","method":"GetTorrentByID","time":"2023-03-09T00:23:48+01:00","message":"'redacted' trying to fetch torrent from api"}
{"level":"error","module":"indexer-api","error":"could not get torrent by id: 4023396: unauthorized: bad credentials","time":"2023-03-09T00:23:48+01:00","message":"could not get torrent: '4023396' from: redacted"}
{"level":"error","module":"filter","error":"could not get torrent by id: 4023396: unauthorized: bad credentials","time":"2023-03-09T00:23:48+01:00","message":"filter.Service.AdditionalSizeCheck: (RED FLAC) could not get torrent info from api: '4023396' from: redacted"}`

**Comment by s0up4200** [comment]
Hi there. Your logs indicate that the API key is invalid.
`{"level":"error","module":"filter","error":"could not get torrent by id: 4023396: unauthorized: bad credentials`

I tested myself, with a min size of `1G`. This is the result:
```
"message":"filter.Service.CheckFilter: found and matched filter: !!!Min size"}
"message":"filter.Service.CheckFilter: (!!!Min size) additional size check required"}
"message":"filter.Service.AdditionalSizeCheck: (!!!Min size) additional size check required"}
"message":"filter.Service.AdditionalSizeCheck: (!!!Min size) preparing to check via api"}
"message":"'redacted' trying to fetch torrent from api"}
"message":"'redacted' successfully fetched torrent from api: &{Id:1234567 TorrentId: InfoHash:strip Size:1961480925}"}
"message":"filter.Service.AdditionalSizeCheck: (!!!Min size) got torrent info from api: &{Id:1234567 TorrentId: InfoHash:strip Size:1961480925}"}
"message":"Matched 'Artist - Album [2022] [Compilation] - FLAC / Lossless / WEB' (!!!Min size) for redacted"}
```

What does your API key look like?
It should look like this: `8g31p7qz.5m9k0o4a6t2u2n7v5w4y6j2e4t8n0f7s`

**Comment by jonandeva** [comment]
Just reset my API again and got the same thing:

`06:48:28.000DEBUG filter.Service.CheckFilter: found and matched filter: RED FLAC
06:48:28.000DEBUG filter.Service.CheckFilter: (RED FLAC) additional size check required
06:48:28.000DEBUG filter.Service.AdditionalSizeCheck: (RED FLAC) additional size check required
06:48:28.000TRACE filter.Service.AdditionalSizeCheck: (RED FLAC) preparing to check via api
06:48:28.000TRACE 'redacted' trying to fetch torrent from api
06:48:28.000ERROR could not get torrent: '4024548' from: redacted
06:48:28.000ERROR filter.Service.AdditionalSizeCheck: (RED FLAC) could not get torrent info from api: '4024548' from: redacted
06:48:28.000ERROR filter.Service.CheckFilter: (RED FLAC) additional size check error
06:48:28.000ERROR release.Process: error checking filter`

My API key does look like yours:
12345a22.aac523a56a77b12b65dc692b88abbff3

**Comment by jonandeva** [comment]
I wouldn't think so, but is it possible more scope is needed? 

It would be nice if there were a button to test API.

**Comment by zze0s** [comment]
> I wouldn't think so, but is it possible more scope is needed?
> 
> It would be nice if there were a button to test API.

Only User and Torrents scope should be needed. I started on a feature to test the settings easily from the indexer settings. #829

**Comment by wastingaeons** [comment]
Unsure if the open PR fixes it, so sorry if this comment is unnecessary, but I did notice it seems to be using the wrong torrentID on lookup:
`{"level":"error","module":"release","indexer":"redacted","filter":"RED","release":"Artist - Album [2023] [Album] - FLAC / 24bit Lossless / WEB / Scene","error":"could not get torrent by id: 4108642: unauthorized: bad credentials","time":"2023-04-15T02:35:49Z","message":"release.Process: error checking filter"}`

When in fact, going to the album on the website shows the torrentID as **4095601** - which gives correct json in postman

Here's the result in postman when using the torrentID brr reports shows:
`{"status": "failure", "error": "bad id parameter"}`
