### ISSUE TITLE
[Suboptimal] - URL field for Generic *Nab detected as username/email autofill 1Password field

### ISSUE THREAD

**Issue by bakerboy448** [autobrr/autobrr#750]
**Version**
Version:
1.19.0
Commit:
cec6809b346610dcaf46f919f6ca19d8d836fe4b
Build date:
2023-03-05T20:13:29Z

**Describe the bug**
title

**To Reproduce**
1. Use 1Password or another PW manager
2. Edit Indexer Settings for a generic Nab
3. See suggestions

**Expected behavior**
should not be a form fillable-esque field for password managers

**Screenshots**
![image](https://user-images.githubusercontent.com/55419169/224458882-796107cb-c2ae-46dc-9766-95788bc3b9c8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Access via Windows; Host Ububtu 20.04
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 110.0.5481.178 

**Smartphone (please complete the following information):**

**Additional context**

1Password Chrome Extension Version 2.7.0
https://1password.community/discussion/117501/as-a-web-developer-how-can-i-disable-1password-filling-for-a-specific-field

**Comment by zze0s** [comment]
Tried setting `autocomplete="off"` on the field but that did not disable it, and reading that 1Password thread a lot of users seem to have the same issue that 1P just decides itself what it think it should be.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/43699394/230922106-dc575fb1-367a-4170-a2fd-054e3d6fd03a.png">

Using `url` seem to work, but it's a "generic" field that is generated all the way down from the yaml indexer definitions and the only separate types we have from those are `text` and `password`.

Adding a new attribute to all those indexer definition settings is not something I see as a solution either.

So with that in mind, I don't see how we can fix this. While it is annoying I hope you don't spend hours and hours in that form each to add indexers.
