### ISSUE TITLE
Automatically remove releases after X amount of time 

### ISSUE THREAD

**Issue by dreondre** [autobrr/autobrr#751]
**Is your feature request related to a problem? Please describe.**
After thousands and thousands of filtered/rejected releases, they serve no purpose to me.

**Describe the solution you'd like**
I’d like to see more options added to the Releases settings, some suggestions:

- Automatically delete releases older than X
- Automatically delete releases by type older than X
- Automatically immediately delete by type.

**Describe alternatives you've considered**
None because I’m unaware of any.

**Additional context**
The delete all releases button can remain because it’s still useful. However, I would love to have more flexibility on what’s kept.

**Comment by zze0s** [comment]
Good suggestions. Been meaning add more options.

> Automatically immediately delete by type.

What would type be here? Is it per indexer, protocol, category etc?

**Comment by dreondre** [comment]
It really depends on how extensive you'd want to make it. Personally, I don't have much use for the data or stats for _any_ indexer beyond a few days except for troubleshooting. At the very least, I like keeping the overall approved pushes. I believe that's what I meant when I wrote "Automatically (delete) immediately by type."

Open to ideas from anyone else.
