### ISSUE TITLE
[BUG] Max age ignored for Torznab feeds

### ISSUE THREAD

**Issue by IevgenSobko** [autobrr/autobrr#754]
**Version**
v1.19.0

**Describe the bug**

**To Reproduce**
1. Create new Torznab indexer from Prowlarr idexer (Settings > Indexers > Add new)
2. Go to RSS feeds and enable newly created Torznab feed (Settings > Feeds)
3. Make sure created feed has default Max age value set to 3600(means download only releases, not older than 1 hour)
4. Add new Filter(Filteers > Add new)
5. Open the newly created filter.
6. Add your Torznab indexer to it and Add Download action with qBittorent client(I actually had set limit to 2 active downloads on this client and it appears was ignored because torrents were appearing an apearing in client when there were already 2 downloads active). All other values might be left untouched to download everything.
7. Enable this filter and wait for it to process some data.
8. Go to Releases and see new downloads appear.
9. Verify that even releases that exceed Max age appear.

**Expected behavior**
Only new releases should be downloaded, which have add time lower than Max age(by default 3600 seconds that stands for 1 hour).

**Additional context**
Also, I 've noticed strange behavior when releases appeared and appeared for few hours. My Torznab had 100 releases in it.
I would expect they all got loaded into client. But maybe I don't know some internals how you scheduling them. For me it is strange to see torrents added in a few hours.
Attaching also XML of Torznab feed with cleaned up sensitive information
[latest.xml.zip](https://github.com/autobrr/autobrr/files/10951298/latest.xml.zip)

**Comment by KyleSanderson** [comment]
hi - thank you for the report. I've attempted an implementation here: https://github.com/autobrr/autobrr/pull/763

When this builds could you please test it (there will be a docker image tag using `pr-763`)?
I don't use the feature presently personally, so I don't have the setup for it unfortunately.

**Comment by IevgenSobko** [comment]
Yes, I can test it.
Will post results later.

**Comment by IevgenSobko** [comment]
@KyleSanderson I have checked source code and found following definition of tornznab item
```go
type FeedItem struct {
	Title           string `xml:"title,omitempty"`
	GUID            string `xml:"guid,omitempty"`
	PubDate         Time   `xml:"pub_date,omitempty"`
	Prowlarrindexer struct {
		Text string `xml:",chardata"`
		ID   string `xml:"id,attr"`
	} `xml:"prowlarrindexer"`
	Comments   string `xml:"comments"`
	Size       string `xml:"size"`
	Link       string `xml:"link"`
	Category   []int  `xml:"category,omitempty"`
	Categories Categories

	// attributes
	TvdbId string `xml:"tvdb,omitempty"`
	//TvMazeId string
	ImdbId string `xml:"imdb,omitempty"`
	TmdbId string `xml:"tmdb,omitempty"`

	Attributes []ItemAttr `xml:"attr"`
}
```
Does this mean that publication date searched by `pub_date` element?
If so, it is incorrect I have checked both tornznab generated by Prowlarr and Jackett and both of them represent publication date as `pubDate` element(you can check this by opening zip I've attached to the initial bug report).
That seems to me the root of the problem.

**Comment by zze0s** [comment]
That's a good find!! I think it might come from a lot of copying and the torznab source was json instead of xml.

I'll push a fix.

**Comment by zze0s** [comment]
Try it out when possible and we'll open this if needed again.
