### ISSUE TITLE
Problems when testing and connecting to qBittorrent 4.5.2 (No-X) version

### ISSUE THREAD

**Issue by KamikazeePL** [autobrr/autobrr#778]
**Version**
Version:
    1.20.0
Commit:
    81d494ec5c7703ef496c9f8406fa9227c36217b5
Build date:
    2023-03-19T23:23:39Z

**Describe the bug**
When I'm adding new qBitorrent client I get error on test

**To Reproduce**
When there seeding torrents on client I get error but when I remove all torrents from qBittorrent client autobrr connect without an error.

Log with error and seeding torrents:
`cat log.txt | tail
{"level":"trace","module":"http","type":"access","time":"2023-03-20T18:10:47+01:00","bytes_in":"331","bytes_out":182,"latency_ms":422.758537,"method":"POST","proto":"HTTP/1.1","remote_ip":"192.168.0.1:54185","status":500,"url":"/api/download_clients/test","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0","time":"2023-03-20T18:10:47+01:00","message":"incoming_request"}
{"level":"trace","module":"download_client","time":"2023-03-20T18:10:48+01:00","message":"logged into client: http://192.168.0.59:1340"}
{"level":"error","module":"download_client","stack":[{"func":"(*service).testQbittorrentConnection","line":"85","source":"connection.go"},{"func":"(*service).testConnection","line":"26","source":"connection.go"},{"func":"(*service).Test","line":"128","source":"service.go"},{"func":"downloadClientHandler.test","line":"80","source":"download_client.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"442","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"71","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"314","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Server.IsAuthenticated.func1","line":"39","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*ChainHandler).ServeHTTP","line":"31","source":"chain.go"},{"func":"(*Mux).routeHTTP","line":"442","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"71","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"314","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"442","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Cors).Handler.func1","line":"231","source":"cors.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"LoggerMiddleware.func1.1","line":"85","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Recoverer.func1","line":"38","source":"recoverer.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RealIP.func1","line":"35","source":"realip.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RequestID.func1","line":"76","source":"request_id.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"88","source":"mux.go"}],"error":"error getting torrents: http://192.168.0.59:1340: could not unmarshal body: json: cannot unmarshal number 5675662131 into Go struct field Torrent.completed of type int","time":"2023-03-20T18:10:48+01:00","message":"client connection test error"}
{"level":"trace","module":"http","type":"access","time":"2023-03-20T18:10:48+01:00","bytes_in":"331","bytes_out":182,"latency_ms":481.397537,"method":"POST","proto":"HTTP/1.1","remote_ip":"192.168.0.1:54185","status":500,"url":"/api/download_clients/test","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0","time":"2023-03-20T18:10:48+01:00","message":"incoming_request"}
{"level":"trace","module":"download_client","time":"2023-03-20T18:10:50+01:00","message":"logged into client: http://192.168.0.59:1340"}
{"level":"error","module":"download_client","stack":[{"func":"(*service).testQbittorrentConnection","line":"85","source":"connection.go"},{"func":"(*service).testConnection","line":"26","source":"connection.go"},{"func":"(*service).Test","line":"128","source":"service.go"},{"func":"downloadClientHandler.test","line":"80","source":"download_client.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"442","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"71","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"314","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Server.IsAuthenticated.func1","line":"39","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*ChainHandler).ServeHTTP","line":"31","source":"chain.go"},{"func":"(*Mux).routeHTTP","line":"442","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"71","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"314","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"442","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Cors).Handler.func1","line":"231","source":"cors.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"LoggerMiddleware.func1.1","line":"85","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Recoverer.func1","line":"38","source":"recoverer.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RealIP.func1","line":"35","source":"realip.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RequestID.func1","line":"76","source":"request_id.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"88","source":"mux.go"}],"error":"error getting torrents: http://192.168.0.59:1340: could not unmarshal body: json: cannot unmarshal number 5675662131 into Go struct field Torrent.completed of type int","time":"2023-03-20T18:10:50+01:00","message":"client connection test error"}
y_ms":474.809778,"method":"POST","proto":"HTTP/1.1","remote_ip":"192.168.0.1:54291","status":204,"url":"/api/download_clients/test","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0","time":"2023-03-20T18:14:26+01:00","message":"incoming_request"}
`

When I removed all torrents from qBittorrent-nox v.4.5.2 autobrr connects
`{"level":"trace","module":"download_client","time":"2023-03-20T18:52:32+01:00","message":"logged into client: http://192.168.0.59:1340"}
{"level":"debug","module":"download_client","time":"2023-03-20T18:52:32+01:00","message":"test client connection for qBittorrent: success"}
{"level":"trace","module":"http","type":"access","time":"2023-03-20T18:52:32+01:00","bytes_in":"187","bytes_out":0,"latency_ms":605.922611,"method":"POST","proto":"HTTP/1.1","remote_ip":"192.168.0.1:62528","status":204,"url":"/api/download_clients/test","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0","time":"2023-03-20T18:52:32+01:00","message":"incoming_request"}
{"level":"debug","repo":"action","time":"2023-03-20T18:52:38+01:00","message":"download_client.store: 7"}`

**Comment by KyleSanderson** [comment]
Just to clarify, submission works, but the Test button isn't working for you?

**Comment by KamikazeePL** [comment]
When connected it works normaly

**Comment by KyleSanderson** [comment]
Which OS are you running autobrr on? is it 32bit? just trying to narrow this down further. I think I see the problem in the code but it's not erroring out on my platform (linux amd64) presumably due to integer promotion.

**Comment by KamikazeePL** [comment]
uname -a
Linux DietPi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/
Linux

**Comment by KyleSanderson** [comment]
ok so your kernel supports 64bit...

Which release are you using:
```
autobrr_1.20.0_linux_arm64.tar.gz
autobrr_1.20.0_linux_armv6.tar.gz
```

**Comment by KamikazeePL** [comment]
i use armv6

**Comment by KyleSanderson** [comment]
Got it - the patch still has to be reviewed and then merged back into here which may take some time.

As your CPU supports 64bit computing, can you try the arm64 build in the meantime? Everything is statically linked so as long as your kernel actually supports 64bit execution it should work better for you in the meantime.
