### ISSUE TITLE
Rejected: could not open temp file: : open : no such file or directory

### ISSUE THREAD

**Issue by phenomeni** [autobrr/autobrr#781]
Since updating to v1.20.0 every .torrent returns the above error in AutoBrr. Nothing else was changed or modified ... why does every other release seem to completely break the client?

Downgraded to 1.90.0 and it works again.... does anyone even test these 'updates' before rolling them out?!

**Comment by zze0s** [comment]
Fixed in #780 and release being built in a few minutes.
