### ISSUE TITLE
Everything is being filtered

### ISSUE THREAD

**Issue by Nebarik** [autobrr/autobrr#784]
Intially I thought I was just being too specific with my filter so I pulled it back. I've got my required filter set to "Select All" pretty much everywhere. But everything is being filtered away and nothing is being sent to my Sonarr. 

Am I doing somehting stupid here or is "Select all" not wide enough still?

Example logs:

`13:32:50.000DEBUG [Movie/Xvid] Upside Down The Creation Records Story 2010 iNTERNAL BDRip x264-PEGASUS - https://www.iptorrents.com/details.php?id=5194152 - 1.51 GB
13:32:50.000DEBUG filter.Service.CheckFilter: (All) for release: Upside Down The Creation Records Story 2010 iNTERNAL BDRip x264-PEGASUS rejections: (resolution not matching. got: want: [2160p 1080p 1080i 810p 720p 576p 480p 480i], container not matching. got: want: [avi mp4 mkv])
13:32:50.000DEBUG release rejected: resolution not matching. got: want: [2160p 1080p 1080i 810p 720p 576p 480p 480i], container not matching. got: want: [avi mp4 mkv]`

`13:33:01.000DEBUG [Movie/HD/Bluray] Upside Down The Creation Records Story 2010 iNTERNAL 720p BluRay x264-PEGASUS - https://www.iptorrents.com/details.php?id=5194153 - 5.06 GB
13:33:01.000DEBUG filter.Service.CheckFilter: (All) for release: Upside Down The Creation Records Story 2010 iNTERNAL 720p BluRay x264-PEGASUS rejections: (container not matching. got: want: [avi mp4 mkv])
13:33:01.000DEBUG release rejected: container not matching. got: want: [avi mp4 mkv]`

**Comment by KyleSanderson** [comment]
> Intially I thought I was just being too specific with my filter so I pulled it back. I've got my required filter set to "Select All" pretty much everywhere. But everything is being filtered away and nothing is being sent to my Sonarr.
> 
> Am I doing somehting stupid here or is "Select all" not wide enough still?
> 
> Example logs:
> 
> `13:32:50.000DEBUG [Movie/Xvid] Upside Down The Creation Records Story 2010 iNTERNAL BDRip x264-PEGASUS - https://www.iptorrents.com/details.php?id=5194152 - 1.51 GB 13:32:50.000DEBUG filter.Service.CheckFilter: (All) for release: Upside Down The Creation Records Story 2010 iNTERNAL BDRip x264-PEGASUS rejections: (resolution not matching. got: want: [2160p 1080p 1080i 810p 720p 576p 480p 480i], container not matching. got: want: [avi mp4 mkv]) 13:32:50.000DEBUG release rejected: resolution not matching. got: want: [2160p 1080p 1080i 810p 720p 576p 480p 480i], container not matching. got: want: [avi mp4 mkv]`
> 
> `13:33:01.000DEBUG [Movie/HD/Bluray] Upside Down The Creation Records Story 2010 iNTERNAL 720p BluRay x264-PEGASUS - https://www.iptorrents.com/details.php?id=5194153 - 5.06 GB 13:33:01.000DEBUG filter.Service.CheckFilter: (All) for release: Upside Down The Creation Records Story 2010 iNTERNAL 720p BluRay x264-PEGASUS rejections: (container not matching. got: want: [avi mp4 mkv]) 13:33:01.000DEBUG release rejected: container not matching. got: want: [avi mp4 mkv]`

Erase your specific criteria for a true select all. None of those conditions exist on those names, therefore, your specific criteria doesn't match.

**Comment by zze0s** [comment]
Check the Sonarr examples we have on the docs: https://autobrr.com/filters/examples

For specifically the arrs I only recommend setting `resolution` and `source` as a bare minimum. Categories as well if you use indexers with both tv and movies. You can find some we have collected here: https://autobrr.com/filters/categories

Like you have in your example above, it's common for users to just select everything. Codec in particular is one of those and that is usually not announced (only some do), so then you will have a lot of rejections because of that.

So that in combination with using https://trash-guides.info to setup your arrs will make for an awesome combo :)
