### ISSUE TITLE
[FEATURE REQ] Add Pushover Notifications

### ISSUE THREAD

**Issue by buroa** [autobrr/autobrr#794]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to send notifications via Pushover

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zze0s** [comment]
There is already a PR for it: https://github.com/autobrr/autobrr/pull/598

**Comment by buroa** [comment]
@zze0s Awesome, thanks!
