### ISSUE TITLE
[FEATURE REQ] Filter feeds by  `seeder` / `leecher` / `published_time`

### ISSUE THREAD

**Issue by Siriussee** [autobrr/autobrr#815]
**Is your feature request related to a problem? Please describe.**
I use the `freeleech` feature to build up buffers from PTs. However, I noticed that the torrents grabbed by autobrr are usually not the optimal ones. For example, it grabs torrents with 200 seeders and only 1 leecher, which results in almost zero uploads. At the same time, a new torrent with only 1 seeder but 200 leechers is neglected (simply because it ranks after the 200-seeder torrent in the feed). 

**Describe the solution you'd like**
Introduce 3 new variables: `seeder`/`leecher`/`published_time` to `Filter > Advance > Freeleech`. 
The variables can be read from Jackett:
```
<item>
  <pubDate>Sat, 17 Dec 2022 01:00:17 -0800</pubDate>
  <torznab:attr name="seeders" value="302"/>
  <torznab:attr name="peers" value="302"/>
</item>
```
Add 3 filters on the variables:
1. `MAX SEEDER`: 10: Any torrent with more than 10 seeders is neglected.
2. `MIN LEECHER`: 100: Any torrent with less than 100 leechers is neglected.
3. `LATEST PUBLISH TIME`: 15 min: Any torrent with more than 15 minutes of published time is neglected.

**Describe alternatives you've considered**
Use 3rd party tools to monitor autobrr's downloads, [autoremove-torrents](https://github.com/jerrymakesjelly/autoremove-torrents) for example. The workflow will be like:
1. autobrr downloads a torrent $T_1$ and `max_download` is reached;
2. autoremove finds out A has seeder > 10, then delete $T_1$;
3. autobrr downloads a torrent $T_2$ since `max_download` is not reached;
4. Goto 2 until torrent  $T_n$ meets the requirement of autoremove.

However, this solution 
1. Needs A 3rd party tool monitoring the client (while the proposed solution is one shot);
2. Download bandwidth wasted for deleted download;
3. May trigger H&R rules due to unfinished downloads.

**Additional context**
N/A. Any thoughts and comments are welcome.

**Comment by zze0s** [comment]
Hey!

Some good ideas here. The option 3/published time is already implemented on the feed settings and called **Max age**.

And this is only relevant for torrents on rss and torznab so not sure if we should add this logic in the filters or in the feed settings itself like the Max age.

**Comment by Siriussee** [comment]
Thanks for the reply @zze0s .

For the `max_age` setting: I do check it (Settings > Feeds > Update Feed > Max age). It is not working as I expected and there is no document on this attribute (I walked through https://autobrr.com/configuration/feeds). Do you have documentation for this? I can help look into this issue (and raise a second issue if I confirm it).

As for where the filter should go, I still vote for `Filter > Advance > Freeleech`.

My use case is as follows:
1. Feeds monitor all new releases;
2. If there is a new release that matches what I have, hand it over to `cross-seed` (as the doc suggests).
3. If there is a freeleech release, hand it over to the downloader.

So, if the filter goes to `Settings > Feeds > Update Feed`, my use case (2) is broken since the feed would not return a full list of releases. A workaround can be keeping 2 versions of feeds, one for use case (2) (w/o filter), and another for use case (3) (w/ filter).

Possible Solution: Enable `Filter > Advance > Freeleech > new filter` only when the feed types are torznab/rss. Disable when it is irc. Let me know if there are any thoughts. :)
