### ISSUE TITLE
Crash when definition has undefined variable

### ISSUE THREAD

**Issue by paperclip-go-brr** [autobrr/autobrr#816]
**Version**
v1.23.0

**Describe the bug**
When creating a custom definition, and you define the `torrenturl` at `irc > parse > match > torrenturl` to be `"{{ .torrentUrl }}"` but in your parse lines you only have `torrentId` and *NOT* `torrentUrl`, then autobrr crashes without any meaningfull error message when it receives a message from the IRC server.

**To Reproduce**
1. Modify any definition to contain a variable name in `match.torrenturl` that is not defined in the `parse.lines` (see screenshot).

**Expected behavior**
When there is an error in the definition, like an undefined variable, i expect an error message explaining what happened, instead of crashing without any information as to why.

**Screenshots**
Here is an example of the variable name mismatch, which caused the crash.
![image](https://user-images.githubusercontent.com/112905434/230237871-9160b9f3-3399-456c-aa67-34446aef0d19.png)

**Additional context**
The last four log lines before the crash, and the subsequent first to messages of the restart.
```
{"level":"trace","module":"irc","network":"irc.rizon.net","time":"2023-04-06T01:07:13+02:00","message":"<-- :TokyoTosho!~TokyoTosh@Tokyo.Tosho PRIVMSG #tokyotosho :\u000310Size: 2.91GB"}
{"level":"debug","module":"irc","network":"irc.rizon.net","channel":"#tokyotosho","user":"TokyoTosho","time":"2023-04-06T01:07:13+02:00","message":"Size: 2.91GB"}
{"level":"trace","module":"irc","network":"irc.rizon.net","module":"announce_processor","time":"2023-04-06T01:07:13+02:00","message":"announce: queued line: Size: 2.91GB"}
{"level":"trace","module":"irc","network":"irc.rizon.net","module":"announce_processor","time":"2023-04-06T01:07:13+02:00","message":"announce: process line: Size: 2.91GB"}
{"level":"info","time":"2023-04-06T01:07:19+02:00","message":"Starting autobrr"}
{"level":"info","time":"2023-04-06T01:07:19+02:00","message":"Version: v1.23.0"}
```

**Comment by zze0s** [comment]
While this is a valid issue for custom definitions, I don't really think it's a critical one since it's one of those things that is figured out during development of a definition.

It's also hard to give a proper error message because the template function that deals with it does not return what was wrong I think.

Crashing fully could be prevented with a panic recoverer but imo it's one of those things that are supposed to work and only found during setup/development of the definition.
