### ISSUE TITLE
Orpheus: line not matching expected regex

### ISSUE THREAD

**Issue by crahzee** [autobrr/autobrr#831]
**Version**
1.23.0

**Describe the bug**
Regex fails to parse the release from the announce channel fails. 

`line not matching expected regex pattern: TORRENT: Biocym – Collector Of Chaos – WEB/FLAC/Lossless – deep.techno,electronic – https://orpheus.network/torrents.php?id=####### – https://orpheus.network/torrents.php?id=#######&torrentid=#######&action=download`

**To Reproduce**
Add Orpheus as an indexer

**Expected behavior**
Release matches regex pattern and is parsed

**Additional context**
This is happening with all releases from the announce channel. Possibly the format was updated and it no longer matches the regex pattern?

**Comment by martylukyy** [comment]
Thanks for opening this bug report!
We already know about this change in their announces and there will be a fix in v1.24.0.
