### ISSUE TITLE
Error "Forbidden" on user creation "onboard" page

### ISSUE THREAD

**Issue by A69Tor** [autobrr/autobrr#846]
**Version**
Version: 1.24.0

**Describe the bug**
During onboard process I am receiving a "Forbidden" error during user creation.

**To Reproduce**
1. Fresh install of v1.24.0 with no users
2. Load GUI, should take you to /onboard
3. Enter username/password and hit Create Account
4. Error appears in top right of screen indicating "Forbidden"

Chrome DevTools log only indicates the following error: POST http://xxx.xxx.xxx.xxx:7474/api/auth/onboard 403 (Forbidden)
Trace logging only indicates: `{"level":"trace","module":"http","type":"access","time":"2023-04-16T21:11:43-04:00","bytes_in":"37","bytes_out":10,"latency_ms":0.28418,"method":"POST","proto":"HTTP/1.1","remote_ip":"XXX.XXX.XXX.XXX:21168","status":403,"url":"/api/auth/onboard","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","time":"2023-04-16T21:11:43-04:00","message":"incoming_request"}`

**Expected behavior**
Creation of account and forwarding to login page

Browser: Chrome

**Comment by facundo59** [comment]
Workaround: downgrade your version to v1.23.0 > configure your username/password > upgrade.

**Comment by zze0s** [comment]
Hey. Thanks for reporting this. We'll get a fix out as soon as possible. 

Another workaround is to use `autobrrctl` to create the initial user. 

```bash
autobrrctl --config ~/.config/autobrr create-user USERNAME
```

See docs here: https://autobrr.com/configuration/autobrr#create-user-via-cli
