### ISSUE TITLE
OPS not working

### ISSUE THREAD

**Issue by garypiner** [autobrr/autobrr#850]
**Version**
v1.24.0

**Describe the bug**
The artist's name is returning as empty and isn't able to match the filter

from the logs(I've trimmed the comparison block as I have a lot of artist in it):
{
    "level": "debug",
    "module": "irc",
    "network": "irc.orpheus.network",
    "channel": "#announce",
    "user": "hermes",
    "time": "2023-04-18T08:22:22+01:00",
    "message": "TORRENT: Sanguisugabogg – Homicidal Ecstasy – CD/FLAC/Lossless – metal,rock – https://orpheus.network/... – https://orpheus.network/...?...&torrentid=....&action=download"
}

{
    "level": "debug",
    "module": "filter",
    "time": "2023-04-18T08:22:22+01:00",
    "message": "filter.Service.CheckFilter: (Orpheus) for release: Sanguisugabogg – Homicidal Ecstasy rejections: (artists not matching. got:  want: ..., Samia, Sanguisugabogg, Saweetie, ...)"
}

The regex was was changed recently is working correctly 
https://regex101.com/r/ATXZbp/1

**Comment by martylukyy** [comment]
We have identified the issue, but need to wait for a fix in an external library we are using here.
As soon as the fix in the external library happens we will push a fix in a timely manner.
