### ISSUE TITLE
[FEATURE REQ] Remove relevant filter actions when deleting a client.

### ISSUE THREAD

**Issue by gl0ryus** [autobrr/autobrr#854]
**Is your feature request related to a problem? Please describe.**
When removing a client, the filters will keep the action active. 

**Describe the solution you'd like**
When removing a client from the settings panel, please clean up the actions in filters for deleted clients.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by martylukyy** [comment]
Superseded by #856
