### ISSUE TITLE
anthelion + radarr does not works as expected

### ISSUE THREAD

**Issue by jaum20** [autobrr/autobrr#857]
**Version**
1.24.1

**Describe the bug**

The releases from anthelion IRC are not being correctly pased by Radarr. In the releases page, the releases from anthelion shoes the movie title instead of release name as the others trackers do:

![image](https://user-images.githubusercontent.com/36702273/232892287-02d8d5dd-8726-4978-b300-77c717835317.png)

So, if I had the movie monitored by radarr, it won't grab the release:

![image](https://user-images.githubusercontent.com/36702273/232892517-3930faf9-c960-4faf-acbb-f343b1b9c9dd.png)

**To Reproduce**
1. Add anthelion IRC
2. Add a radarr action
3. Add some movies to be monitored in radarr
4. When a release for a monitored movie is sent to radarr, it won't grab it

**Expected behavior**
Grab the movie or reject the release based on radarr preferences

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 arm
 - Browser Brave
 - Version [1.38.119 Chromium: 101.0.4951.67)

**Additional context**

**Comment by zze0s** [comment]
Hi! The do not announce the full release name, just title + release tags. We could likely change the pattern to grab the release tags or re-construct the `torrentName`.

We were waiting on the Ant devs to change the format but that never happened so we added it as is knowing there might be issues with the arrs.

**Comment by ahopelesshadow** [comment]
This should be fixed, the current release format is

11:39 <&Sauron> [Feature Film] Beverly Hills Cop III (1994) [H264 / MKV / Blu-ray / 1080p / AC3 / Subs / CtrlHD / Freeleech! / Filename: Beverly.Hills.Cop.III.1994.1080p.BluRay.DD5.1.x264-CtrlHD.mkv] [15.18 GiB - Uploader: Anonymous] https://anthelion.me/torrents.php?action=download&id=58911 - action,buddy.cop,comedy,crime,subtitles

**Comment by zze0s** [comment]
> This should be fixed, the current release format is
> 
> 11:39 <&Sauron> [Feature Film] Beverly Hills Cop III (1994) [H264 / MKV / Blu-ray / 1080p / AC3 / Subs / CtrlHD / Freeleech! / Filename: Beverly.Hills.Cop.III.1994.1080p.BluRay.DD5.1.x264-CtrlHD.mkv] [15.18 GiB - Uploader: Anonymous] https://anthelion.me/torrents.php?action=download&id=58911 - action,buddy.cop,comedy,crime,subtitles

Already fixed in [v1.31.0](https://github.com/autobrr/autobrr/releases/tag/v1.31.0). Please update :)
