### ISSUE TITLE
Data from deleted filters is getting transferred into new filters

### ISSUE THREAD

**Issue by martylukyy** [autobrr/autobrr#865]
**Version**
v1.24.1

**Describe the bug**
When deleting a filter and creating a new one, data from the old filter gets transferred into the new filters
which might lead to unwanted behavior with the new filter.
This does not only happen with the name field. It happens to other fields too.

**Video to Reproduce**

https://user-images.githubusercontent.com/35452459/233619609-e972f9aa-acd9-43d1-9a54-b1f43bc891f3.mp4

**Expected behavior**
When deleting a filter and creating a new one afterwards it should start without the data of the old filter.

**Comment by stacksmash76** [comment]
Probably same thing as #864
