### ISSUE TITLE
[FEATURE REQ] apprise notification support

### ISSUE THREAD

**Issue by Silent-Remux** [autobrr/autobrr#867]
Integrate apprise notifications.

[https://github.com/caronc/apprise](url)

**Comment by Silent-Remux** [comment]
> Apprise is written in Python and we can't bake that in since the autobrr backend is written in Golang.
> 
> There appears to be some API support for it tho: https://github.com/caronc/apprise-api Is that something you're using?

Ideally I would use that yes if autobrr supported it. Would be useful as it would allow you to push it to all of many other notification options apprise supports.

**Comment by onedr0p** [comment]
@zze0s not sure if you are aware but there is https://github.com/containrrr/shoutrrr

**Comment by onedr0p** [comment]
> The initial implementation for notifications used shoutrrr, or rather I tried using it. I could not figure out how to use it the way I wanted so it was quicker to build it from scratch with a few supported notification type.

Looks like you can just accept a "url" that the user provides like...

`gotify://gotify-host/token` or `ntfy://username:password@ntfy.sh/topic` or `discord://token@id`

Then you can add in the title and message to the request and send it via...

```go
url := "slack://token-a/token-b/token-c"
err := shoutrrr.Send(url, "Hello world (or slack channel) !")
```

**Comment by onedr0p** [comment]
Not sure I follow, the shoutrrr "url" would be stored in the database...

**Comment by onedr0p** [comment]
I never said it was, I was talking about alternative options...

**Comment by C0D3D3V** [comment]
For anyone who wantet to use the apprise Api, you can use the shoutrrr to send a request to the api like this:

`generic://apprise-api:8000/notify/apprise?template=json&disabletls=yes&messagekey=body&$tag=starr&$type=warning`

This is an example for the static configuration "apprise" and tag "starr*

**Comment by BoKKeR** [comment]
For anyone else struggling to make the notifications work, you have to enable at least one option in the global events for it to send out anything with the TEST button. Not great UX

<img width="682" height="1073" alt="Image" src="https://github.com/user-attachments/assets/afd26d5f-f191-4c07-bc92-db5888da198b" />
