### ISSUE TITLE
[FEATURE REQ] Action qBittorrent: add an option to chose the queue position.

### ISSUE THREAD

**Issue by AN1MATEK** [autobrr/autobrr#871]
**Is your feature request related to a problem? Please describe.**
When using torrent queuing, all new torrents get sent to the bottom of the queue. I want autobrr scripted torrents to be downloaded as fast as possible, they need to go at the top. 

**Describe the solution you'd like**
A simple toggle under qBittorrent > Action > Advanced that says "Set at the top of the queue" would be ideal and simple to implement. 

**Describe alternatives you've considered**
For now just manually intervening.

**Additional context**
Thanks a lot for the awesome app.

**Comment by zze0s** [comment]
Hi,

Looks like it will be available in qbit first in 4.6.X releases according to https://github.com/qbittorrent/qBittorrent/pull/18518

**Comment by facundo59** [comment]
Thanks for the heads up. Do you plan to wait until is included in there or is there any change of implementing this with an API call in autobrr itself?

**Comment by s0up4200** [comment]
Solved in https://github.com/autobrr/autobrr/pull/1315
