### ISSUE TITLE
qBittorrent will break when filter's action add tags

### ISSUE THREAD

**Issue by Luvmon** [autobrr/autobrr#909]
**Version**
1.25.0

**Describe the bug**
The qBittorrent WEB-UI is broken when I add "{{.Indexer}}" in TAGS of filter's action with TYPE "qBittorrent".
BUG 1: The data(eg. value of Up Speed or Down Speed) won't change unless you refresh the page, and it will stuck at another value after you refresh the page.
BUG 2: You can't see General info or Tracker info or Peer info when you hit a torrent.
BUG 3: Data in the left column is not fully displayed, like TRACKERS, number of TAGS.
BUG 4: You can't even see the whole torrents already added to the client.

In the image below you can see there shows nothing in the General Area.
https://imgur.com/xTcFySg

**To Reproduce**
1. Add a filter, I used to filter the Redacted.
2. Go to 'Actions'
3. Add a new one action, TYPE choose "qBittorrent", CLIENT choose "qBittorrent" which added in the setting page. And write "{{.Indexer}}" in the TAGS field.
4. When a new torrent add to the qBittorrent client, then the error occures.

**Expected behavior**
I want to know how to back to normal qBittorrent. I tried uninstall qBittorrent and install again, it stills the same.

**Screenshots**
https://imgur.com/LIRkAhI
https://imgur.com/t8iCDJJ

In the first screenshot, all STATUS and TRACKERS works well, and in the second screenshot, you can see all "0" in STATUS, and the number of torrents don't match.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [chrome, edge]
 - Version [108.0.5359.72, 108.0.5359.72]

**Additional context**
BUG 1 and 3 always happen.
BUG 4 happened when qbittorrent version is less than 4.4
BUG 2 happened only in chrome, so this maybe count on me.

**Comment by zze0s** [comment]
Hi,

Did you potentially add a tag with a space in front? You can find that in the `qBittorrent.conf` file. Not sure of the data path, but on linux it's usually in `~/.config/qBittorrent`. Look that up on a search engine for windows.

In that file scroll down to or search for `Session\Tags`. It will be a list of tags. If any of them look like `, " indexer"` then you've added a tag with space in front and it makes qbit brake the UI.

You can remove bad tags via the qbit API if you have it enabled. Will edit with a solution later.

**Comment by Luvmon** [comment]
`Session\Tags=redacred\t`

The above is shows in `qBittorrent.conf`, I don't know if this is normal. And I don't know how to remove bad tags via the qbit API because I don't know where to find the API.

**Comment by zze0s** [comment]
That `\t` is a tab character so that makes sense it's not working correctly.

You are using the qbit API since you connect autobrr to it. If you have WSL (windows subsystem linux) on windows you can easily do the requests with `curl`, or install/use something like https://www.postman.com/ to make requests.

You first need to login to get a cookie. Set PORT to the same used in autobrr qbit client, username and password:

```sh
curl -X POST http://127.0.0.1:PORT/api/v2/auth/login
   -H "Content-Type: application/x-www-form-urlencoded" 
   -d "username=USERNAME&password=PASSWORD" 
```

Then to remove the tag:

```sh
curl -X POST http://127.0.0.1:PORT/api/v2/torrents/deleteTags
   -H "Content-Type: application/x-www-form-urlencoded" 
   -d "tags=redacted\t" 
```

I think that should work. If it does not you can remove all tags from all torrents, that might be easier, but you'll loose tags so.

```sh
curl -X POST http://127.0.0.1:PORT/api/v2/torrents/removeTags
   -H "Content-Type: application/x-www-form-urlencoded" 
   -d "hashes=all&tags=all" 
```

**Comment by zze0s** [comment]
You need to pass the cookie. Do login again, but add `-v` for verbose output. It will show the cookie value. Then for the other request you must add the cookie. Good info here. https://reqbin.com/req/c-bjcj04uw/curl-send-cookies-example

`--cookie "Name=Value"`

**Comment by Luvmon** [comment]
I tried the new command to get the cookie and did not return any errors, but it did not succeed in deleting the tags. Eventually, I deleted all the tagged torrents, and qBittorrent returned to normal.

Thanks for your help.
