### ISSUE TITLE
MyAnonaMouse issues - 401 unrecoverable error

### ISSUE THREAD

**Issue by IHateIssues** [autobrr/autobrr#929]
**Version**
v1.25.0

**Describe the bug**
When MyAnonaMouse tracker is added, it's throwing errors for some reason when trying to auto-download content form filters. Downloading itself works just fine with the same cookie (mam_id) for prowlarr. I am not sure about the meaning of the error either, as it's nothing specific. IRC works fine and status is green. I also have few other trackers like torrentleech, iptorrents, filelist...etc. that works without issue, so it's only specific to this one tracker, but like I said, prowlarr works just fine with the same mam_id, so I am not sure what could be wrong. If you would need some specific logs, let me know.

```
Type: QBITTORRENT
Client: qBittorrent
Filter: [Freeleech] Latest books MAM
Time: 2023-05-12 20:03:53
Rejected: error downloading torrent file for release: The Marxification of Education: Paulo Freire's Critical Marxism and Theft of Education by James Lindsay [English / m4b]: All attempts fail:
#1: unrecoverable error downloading torrent (The Marxification of Education: Paulo Freire's Critical Marxism and Theft of Education by James Lindsay [English / m4b]) file (https://www.myanonamouse.net/tor/download.php?tid=NUMBER) from 'myanonamouse' - status code: 401: unrecoverable error
```

**To Reproduce**
1. Add MAM through autobrr
2. Add new filter and rules for MAM and wait for them to trigger
3. Torrent is not being added into qbittorrent and it's throwing error in autobrr (error is above)

**Expected behavior**
autobrr should add the release to qbittorrent for download

**Screenshots**
![Snímka obrazovky 2023-05-12 184207](https://github.com/autobrr/autobrr/assets/133397479/fa884723-26c3-4194-938d-57f5d33f980b)

**Additional context**
I am using docker and VPN Gluetun tunnel for all my containers. qBittorrent version is 4.5.2,

**Comment by zze0s** [comment]
Hi! MAM makes it pretty annoying to setup. Is your Prowlarr also using your VPN so it's a shared IP? The cookie must be allowed for that ip.

There's been a lot of it talked about on [our Discord](https://discord.gg/WQ2eUycxyT) so I'd advice you to join that and search because there's multiple threads about MAM.

**Comment by IHateIssues** [comment]
> Hi! MAM makes it pretty annoying to setup. Is your Prowlarr also using your VPN so it's a shared IP? The cookie must be allowed for that ip.
> 
> There's been a lot of it talked about on [our Discord](https://discord.gg/WQ2eUycxyT) so I'd advice you to join that and search because there's multiple threads about MAM.

I actually found out what's the issue and it's related to this feature request: https://github.com/autobrr/autobrr/issues/861

I know about the whole VPN stuff and issues already, although I already figured out how to do it correctly and communicated with their staff in that regards, but the whole VPN issue was only for downloading/seeding, not accessing website or IRC itself. 

This issue is because autobrr doesn't differentiate between VIP Freeleech and Freeleech for all users, which then causes the 401 (unathorized) error when I - as not VIP user - try to download a VIP freeleech. I will try to confirm my claim by activating VIP, since I have enough points to give myself VIP for few weeks, but I am pretty sure this is the issue. If autobrr was about to somehow get user's VIP status and then make difference between those 2 types of Freeleech torrents on MAM with some checkbox for filters and rules, this error shouldn't be a problem anymore.

Also to answer your question, yes Prowlarr uses same VPN tunnel as autobrr without a problem with the correct setup of mam_id on the MAM website. They even allow dynamic IPs as long as you activate the specific setting in their website settings. There isn't really a problem with browsing the site on VPN or downloading .torrent files on any VPN (as long as staff is informed that you use VPN and which specific provider) on MAM. The only problem is with downloading/seeding torrents using your bittorrent client and with the passkey/IP missmatch, but it's simple to fix with the correct method described on their forums. This shouldn't be at all related to the autobrr freeleech issue though.

**Comment by IHateIssues** [comment]
Also just read here that including "mam_id=" before the cookie is required from older issue opened here, so I will try that as well, but I am still pretty sure there is no way of downloading freeleech stuff for VIP only without actually being a VIP, so might be 2 issues combined.

**Comment by IHateIssues** [comment]
After adding the mam_id= part to the cookie it started snatching torrents correctly. I think it might be worth mentioning that this part needs to be added or maybe even add it for users automatically? However now new issue arises with torrents not actually downloading since autobrr doesn’t recognize freeleech only for vip / freeleech for all. I hope you can look at the possibility of making difference between these two in future versions :) @zze0s
