### ISSUE TITLE
Auth issues / login issues

### ISSUE THREAD

**Issue by martylukyy** [autobrr/autobrr#941]
**Version**
v1.26.1

**Describe the bug**
So I did some testing with the auth issues we have been having lately.
Right now, there are three bugs with our login page i think.

First, if the basic auth of the webserver becomes invalid, users will get a toast with `Wrong password or username!`
when trying to log in, even though they have entered the correct credentials. 
This behaviour will persist until a hard refresh of the login page which results in the user getting a browser prompt for the basic auth.
After providing the correct credentials for the basic auth you can log into autobrr again.

So you might ask yourself right now: Why should the basic auth become invalid?
Let me introduce you to the second issue. 
When entering wrong credentials, the basic auth will become invalid, but the user won't notice that until a hard refresh 
because you are not getting a browser prompt for the basic auth if you don't hard refresh the page. 
So you are basically stuck on the login page without any hint of you basic auth being invalid.

Third, if the session secret in the config.toml or the session token of the cookie is not valid for the current session, 
it will throw an recoverable error while it should theoretically just put the user back to the login page.

The first two issues should have a higher priority, since it has the potential of getting the user stuck. 
On the third issue the user can just click the `Reset page state` button and the you will be able to login as intended.

**Comment by stacksmash76** [comment]
The thing here is to ditch Basic auth altogether and implement argon2id hashing in JS.

There's another issue here: caching of the template page where JS is getting injected. This can be done in two ways:
1) adding to the main html template:
```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"/>
<meta http-equiv="Pragma" content="no-cache"/>
<meta http-equiv="Expires" content="0"/>
```
which might be less than optimal for the majority of use cases.
2a) `Cache-Control: max-age=0,no-cache,no-store,post-check=0,pre-check=0` header provided by the backend with certain 4XX responses should do it, maybe?
2b) the same header, but when serving index.html and when the last interaction time with the api is (say) >= 15 min (might be harder if no hooks are available on user session token access)

**Comment by rkodirkhonov** [comment]
Based on the description of the case, if we do some improvements in the log in page: 
Update the onError callback in the loginMutation to display the correct error message when wrong credentials are entered:
1) Incorrect toast message display:
```
const handleError = () => {
  if (!toast) {
    throw new Error("Toast component not found");
  }
  toast.custom((t) => (
    <Toast type="error" body="Invalid credentials!" t={t} />
  ));
};
```
or
```
onError: () => {
  toast.custom((t) => (
    <Toast type="error" body="Invalid credentials!" t={t} />
  ));
}
```
2) Real-time authentication validation:
```
const checkUserAuthentication = () => {
  APIClient.auth.checkAuthentication()
    .then((response) => {
      const isAuthenticated = response.data.isAuthenticated;
      setAuthContext({
        username: variables.username,
        isLoggedIn: isAuthenticated
      });
      if (isAuthenticated) {
        navigate("/");
      }
    })
    .catch((error) => {
      console.error(error);
      // Display error message to user
      toast.error("Failed to check authentication. Please try again.");
    });
};

// Call checkUserAuthentication after successful login and on component mount
useEffect(() => {
  checkUserAuthentication();
}, []);

```
3) Or maybe it is necessary to try (if not tried):
```
onError: (error) => {
  if (error.response.status === 401) {
    navigate("/login");
  } else {
    // Log the error to the console
    console.error(error);
  }
}
```
