### ISSUE TITLE
Not joining channels on Superbits (no errors)

### ISSUE THREAD

**Issue by fredrikscode** [autobrr/autobrr#959]
**Version**
v1.26.2 (Same issue on atleast the previous version as well. That's the version I had when I set up this indexer)

**Describe the bug**
Not joining channels on the Superbits IRC server. No errors with the following configuration options enabled:
- ircFramework: true
- raw: true

**Log**
```
21:16:25.000
DEBUG
irc.service: update network: &{ID:2 Name:SuperBits Enabled:true Server:irc.superbits.org Port:6697 TLS:true Pass: Nick:REDACTED|bot Auth:{Mechanism:NICKSERV Account:REDACTED Password:REDACTED} InviteCommand: Channels:[{ID:4 Enabled:true Name:#autodl Password: Detached:false Monitoring:false}] Connected:false ConnectedSince:0001-01-01 00:00:00 +0000 UTC}
21:16:25.000
DEBUG
starting network: SuperBits
21:16:25.000
DEBUG
connect attempt 0
21:16:25.000
WARN
network unhealthy
21:16:25.000
DEBUG
connected to: SuperBits
21:16:25.000
DEBUG
connected at attempt 0
21:16:26.000
DEBUG
NickServ: { PRIVMSG [NickServ IDENTIFY REDACTED false map[] map[]}
21:16:26.000
DEBUG
NickServ: { PRIVMSG [NickServ IDENTIFY REDACTED false map[] map[]}
21:16:26.000
DEBUG
NickServ: { PRIVMSG [NickServ IDENTIFY REDACTED false map[] map[]}
21:16:26.000
DEBUG
NOTICE nickserv logged in: [REDACTED|bot Password accepted - you are now recognized.]
```
It'll just stay at the last line, no more output for 15min+.

**To Reproduce**
Add Superbits indexer with NickServ login and setup to join the channel #autodl or #superbits.announce

**Expected behavior**
Connected to IRC server and join mentioned channel(s)

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser: Brave
 - Version: 1.51.118

**Additional context**
Log file looks the same for the channel #superbits.announce. Config file is unchanged except for enabling debug options mentioned above due to this issue. Not sure how to troubleshoot since I can't get any more log output.

**Comment by zze0s** [comment]
Hey! I have it setup with SASL and working. Nick and Account is a grouped nick, and pass for the main nick of that group. The only usable channel is `#autodl` autobrr.

If that still fails, try set auth mechanism to None and remove Account and Password, restart autobrr and see if that makes any difference.

**Comment by fredrikscode** [comment]
> Hey! I have it setup with SASL and working. Nick and Account is a grouped nick, and pass for the main nick of that group. The only usable channel is `#autodl` autobrr.
> 
> If that still fails, try set auth mechanism to None and remove Account and Password, restart autobrr and see if that makes any difference.

I appreciate the quick reply. Unfortunately that doesn't do it for me. Still the same output. I tried setting nick to the bot nickname + bot nickname for the account then I switched account to my own but bubkis.

**Comment by zze0s** [comment]
I just tested and the channel does not require a registered user. Set nick to something like username-bot2, clear account and password, set mechanism to None. That does work.

**Comment by fredrikscode** [comment]
> I just tested and the channel does not require a registered user. Set nick to something like username-bot2, clear account and password, set mechanism to None. That does work.
> 
> And also, set log level to TRACE and check the console or log file instead of the browser logs page. The one in the ui does not show everything because some limitations of how it's sent.

Aye, that worked. For some reason it can't join while registered.. hmpf. I've spammed a couple of indexers now since I forgot to disable them while troubleshooting so I'll cool down a bit and try and post a log here later. If not only for documentation purposes :)

Thank you mate!
