### ISSUE TITLE
[FEATURE REQ] Sonarr/Radarr: add ability to specify downloadClientId

### ISSUE THREAD

**Issue by Schaka** [autobrr/autobrr#961]
**Version**
v1.26.2

**Describe the bug**
I'm not sure this is a bug/feature or how the decisions are made. In fact, I'm still trying to figure out if autobrr causes this.
In Sonarr/Radarr, I have 2 clients set up. One for public/semi-private trackers that I don't seed very long on and one for private trackers with a minimum seed time of 90 days. **In Autobrr, I only have Sonarr/Radarr set up as download clients, nothing else.**

In both servarr applications, each indexer is assigned to a specific client. This is an example - qBittorrent is the wrong client. For TL, qBittorrent-semi-private is set:
![image](https://github.com/autobrr/autobrr/assets/2223171/4bb759c7-4149-4945-bc0f-276610cb30ab)
![image](https://github.com/autobrr/autobrr/assets/2223171/acea2dd8-949f-4a18-9cdb-2c6d3d2fbd95)

What I've noticed is that when autobrr picks up a release and sends it to Sonarr/Radarr, it ends up in the wrong client. It's almost as if the client settings are ignored. Thankfully, I've caught it in time before it got removed from the client and potentially caused HnR.

So I guess my question is, is there any way to tell autobrr which client the servarr application is supposed to use? 

Log from Radarr:
```
2023-05-25 09:35:05.3|Info|ReleasePushController|Release pushed: Torrent Name 1999 1080p BluRay DD+5 1 x264-playHD - https://www.torrentleech.org/rss/download/<id>>/(removed)/Torrent+Name+1999+1080p+BluRay+DD+5+1+x264-playHD.torrent
2023-05-25 09:35:05.3|Info|DownloadDecisionMaker|Processing 1 releases
2023-05-25 09:35:05.7|Info|DownloadService|Report for Torrent Name (1999) sent to qBittorrent from indexer torrentleech. Torrent Name 1999 1080p BluRay DD+5 1 x264-playHD
```

**Comment by KyleSanderson** [comment]
so, certainly not an autobrr bug. There's a downloadClientId field that's optional but could be used to set on the push. Your servarr app selecting a client when that field is missing falls into their domain. (If it's random, or the first configured, I would consider that a defect if autobrr did that).

I'd be curious about z's thoughts. There's certainly more that can be done here, but for now I believe this is a feature request.

**Comment by Schaka** [comment]
Thank you, that explains so much. I noticed the downloadClientId missing in the logs of my own rarrnomore for some requests. 

I'll create an issue with radarr - it's possible that when calling the specific endpoint you're calling, it ignores their settings and just picks the torrent client based on priority. I suspect that's what's happening based on what I've seen. I'll change the priorities around for now.

I assume the endpoint you're calling here is `/api/v3/release/push`?

**Comment by nateify** [comment]
I would like to bump this and show some findings. I did not deep dive into the docs or code of Sonarr to see if this is intended behavior but it seems plausible. I had an indexer named "BHD" which is configured in Sonarr to always go to 1 specific download client. In this screenshot we see the name BHD before I had used autobrr: https://files.catbox.moe/h6qc05.png

After I used autobrr with a similar setup to the OP I also saw the behavior of using the wrong upload client, however in the far right column it has a different name beyondhd: https://files.catbox.moe/ddwntx.png

I assume this is why the indexer does not match and Sonarr in my case ignores the indexer "BHD" set to go to a download client, and instead sends to a download client with a higher priority just as in OP's screenshot.

I have tested if renaming the indexer in Sonarr is enough to get the intended behavior, instead I opted for a safer workaround of changing my default download client so I too do not get HnR. I think to cover the user case safely autobrr should expose the downloadClientId in the action level so we can customize it per filter.

**Comment by Schaka** [comment]
I had forgotten about this issue. I set my client priority in Sonarr as well - I don't use autobrr on indexers that would use the "public" client anyway. I suggest until this is solved, everyone finding this issue try and implement a similar workaround.

**Comment by zze0s** [comment]
Have a working PR for this now. There is however no user friendly way to get the `downloadClientId` in the arr without looking at the network responses in browser console :thinking: 

That could be improved on their end, but we'll ship this anyway.
