### ISSUE TITLE
Mylar and LazyLibrarian support

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#964]
The main clients have been added, new ones would like to have support for these :)

**Comment by zze0s** [comment]
Neither of those projects are maintained for the past 4-5 years and has lots of critical bugs/CVEs etc.

**Comment by srobies** [comment]
Any chance of revisiting this? LazyLibrarian seems to be maintained at this repo: https://gitlab.com/LazyLibrarian/LazyLibrarian
