### ISSUE TITLE
Environment variables are not picked up unless option is defined in `config.toml`

### ISSUE THREAD

**Issue by onedr0p** [autobrr/autobrr#969]
**Version**
1.26.2

**Describe the bug**

Env vars are not picked up unless setting is defined in `config.toml`

**To Reproduce**

1. Set a env var that is not defined or commented out in the `config.toml`
2. Notice how the option does not get set

**Expected behavior**

Any env var should be able to be set wether defined in the `config.toml` or not.

**Comment by KyleSanderson** [comment]
I think what we want to do is register the keys from:
https://github.com/autobrr/autobrr/blob/d31866b03e376ac9bc07411935c0c7010066bbc1/internal/config/config.go#L183

before binding the environment variables here:
https://github.com/autobrr/autobrr/blob/d31866b03e376ac9bc07411935c0c7010066bbc1/internal/config/config.go#L243

This way Viper is aware that the keys exist, and we don't have to call https://pkg.go.dev/os#Environ and bind AUTOBRR__ by hand or something after reading.

Viper I think can do this if we use reflect to turn it into a map[string]* via https://pkg.go.dev/github.com/spf13/viper#MergeConfigMap

But, as with all things viper, we've been hurt before - so just a thought anyways.
