### ISSUE TITLE
Unable to delete filter or client when using Postgres

### ISSUE THREAD

**Issue by onedr0p** [autobrr/autobrr#973]
**Version**

1.26.2

**Describe the bug**

I am unable to delete filters when using postgres

```
Error

{"message":"error executing query: pq: update or delete on table \"action\" violates foreign key constraint \"release_action_status_action_id_fkey\" on table \"release_action_status\""}
```

I am also unable to delete a client:

```
{"message":"pq: isolation level not supported: 3"}
```

**To Reproduce**

Deploy autobrr with postgres, create a filter and client and try to delete them

**Expected behavior**

Filter can be deleted

**Comment by buroa** [comment]
Also seeing this as well.

**Comment by onedr0p** [comment]
I'm seeing the age issue as well but didn't know it was related to postgres 🤣

**Comment by onedr0p** [comment]
I fixed the age issue by removing the TZ environment variable.

**Comment by buroa** [comment]
> I fixed the age issue by removing the TZ environment variable.

Fixed for me as well. Weird.

**Comment by zze0s** [comment]
> > I fixed the age issue by removing the TZ environment variable.
> 
> Fixed for me as well. Weird.

👀 

That is super strange. There are som badly configured Foreign Keys which is the core issue and can be fixed with a migration, but I don't get how removing the TZ would fix that 🤔 

Will debug later this week.
