### ISSUE TITLE
[FEATURE REQ] Dynamic Customized Save path

### ISSUE THREAD

**Issue by DirectorX** [autobrr/autobrr#974]
**Describe the solution you'd like**
allow to set custom save path with predefined variables like `series name`,  `year` etc

![demo](https://i.ibb.co/K0cZ2By/demopng.png)

**Comment by s0up4200** [comment]
These are the currently supported macros: https://autobrr.com/filters/actions#macros

**Comment by DirectorX** [comment]
so `/media/series/{{.Title}}/{{.Title}} {{.Season}}` should do the job for me?

**Comment by s0up4200** [comment]
Yeah that should work 👍

**Comment by DirectorX** [comment]
thanks for the quick answers!
