### ISSUE TITLE
HD-Torrents, Alpharatio "the account does not exist"

### ISSUE THREAD

**Issue by bulletproof2k** [autobrr/autobrr#977]
v1.26.2 Latest

There is no connection to the announcement channels of the above indexers.

I set up everything according to the instructions from the wiki.

Connection with indexers.

**Desktop (please complete the following information):**
Windows 11 Pro
Yandex Browser
Latest

There were no errors when setting up indexers. The only thing is that after turning on the added indexer channel, they all disappear and appear only after several reboots. And the newly added ones are marked in red.
![2023-06-03_22-08-54](https://github.com/autobrr/autobrr/assets/1818579/15255d69-ef97-48e9-b564-dfa092da6dc5)
![2023-06-03_22-10-14](https://github.com/autobrr/autobrr/assets/1818579/8491857b-75ac-4a97-bcd4-ea6cba00bced)

**Comment by bulletproof2k** [comment]
NickServ: bulletproof2k
Grouped nicks:
HD-T: bprf2k-bot

**Comment by zze0s** [comment]
Do you have multiple of P2P-Network added in IRC networks? If you have multiple different nicks it will create multiple instances of the network. You have two grouped nicks, but you can get by with using just one of them.

**Comment by bulletproof2k** [comment]
I didn't add other networks on my own, but set them up through an indexer. After that, they all disappeared, even those that are configured without errors. After the reboot, the following have not yet appeared :(
![2023-06-07_10-05-16](https://github.com/autobrr/autobrr/assets/1818579/a6f91976-c79a-4ed1-b5d0-fc6ee938f759)
