### ISSUE TITLE
No releases shown in view screen

### ISSUE THREAD

**Issue by Silent-Remux** [autobrr/autobrr#985]
**Version**
1.27.0

**Describe the bug**
No releases shown in Settings, IRC, View

**To Reproduce**

I waited until announce hit but there was no releases shown in Settings, IRC, View. Just a blank box.

**Expected behavior**

Releases shown.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4
 - Browser: Firefox 114.0.1

**Comment by martylukyy** [comment]
Which indexer does that bug occur for?

**Comment by Silent-Remux** [comment]
> Which indexer(s) does that bug occur for?

btn

**Comment by martylukyy** [comment]
We have received reports of that bug with BTN and AR and will look into it.
